#!/usr/bin/env python3
"""
rebind_office.py — report-regeneration pipeline stage 3 for the OFFICE lane: the Word
(`.docx`) surgical output engine (the `rebind-office` skill).

The Office analogue of `skills/rebind-html/rebind_html.py`. Applies a Binding Manifest
(`knowledge/binding-manifest.schema.json`, `format: "office"`) to a COPY of a `.docx`
template ("surgeon, not a renderer" — `knowledge/core-architecture-spec.md` §1) and emits
the regenerated `.docx`. It works on a copy the whole way: read `word/document.xml` out of
the OPC/ZIP package with stdlib `zipfile`, edit those bytes via the SHARED OOXML resolver in
`scripts/rr_anchor.py` (this module NEVER re-implements anchor resolution), then re-zip —
every OPC part other than the ones a binding names is copied through byte-for-byte.

Per §4's node taxonomy:

    frozen       — NO mutation. After every other binding is applied, the engine re-resolves
                   the node in the template AND the output and proves its outer OOXML byte
                   span is identical (`_assert_frozen_unchanged`) — a defensive proof, not an
                   assumption. `frozen` is EARNED upstream (the manifest's job); rebind only
                   guarantees a frozen node did not move.
    surgical     — STRIP the old value at the anchor, THEN WRITE the new one — two separate
                   byte splices, in that order (zero-literal construction). At the instant
                   between them the node provably carries no old instance value, by
                   construction, not by a downstream check. The value lives in the run/cell's
                   `w:t` text; run properties (`w:rPr`) and every other child are preserved.
    regenerate   — Same strip-then-write zero-literal invariant. A prose/run node is rebuilt
                   from new data via stdlib `string.Template` (dotted-placeholder subclass;
                   `jinja2` is OPTIONAL acceleration for native `{{ }}`/`{% %}` control
                   syntax). A raster/`w:drawing` node is force-regenerated by REPLACING the
                   referenced `word/media/*` binary with a FRESH capture supplied in new-data
                   — never by transplanting the old pixels, per the spec's construction rule
                   ("a transplanted binary blob cannot be proven data-free").
    needs-review — Left completely untouched, but a visible OOXML marker run/paragraph
                   (carrying a machine-readable token) is inserted adjacent to it, and it is
                   logged. Never ships silently — guarantee #2 made mechanical for Office.

Bindings are applied in **reverse document order** (RT1-F10): each anchor is a stable node
identity re-resolved on the current bytes just before its edit, and processing from the end
of the document backward means an earlier edit's byte/index shifts can never invalidate a
not-yet-applied anchor. (Known constraint: a `needs-review` marker inserted as a run that
*precedes* a `frozen` run in the SAME paragraph would shift that frozen run's sibling index;
the upstream classifier does not produce that pairing, and it is out of scope here.)

Usage:
    python3 rebind_office.py --template t.docx --manifest m.json --new-data d.json --out o.docx
    python3 rebind_office.py --template t.docx --manifest m.json --new-data d.json --out o.docx --pretty

Exit codes:
    0 — success (output written; a JSON change-manifest printed to stdout)
    2 — usage / path-guard / manifest-schema / anchor-not-found / missing-data-query /
        missing-new-data-key / invalid-docx error (message on stderr + a best-effort JSON
        error object on stdout)

Design constraints (binding):
    - stdlib-first: argparse, base64, io, json, os, posixpath, re, string, sys, zipfile,
      xml.etree. NO pip installs. `python-docx` / `docxtpl` are detected for parity only
      (the byte-splice engine is the SOLE code path); `jinja2` is optional acceleration for
      regenerate templates that use native Jinja control syntax.
    - Runs unmodified on Python 3.9.6: `from __future__ import annotations`; no PEP 604
      `X | Y` unions in runtime expressions, no `match` statement.
    - Path-guarded (mirrors ../rebind-html/rebind_html.py / ../../scripts/seed_defects.py):
      every path is relative or an in-repo absolute path, no `..`, must resolve inside the
      repo root; `--out` may never equal `--template` (works on a COPY).
    - No network, no subprocess inside the engine.

Fixture: tests/fixtures/report-regeneration/sample-report.docx. Shared OOXML anchor
grammar + resolver: ../../scripts/rr_anchor.py. Manifest shape: ../../knowledge/
binding-manifest.schema.json. Full architecture: ../../knowledge/core-architecture-spec.md
§1/§2.1/§4.
"""
from __future__ import annotations

import argparse
import base64
import io
import json
import posixpath
import re
import string
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path
from typing import Any

# The SHARED anchor resolver (../../scripts/rr_anchor.py) OWNS the OOXML anchor contract —
# rebind-office resolves EXACTLY the grammar infer-office emits, and never re-implements it.
_SCRIPTS_DIR = Path(__file__).resolve().parents[2] / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))
import rr_anchor  # noqa: E402

# Optional acceleration (graceful, non-load-bearing — mirrors infer_office._ACCEL). The
# byte-splice surgical engine below is the sole code path regardless of what is importable.
_ACCEL = None  # "docxtpl" / "python-docx" / None — an optional-accelerator marker only
try:  # pragma: no cover - environment-dependent
    import docxtpl  # type: ignore  # noqa: F401

    _ACCEL = "docxtpl"
except Exception:  # pragma: no cover
    try:
        import docx  # type: ignore  # noqa: F401

        _ACCEL = "python-docx"
    except Exception:
        _ACCEL = None

try:
    import jinja2  # optional acceleration only — every stdlib-only template still works
except ImportError:  # pragma: no cover - exercised whenever jinja2 isn't installed
    jinja2 = None

SCHEMA = "report-regeneration/rebind-office@1"
VALID_CLASSES = ("frozen", "surgical", "regenerate", "needs-review")
DOCUMENT_PART = "word/document.xml"
DOCUMENT_RELS_PART = "word/_rels/document.xml.rels"
CONTENT_TYPES_PART = "[Content_Types].xml"
NEEDS_REVIEW_TOKEN = "[[REBIND-NEEDS-REVIEW]]"


class RebindOfficeError(Exception):
    """Raised for any anchor-not-found, unsupported-anchor-kind, manifest-schema violation,
    missing-data-query, missing-new-data-key, invalid-docx, or path-guard failure. Every raise
    means "abort the whole run, write nothing" — never a partial or guessed rebind (the same
    never-silently-no-op discipline as rebind_html.RebindError)."""


# ── path safety (mirrors ../rebind-html/rebind_html.py _repo_root()/_guard_path()) ────────


def _repo_root() -> Path:
    here = Path(__file__).resolve().parent
    root = here
    for _ in range(10):
        if (root / ".repo-layout.json").is_file() or (root / "AGENTS.md").is_file():
            return root
        if root.parent == root:
            break
        root = root.parent
    # Fallback: this file lives at plugins/report-regeneration/skills/rebind-office/rebind_office.py
    return (here / ".." / ".." / ".." / "..").resolve()


def _guard_path(raw: str, *, must_exist: bool) -> Path:
    """Resolve `raw`, reject traversal / absolute-escape. Raises RebindOfficeError on violation."""
    if not raw:
        raise RebindOfficeError("empty path")
    p = Path(raw)
    if p.is_absolute():
        raise RebindOfficeError(f"absolute paths are not allowed: {raw!r}")
    if ".." in p.parts:
        raise RebindOfficeError(f"path traversal ('..') is not allowed: {raw!r}")
    repo_root = _repo_root().resolve()
    resolved = (Path.cwd() / p).resolve()
    try:
        resolved.relative_to(repo_root)
    except ValueError as exc:
        raise RebindOfficeError(f"path escapes the repo root: {resolved}") from exc
    if must_exist and not resolved.is_file():
        raise RebindOfficeError(f"input file not found: {raw!r} (resolved {resolved})")
    return resolved


# ── new-data resolution + template render (mirrors rebind_html; kept local so the Office ──
# ── engine is self-contained) ──


def lookup_path(data: Any, dotted_path: str) -> Any:
    cur = data
    for part in dotted_path.split("."):
        if isinstance(cur, dict) and part in cur:
            cur = cur[part]
        else:
            raise RebindOfficeError(
                f"new-data has no value at path {dotted_path!r} (missing segment {part!r})"
            )
    return cur


class _DotLookup:
    """dict-like adapter so string.Template.safe_substitute resolves dotted placeholders
    (${a.b.c}) against a nested new-data JSON object."""

    def __init__(self, data: Any) -> None:
        self._data = data

    def __getitem__(self, key: str) -> Any:
        return lookup_path(self._data, key)


class _DottedTemplate(string.Template):
    idpattern = r"[_a-zA-Z][_a-zA-Z0-9]*(?:\.[_a-zA-Z][_a-zA-Z0-9]*)*"


def render_template(template_text: str, data: Any) -> str:
    """Render a regenerate-class template against new_data. `${dotted.path}` placeholders
    ALWAYS work via stdlib string.Template (no third-party package). If the template text ALSO
    uses native Jinja control syntax ({{ }} / {% %}), jinja2 is imported gracefully to render
    that richer subset; its absence in THAT case is a loud RebindOfficeError, never a silent
    stdlib mis-render of control-flow syntax."""
    needs_jinja = ("{{" in template_text) or ("{%" in template_text)
    if needs_jinja:
        if jinja2 is None:
            raise RebindOfficeError(
                "template uses Jinja control syntax ({{ }} / {% %}) but jinja2 is not installed "
                "— install jinja2, or rewrite the template using only ${dotted.path} placeholders"
            )
        env = jinja2.Environment(autoescape=False, undefined=jinja2.StrictUndefined)
        try:
            return env.from_string(template_text).render(**data)
        except jinja2.exceptions.TemplateError as exc:
            raise RebindOfficeError(f"jinja2 template render failed: {exc}") from exc
    return _DottedTemplate(template_text).safe_substitute(_DotLookup(data))


# ── OOXML text helpers (byte-level; operate on the run/cell w:t region) ────────────────────

# Matches a paired <w:t> open tag (any namespace prefix), NOT <w:tbl>/<w:tc>/<w:tr>/<w:tab>
# (a non-'t' char follows) and NOT a self-closed <w:t/> (a '/' follows, breaking the match).
_WT_OPEN_RE = re.compile(rb"<((?:[A-Za-z_][\w.-]*:)?t)(?:\s[^>]*?)?>")
_EMBED_RE = re.compile(rb'\br:embed="([^"]+)"|\bembed="([^"]+)"')


def _xml_escape_text(text: str) -> bytes:
    """XML-escape a value for insertion as element text (& < >) and encode utf-8."""
    escaped = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return escaped.encode("utf-8")


def _wt_inner_spans(region: bytes) -> list[tuple[int, int]]:
    """Byte spans (inner_start, inner_end) of every paired <w:t>...</w:t> inside `region`
    (already the run/cell inner bytes). Self-closed <w:t/> carry no inner and are excluded."""
    spans: list[tuple[int, int]] = []
    pos = 0
    while True:
        m = _WT_OPEN_RE.search(region, pos)
        if not m:
            break
        qname = m.group(1)
        close = b"</" + qname + b">"
        inner_start = m.end()
        close_idx = region.find(close, inner_start)
        if close_idx == -1:
            break
        spans.append((inner_start, close_idx))
        pos = close_idx + len(close)
    return spans


def _reject_dtd(xml_bytes: bytes) -> None:
    """XXE / billion-laughs defense (stdlib-only floor — defusedxml is deliberately off this
    plugin's dependency path; mirrors infer_office._reject_dtd + the expat-level rejection in
    scripts/rr_anchor.py). A valid OOXML part NEVER carries a DTD, so a DOCTYPE/ENTITY can only
    be a hostile template; reject it before xml.etree ever expands an entity. Treats a hostile
    input as DATA, never instructions (§6)."""
    low = xml_bytes.lower()
    if b"<!doctype" in low or b"<!entity" in low:
        raise RebindOfficeError(
            "DOCTYPE/DTD/ENTITY in an OOXML part is rejected (XXE / entity-expansion defense)"
        )


def _anchor_value(anchor: Any) -> Any:
    return anchor.get("value") if isinstance(anchor, dict) else anchor


def _resolve_node(doc: bytes, anchor: Any):
    """Resolve `anchor` against document.xml `doc` via the SHARED resolver. Raises
    RebindOfficeError (never a bare AnchorError) for an unparseable or absent anchor."""
    try:
        node = rr_anchor.ooxml_try_resolve(doc, anchor)
    except rr_anchor.AnchorError as exc:
        raise RebindOfficeError(f"anchor {_anchor_value(anchor)!r} is unparseable: {exc}") from exc
    if node is None:
        raise RebindOfficeError(f"anchor {_anchor_value(anchor)!r} names no node in {DOCUMENT_PART}")
    return node


def _strip_value(doc: bytes, anchor: Any) -> tuple[bytes, str]:
    """STEP 1 of zero-literal construction: empty EVERY <w:t> under the anchored run/cell so
    that, at the instant this returns, the node carries no old instance value. Returns
    (doc_with_empty_value, old_value_text)."""
    node = _resolve_node(doc, anchor)
    old_value = node.text()
    inner = node.inner_bytes()
    spans = _wt_inner_spans(inner)
    if not spans:
        raise RebindOfficeError(
            f"anchor {_anchor_value(anchor)!r} (<{node.local_name}>) carries no <w:t> value "
            f"region to strip — surgical/regenerate targets must hold a run value"
        )
    new_inner = inner
    for (s, e) in reversed(spans):  # right-to-left so earlier offsets stay valid
        new_inner = new_inner[:s] + new_inner[e:]
    new_doc = doc[: node.inner_start] + new_inner + doc[node.inner_end :]
    return new_doc, old_value


def _write_value(doc: bytes, anchor: Any, new_value: bytes) -> bytes:
    """STEP 2 of zero-literal construction: write `new_value` (already XML-escaped bytes) into
    the FIRST <w:t> of the (now-emptied) anchored node. Re-resolves fresh on the stripped
    bytes so byte offsets are current."""
    node = _resolve_node(doc, anchor)
    inner = node.inner_bytes()
    spans = _wt_inner_spans(inner)
    if not spans:
        raise RebindOfficeError(
            f"anchor {_anchor_value(anchor)!r} lost its <w:t> region between strip and write"
        )
    s, e = spans[0]
    new_inner = inner[:s] + new_value + inner[e:]
    return doc[: node.inner_start] + new_inner + doc[node.inner_end :]


# ── per-class edits ────────────────────────────────────────────────────────────────────────


def apply_surgical(doc: bytes, anchor: Any, resolved: Any) -> tuple[bytes, str]:
    """Zero-literal construction, two-step: STRIP the old value to empty, THEN WRITE the new
    value. Between the two calls the node provably carries no old instance value."""
    value_str = resolved if isinstance(resolved, str) else json.dumps(resolved)
    doc, old_value = _strip_value(doc, anchor)  # STEP 1
    doc = _write_value(doc, anchor, _xml_escape_text(value_str))  # STEP 2
    return doc, old_value


def apply_regenerate_text(
    doc: bytes, anchor: Any, resolved: Any, new_data: Any
) -> tuple[bytes, str, str]:
    """Same zero-literal construction as surgical, but the new run value is RENDERED from a
    template against new-data (stdlib ${dotted.path}; jinja2 optional for control syntax)."""
    if isinstance(resolved, str):
        rendered = render_template(resolved, new_data)
    elif isinstance(resolved, dict) and "template" in resolved:
        rendered = render_template(resolved["template"], new_data)
    elif isinstance(resolved, (int, float, bool)):
        rendered = json.dumps(resolved)
    else:
        raise RebindOfficeError(
            f"regenerate anchor {_anchor_value(anchor)!r} (text) needs a template string or a "
            f'{{"template": "..."}} object from new-data; resolved value was {resolved!r}'
        )
    doc, old_value = _strip_value(doc, anchor)
    doc = _write_value(doc, anchor, _xml_escape_text(rendered))
    return doc, old_value, rendered


def _fresh_media_bytes(resolved: Any) -> bytes:
    """A FRESH raster capture from new-data, base64-decoded. Never a transplant: a regenerate
    raster with no fresh capture is a loud error (a transplanted binary cannot be proven
    data-free — §4/§6.4)."""
    if isinstance(resolved, dict):
        b64 = resolved.get("media_base64") or resolved.get("src_base64")
        if not b64:
            raise RebindOfficeError(
                "regenerate raster asset needs a 'media_base64' fresh-capture field — a "
                "transplanted binary cannot be proven data-free"
            )
    elif isinstance(resolved, str):
        b64 = resolved
    else:
        raise RebindOfficeError(
            "regenerate raster needs a base64 string or a {'media_base64': ...} object from new-data"
        )
    try:
        return base64.b64decode(b64, validate=True)
    except Exception as exc:
        raise RebindOfficeError(f"regenerate raster media is not valid base64: {exc}") from exc


def apply_regenerate_drawing(
    doc: bytes,
    anchor: Any,
    resolved: Any,
    rels_map: dict[str, str],
    media_overrides: dict[str, bytes],
) -> tuple[str, str]:
    """Force-regenerate a raster: find the drawing's r:embed relationship, resolve it to a
    `word/media/*` part, and queue that part for REPLACEMENT with a fresh capture. document.xml
    is not edited (the relationship id is stable); only the binary part is swapped. Returns
    (rId, part_name)."""
    node = _resolve_node(doc, anchor)
    m = _EMBED_RE.search(node.outer_bytes())
    if not m:
        raise RebindOfficeError(
            f"regenerate drawing {_anchor_value(anchor)!r} has no r:embed image reference"
        )
    rid = (m.group(1) or m.group(2)).decode("ascii")
    part = rels_map.get(rid)
    if part is None:
        raise RebindOfficeError(
            f"regenerate drawing {_anchor_value(anchor)!r}: relationship {rid!r} not found in "
            f"{DOCUMENT_RELS_PART}"
        )
    media_overrides[part] = _fresh_media_bytes(resolved)
    return rid, part


def _needs_review_marker(local_name: str, confidence: Any, note: str) -> bytes:
    """A visible OOXML marker (a run, or a paragraph for a cell) carrying a machine-readable
    token. Content of the flagged node itself is never touched."""
    text = (
        f"⚠ NEEDS REVIEW — human sign-off required ({note}, confidence {confidence}) "
        f"{NEEDS_REVIEW_TOKEN}"
    )
    run = b'<w:r><w:t xml:space="preserve">' + _xml_escape_text(text) + b"</w:t></w:r>"
    if local_name == "tc":
        return b"<w:p>" + run + b"</w:p>"
    return run


def flag_needs_review(doc: bytes, anchor: Any, confidence: Any, note: str) -> bytes:
    """Insert a visible needs-review marker adjacent to the anchored node, leaving the node's
    own content byte-for-byte untouched. A run gets a sibling marker run immediately after it;
    a paragraph/cell gets the marker appended as its last child."""
    node = _resolve_node(doc, anchor)
    local = node.local_name
    marker = _needs_review_marker(local, confidence, note)
    if local == "r":
        insert_at = node.outer_end
    elif local in ("p", "tc"):
        insert_at = node.inner_end  # append inside the paragraph/cell
    else:
        raise RebindOfficeError(
            f"needs-review marker is not supported for a <{local}> node "
            f"({_anchor_value(anchor)!r}); expected a run, paragraph, or table cell"
        )
    return doc[:insert_at] + marker + doc[insert_at:]


# ── binding orchestration ──────────────────────────────────────────────────────────────────


def apply_binding(
    doc: bytes,
    binding: dict[str, Any],
    new_data: Any,
    rels_map: dict[str, str],
    media_overrides: dict[str, bytes],
    changes: list[dict[str, Any]],
) -> bytes:
    anchor = binding["anchor"]
    label = _anchor_value(anchor)
    cls = binding["class"]

    if cls == "frozen":
        if rr_anchor.ooxml_try_resolve(doc, anchor) is None:
            raise RebindOfficeError(f"frozen node {label!r} not found in template")
        changes.append(
            {
                "node_id": binding.get("node_id"),
                "anchor": label,
                "class": cls,
                "action": "no-op (frozen — earned, must stay byte-identical)",
            }
        )
        return doc

    if cls == "needs-review":
        confidence = binding.get("confidence")
        doc = flag_needs_review(doc, anchor, confidence, f"confidence {confidence}")
        changes.append(
            {
                "node_id": binding.get("node_id"),
                "anchor": label,
                "class": cls,
                "action": "flagged needs-review (content left untouched, visible marker inserted)",
                "confidence": confidence,
                "marker_token": NEEDS_REVIEW_TOKEN,
            }
        )
        return doc

    data_query = binding.get("data_query")
    if not data_query:
        raise RebindOfficeError(f"node {label!r}: class {cls!r} requires a data_query (schema violation)")
    expr = data_query.get("expression")
    if not expr:
        raise RebindOfficeError(f"node {label!r}: data_query has no expression")
    resolved = lookup_path(new_data, expr)

    if cls == "surgical":
        doc, old_value = apply_surgical(doc, anchor, resolved)
        changes.append(
            {
                "node_id": binding.get("node_id"),
                "anchor": label,
                "class": cls,
                "action": "surgical-rebind (strip-then-write)",
                "old_value": old_value,
                "new_value": resolved,
            }
        )
        return doc

    # regenerate
    node = _resolve_node(doc, anchor)
    if node.local_name == "drawing":
        rid, part = apply_regenerate_drawing(doc, anchor, resolved, rels_map, media_overrides)
        changes.append(
            {
                "node_id": binding.get("node_id"),
                "anchor": label,
                "class": cls,
                "action": "regenerated raster (fresh media part; old binary dropped)",
                "old_value": f"embed={rid}",
                "new_value": {"media_part": part},
            }
        )
        return doc  # document.xml unchanged for a drawing; only the binary part is replaced

    doc, old_value, rendered = apply_regenerate_text(doc, anchor, resolved, new_data)
    changes.append(
        {
            "node_id": binding.get("node_id"),
            "anchor": label,
            "class": cls,
            "action": "regenerated text (strip-then-write)",
            "old_value": old_value,
            "new_value": rendered,
        }
    )
    return doc


def _assert_frozen_unchanged(orig_doc: bytes, final_doc: bytes, bindings: list[dict[str, Any]]) -> None:
    """Post-hoc proof: for every frozen binding, the anchored node's outer OOXML byte span is
    identical between template and output.

    Exception: a frozen node that is a structural ANCESTOR of a licensed-mutable
    (surgical/regenerate/needs-review) binding legitimately changes its OUTER bytes when that
    descendant is rebound/annotated — an OOXML table cell / heading paragraph is frozen *chrome*,
    yet it wraps the value run the manifest addresses. (The HTML lane never hits this because its
    bound value nodes are flat, id-anchored leaves; the OOXML lane nests a value run inside a
    frozen w:tc / styled w:p.) Byte-identity for such a container is neither expected nor the
    guarantee — the frozen-complement guarantee for it is enforced by the harness V2 leg, which
    masks the mutable subtree exactly. This defensive proof therefore checks byte-identity only for
    frozen nodes that contain NO mutable descendant (the genuinely-untouched frozen leaves)."""
    mutable_paths: list = []
    for b in bindings:
        if b["class"] in ("surgical", "regenerate", "needs-review"):
            try:
                mutable_paths.append(rr_anchor.ooxml_document_path(orig_doc, b["anchor"]))
            except rr_anchor.AnchorError:
                pass

    for binding in bindings:
        if binding["class"] != "frozen":
            continue
        anchor = binding["anchor"]
        try:
            fpath = rr_anchor.ooxml_document_path(orig_doc, anchor)
        except rr_anchor.AnchorError:
            fpath = None
        if fpath is not None and any(
            len(fpath) < len(mp) and mp[: len(fpath)] == fpath for mp in mutable_paths
        ):
            continue  # frozen container of a licensed-mutable descendant — V2 owns its proof
        before = rr_anchor.ooxml_try_resolve(orig_doc, anchor)
        after = rr_anchor.ooxml_try_resolve(final_doc, anchor)
        before_bytes = before.outer_bytes() if before else None
        after_bytes = after.outer_bytes() if after else None
        if before_bytes != after_bytes:
            raise RebindOfficeError(
                f"INTERNAL: frozen node {_anchor_value(anchor)!r} changed between template and "
                f"output — the earned-frozen invariant must never be violated"
            )


def _assert_wellformed(doc: bytes) -> None:
    """Smoke-check the rebound document.xml is still well-formed XML (a gross-rebind-bug catch,
    not a substitute for the downstream V1-V6 fidelity harness)."""
    _reject_dtd(doc)
    try:
        ET.fromstring(doc)
    except ET.ParseError as exc:
        raise RebindOfficeError(f"rebound {DOCUMENT_PART} is not well-formed XML: {exc}") from exc


# ── docx (OPC/ZIP) read + re-zip ────────────────────────────────────────────────────────────


def read_part(docx_bytes: bytes, name: str) -> bytes:
    try:
        with zipfile.ZipFile(io.BytesIO(docx_bytes)) as zf:
            try:
                return zf.read(name)
            except KeyError:
                raise RebindOfficeError(f"{name!r} not found in .docx package (not a Word .docx?)")
    except zipfile.BadZipFile as exc:
        raise RebindOfficeError(f"input is not a valid .docx zip: {exc}") from exc


def parse_rels(rels_xml: bytes) -> dict[str, str]:
    """Map each internal relationship Id -> its OPC part name (resolved against `word/`, since
    document.xml.rels lives at word/_rels/). External relationships are skipped."""
    out: dict[str, str] = {}
    if not rels_xml:
        return out
    _reject_dtd(rels_xml)
    try:
        root = ET.fromstring(rels_xml)
    except ET.ParseError:
        return out
    for rel in list(root):
        rid = rel.attrib.get("Id")
        target = rel.attrib.get("Target")
        if not rid or not target:
            continue
        if rel.attrib.get("TargetMode") == "External":
            continue
        if target.startswith("/"):
            part = target.lstrip("/")
        else:
            part = posixpath.normpath("word/" + target)
        out[rid] = part
    return out


def rezip(template_bytes: bytes, new_document_xml: bytes, media_overrides: dict[str, bytes]) -> bytes:
    """Re-emit the .docx: `word/document.xml` becomes the rebound bytes, any regenerated media
    part is swapped, and EVERY other OPC part is copied through with its original ZipInfo so
    untouched parts stay content-identical. Member order is preserved."""
    out_buf = io.BytesIO()
    with zipfile.ZipFile(io.BytesIO(template_bytes)) as src, zipfile.ZipFile(out_buf, "w") as dst:
        for info in src.infolist():
            name = info.filename
            if name == DOCUMENT_PART:
                data = new_document_xml
            elif name in media_overrides:
                data = media_overrides[name]
            else:
                data = src.read(name)
            new_info = zipfile.ZipInfo(filename=name, date_time=info.date_time)
            new_info.compress_type = info.compress_type
            new_info.external_attr = info.external_attr
            new_info.internal_attr = info.internal_attr
            new_info.create_system = info.create_system
            dst.writestr(new_info, data)
    return out_buf.getvalue()


# ── the engine's pure core ──────────────────────────────────────────────────────────────────


def rebind(template_docx_bytes: bytes, manifest: dict[str, Any], new_data: Any) -> tuple[bytes, list[dict[str, Any]], int]:
    """Apply every binding to a COPY of the template docx and return
    (output_docx_bytes, changes, needs_review_count). The input bytes are never mutated."""
    document_xml = read_part(template_docx_bytes, DOCUMENT_PART)
    original_document_xml = document_xml
    try:
        rels_xml = read_part(template_docx_bytes, DOCUMENT_RELS_PART)
    except RebindOfficeError:
        rels_xml = b""  # a docx with no images has no document rels part — that's fine
    rels_map = parse_rels(rels_xml)

    bindings = manifest["bindings"]

    # Reverse document order (RT1-F10): resolve each anchor once on the ORIGINAL bytes to get
    # its true document position, then apply from the end backward, re-resolving fresh so an
    # earlier edit's byte/index shift can never invalidate a not-yet-applied anchor.
    ordered: list[tuple[int, dict[str, Any]]] = []
    for binding in bindings:
        node = _resolve_node(original_document_xml, binding["anchor"])
        ordered.append((node.open_start, binding))
    ordered.sort(key=lambda t: t[0], reverse=True)

    media_overrides: dict[str, bytes] = {}
    changes: list[dict[str, Any]] = []
    needs_review_count = 0
    for _offset, binding in ordered:
        document_xml = apply_binding(document_xml, binding, new_data, rels_map, media_overrides, changes)
        if binding["class"] == "needs-review":
            needs_review_count += 1

    _assert_frozen_unchanged(original_document_xml, document_xml, bindings)
    _assert_wellformed(document_xml)
    changes.reverse()  # present the change log in document order

    output_docx = rezip(template_docx_bytes, document_xml, media_overrides)
    return output_docx, changes, needs_review_count


# ── manifest loading (pragmatic subset of binding-manifest.schema.json — the fields this ──
# ── engine consumes; mirrors rebind_html.load_manifest, format "office") ──


def load_manifest(path: Path) -> dict[str, Any]:
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RebindOfficeError(f"manifest is not valid JSON: {exc}") from exc

    for key in ("manifest_version", "rsg_schema_version", "template_id", "format", "bindings"):
        if key not in manifest:
            raise RebindOfficeError(f"manifest missing required field {key!r} (binding-manifest.schema.json)")
    if manifest["format"] != "office":
        raise RebindOfficeError(
            f"manifest format is {manifest['format']!r}; rebind-office only applies 'office' manifests"
        )
    if not isinstance(manifest["bindings"], list):
        raise RebindOfficeError("manifest 'bindings' must be an array")

    for binding in manifest["bindings"]:
        for key in ("node_id", "anchor", "class", "confidence", "provenance", "data_query"):
            if key not in binding:
                raise RebindOfficeError(
                    f"binding {binding.get('node_id', '?')!r} missing required field {key!r}"
                )
        if binding["class"] not in VALID_CLASSES:
            raise RebindOfficeError(f"binding {binding['node_id']!r} has unknown class {binding['class']!r}")
        anchor = binding["anchor"]
        if not isinstance(anchor, dict) or "kind" not in anchor or "value" not in anchor:
            raise RebindOfficeError(f"binding {binding['node_id']!r} has a malformed anchor (needs kind+value)")
        if anchor["kind"] != "ooxml_path":
            raise RebindOfficeError(
                f"binding {binding['node_id']!r} has anchor kind {anchor['kind']!r}; rebind-office "
                f"resolves only 'ooxml_path' anchors (HTML anchors are a different lane)"
            )
        if binding["class"] == "frozen" and binding["data_query"] is not None:
            raise RebindOfficeError(
                f"binding {binding['node_id']!r} is class 'frozen' but carries a data_query "
                f"(schema violation — frozen carries none)"
            )
        if binding["class"] != "frozen" and binding["data_query"] is None:
            raise RebindOfficeError(
                f"binding {binding['node_id']!r} is class {binding['class']!r} but carries no "
                f"data_query (schema violation)"
            )

    return manifest


# ── CLI ──────────────────────────────────────────────────────────────────────────────────────


def _emit_error(message: str) -> None:
    print(json.dumps({"schema": SCHEMA, "ok": False, "error": message}), file=sys.stdout)
    print(f"[error] {message}", file=sys.stderr)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="rebind_office.py",
        description="Apply a Binding Manifest to a COPY of a Word (.docx) template and emit the "
        "regenerated .docx (report-regeneration pipeline stage 3, Office lane).",
    )
    p.add_argument("--template", required=True, metavar="PATH", help="template .docx, relative path")
    p.add_argument("--manifest", required=True, metavar="PATH", help="binding manifest JSON, relative path")
    p.add_argument("--new-data", required=True, dest="new_data", metavar="PATH", help="resolved new-source data JSON, relative path")
    p.add_argument("--out", required=True, metavar="PATH", help="output .docx path, relative path")
    p.add_argument("--pretty", action="store_true", help="pretty-print the JSON change-manifest")
    return p


def main(argv: list[str]) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        template_path = _guard_path(args.template, must_exist=True)
        manifest_path = _guard_path(args.manifest, must_exist=True)
        data_path = _guard_path(args.new_data, must_exist=True)
        out_path = _guard_path(args.out, must_exist=False)
        if out_path == template_path:
            raise RebindOfficeError(
                "--out must not be the same path as --template — rebind-office works on a COPY; "
                "the template is never mutated"
            )
    except RebindOfficeError as exc:
        _emit_error(str(exc))
        return 2

    try:
        template_docx = template_path.read_bytes()
        manifest = load_manifest(manifest_path)
        new_data = json.loads(data_path.read_text(encoding="utf-8"))
    except (RebindOfficeError, json.JSONDecodeError, OSError) as exc:
        _emit_error(str(exc))
        return 2

    try:
        output_docx, changes, needs_review_count = rebind(template_docx, manifest, new_data)
    except RebindOfficeError as exc:
        _emit_error(str(exc))
        return 2

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(output_docx)

    payload = {
        "schema": SCHEMA,
        "ok": True,
        "template": args.template,
        "manifest": args.manifest,
        "new_data": args.new_data,
        "output": args.out,
        "template_id": manifest["template_id"],
        "manifest_version": manifest["manifest_version"],
        "binding_count": len(manifest["bindings"]),
        "needs_review_count": needs_review_count,
        "accelerator": _ACCEL or "stdlib(zipfile+xml.etree)",
        "jinja2_available": jinja2 is not None,
        "changes": changes,
    }
    print(json.dumps(payload, indent=2 if args.pretty else None))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
