import ast
import base64
import contextlib
import copy
import hashlib
import io
import json
import os
import posixpath
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from collections import Counter
from html.parser import HTMLParser
from pathlib import Path
from unittest import mock
from urllib.parse import unquote

os.environ["ATLAS_TEST_ALLOW_ANY_TREE"] = "1"
TOOLS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(TOOLS))

import render  # noqa: E402
from atlas_common import DATA_DIR, dump_json, load_json  # noqa: E402

RENDER_PY = TOOLS / "render.py"
MARKER = "<!-- Generated by _tools/render.py from data/. Do not edit by hand. -->"
XSS = "<script>alert(1)</script>"
XSS_ESCAPED = "&lt;script&gt;alert(1)&lt;/script&gt;"
SHA = "a" * 64
LONG_VALUE = "".join(chr(ord("a") + i % 26) for i in range(100))
SURFACES = load_json(DATA_DIR / "surfaces.json")["surfaces"]
SURFACE_IDS = [s["id"] for s in SURFACES]
PRODUCTS = [
    "claude-code",
    "codex-cli",
    "copilot",
    "cursor",
    "gemini-cli",
    "grok-build",
    "grok-bot",
]
EXPECTED_PAGES = (
    ["index.html", "matrix.html", "levers.html", "register.html", "method.html"]
    + [f"harness/{p}.html" for p in PRODUCTS]
    + [f"sources/{s}.html" for s in SURFACE_IDS]
)
ALLOWED_HOSTS = {h for s in SURFACES for h in s["docs_hosts"]} | {"github.com"}
BASE_CSP = (
    "default-src 'none'; style-src 'unsafe-inline'; img-src data:; "
    "base-uri 'none'; form-action 'none'"
)


def cell(surface, row, state, verification="verified", **extra):
    record = {
        "id": f"{surface}/{row}",
        "surface": surface,
        "row": row,
        "state": state,
        "verification": verification,
        "evidence": [],
    }
    record.update(extra)
    return record


def evidence(surface, number, **extra):
    record = {
        "id": f"E-{surface}-{number:05d}",
        "surface": surface,
        "tier": "E1",
        "url": "https://code.claude.com/docs/en/permissions",
        "retrieved": "2026-09-01",
        "sha256": SHA,
        "product_version": "2.0.1",
        "locator": {"heading": "Modes", "raw_line_start": 3, "raw_line_end": 5},
        "quote": "Plain quote",
        "context_before": [],
        "context_after": [],
        "quote_verified": True,
    }
    record.update(extra)
    return record


def lever(surface, kind, row, **extra):
    record = {
        "surface": surface,
        "lever": kind,
        "row": row,
        "model": None,
        "location_kind": "cli_flag",
        "state": "supported",
        "verification": "verified",
        "evidence": [],
    }
    record.update(extra)
    return record


def task(surface, pointer, basis="capability-fact", pending=None, settings=()):
    return {
        "surface": surface,
        "task_class": f"task for {surface}",
        "pointer": pointer,
        "basis": basis,
        "pending_label": pending,
        "lever_settings": list(settings),
    }


POINTER = {"file": "plugins/x/agent-routing-matrix.json", "path": "$.rows[3]"}


def fixture():
    cc, cx = "claude-code", "codex-cli"
    cells = {
        cc: [
            cell(
                cc,
                "F04.approval-modes",
                "supported",
                value=LONG_VALUE,
                evidence=[f"E-{cc}-00001", f"E-{cc}-00002"],
            ),
            cell(
                cc,
                "F04.per-tool-rules",
                "partial",
                value=f"per tool {XSS}",
                limitation=f"Only {XSS} in settings",
                evidence=[f"E-{cc}-00001"],
            ),
            cell(cc, "F04.path-scoping", "not-exposed", vendor_statement=f"E-{cc}-00002"),
            cell(cc, "F04.command-scoping", "not-applicable", na_quote=f"E-{cc}-00001"),
            cell(
                cc,
                "F04.trust-prompt",
                "undocumented",
                sweep_report={
                    "terms": ["trust"],
                    "corpus_sha256": SHA,
                    "hits": 0,
                    "hits_reviewed": 0,
                    "positive_control_term": "permission",
                    "positive_control_hits": 4,
                },
            ),
            cell(cc, "F04.bypass-mode", "not-researched", "unverified"),
            cell(
                cc,
                "F04.auto-review",
                "supported",
                "unverified",
                value="auto",
                marker="single secondary source",
                settles_by="fetch the changelog",
            ),
            cell(cc, "F17.model-picker", "supported", "unverified", value="picker"),
            cell(cc, "F21.host-platform", "supported", value="standalone"),
            cell(cc, "U00", "supported", value="Unmapped feature", evidence=[f"E-{cc}-00001"]),
        ],
        cx: [
            cell(
                cx,
                "F04.approval-modes",
                "supported",
                value="ask or never",
                evidence=[f"E-{cx}-00001"],
            )
        ],
        "copilot-vscode": [
            cell("copilot-vscode", "F04.approval-modes", "partial", limitation="IDE only")
        ],
    }
    cells[cc][-1]["id"] = f"{cc}/U00/1"
    return {
        "cells": cells,
        "evidence": {
            cc: [
                evidence(cc, 1, quote=f"Plain {XSS} quote"),
                evidence(
                    cc,
                    2,
                    tier="E2",
                    url="https://evil.example.com/page",
                    retrieved="2026-06-01",
                    product_version=None,
                    quote="",
                    described_span={
                        "description": "an install command line",
                        "raw_line_start": 9,
                        "raw_line_end": 9,
                        "span_sha256": SHA,
                    },
                ),
                evidence(cc, 3, url="http://code.claude.com/insecure"),
            ],
            cx: [evidence(cx, 1, url="https://developers.openai.com/codex/security")],
        },
        "levers": {
            "levers": [
                lever(
                    cc,
                    "mode",
                    "F19.named-modes",
                    literal="--permission-mode",
                    scope="session",
                    values=["default", "plan"],
                    default="default",
                    evidence=[f"E-{cc}-00001"],
                ),
                lever(
                    cx,
                    "effort",
                    "F18.effort-values",
                    model="gpt-x",
                    location_kind="config_file_key",
                    literal="model_reasoning_effort",
                    values=["low", "high"],
                    state="partial",
                    verification="unverified",
                    unread_models=["gpt-y"],
                ),
            ],
            "task_shape_rows": [
                task(cc, POINTER, "capability-fact", None, [f"{cc}|mode|"]),
                task("cursor", None, "editorial-judgment", f"pending {XSS}"),
            ],
        },
        "register": {
            "entries": [
                {
                    "id": "ENH-002",
                    "title": "Second by rank",
                    "type": "extend",
                    "surfaces": [cc],
                    "cells": [],
                    "rank": 2,
                    "score": 4,
                    "status": "proposed",
                },
                {
                    "id": "ENH-001",
                    "title": f"Fix {XSS} docs",
                    "type": "correct",
                    "surfaces": [cc, "not-a-surface"],
                    "cells": [f"{cc}/F04.approval-modes", f"{cc}/U00/1", "nowhere/F04.x"],
                    "repo_files": [
                        {"path": "docs/a.md", "exists": True},
                        {"path": "docs/missing.md", "exists": False},
                    ],
                    "proposal": "Change the thing",
                    "basis": {"kind": "inference", "falsified_by": "read the page"},
                    "rank": 1,
                    "score": 7.5,
                    "rationale": f"editorial-judgment {XSS}",
                    "status": "proposed",
                },
            ]
        },
        "snapshot": {
            "freeze_start": "2026-10-01",
            "freeze_end": "2026-10-04",
            "columns": [
                {
                    "surface": cc,
                    "retrieved": "2026-10-04",
                    "version": "2.0.1",
                    "version_source": "npm",
                },
                {"surface": cx, "retrieved": "2026-10-03", "version": None, "version_source": None},
            ],
            "index_hashes": {},
            "matrix_sha": "b" * 40,
            "known_gaps": [f"gap one {XSS}"],
            "verification": {"quotes_checked": 12, XSS: "x"},
            "coverage": {cc: {"pages": 120}},
        },
    }


def write_data(root, data, raw=None):
    """Write ``data`` (see fixture()) under ``root``/data with the real facets and surfaces."""
    base = Path(root) / "data"
    base.mkdir(parents=True, exist_ok=True)
    for name in ("facets.json", "surfaces.json"):
        shutil.copy(DATA_DIR / name, base / name)
    for sid, items in data.get("cells", {}).items():
        dump_json(base / "cells" / f"{sid}.json", {"surface": sid, "cells": items})
    for sid, items in data.get("evidence", {}).items():
        dump_json(base / "evidence" / f"{sid}.json", {"surface": sid, "evidence": items})
    for name in ("levers", "register", "snapshot"):
        if name in data:
            dump_json(base / f"{name}.json", data[name])
    for name, text in (raw or {}).items():
        (base / name).parent.mkdir(parents=True, exist_ok=True)
        (base / name).write_text(text, encoding="ascii")
    return base


class Scan(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.tags = Counter()
        self.ids = []
        self.links = []
        self.attr_names = set()
        self.scripts = []
        self.csp = None
        self.lang = None
        self.table_captions = []
        self._in_script = False
        self._tables = []

    def handle_starttag(self, tag, attrs):
        attributes = dict(attrs)
        self.tags[tag] += 1
        self.attr_names.update(name for name, _ in attrs)
        if "id" in attributes:
            self.ids.append(attributes["id"])
        for name in ("href", "src"):
            if name in attributes:
                self.links.append((name, attributes[name]))
        if tag == "html":
            self.lang = attributes.get("lang")
        if tag == "meta" and attributes.get("http-equiv") == "Content-Security-Policy":
            self.csp = attributes.get("content")
        if tag == "script":
            self._in_script = True
            self.scripts.append("")
        if tag == "table":
            self._tables.append(False)
        if tag == "caption" and self._tables:
            self._tables[-1] = True

    def handle_endtag(self, tag):
        if tag == "script":
            self._in_script = False
        if tag == "table":
            self.table_captions.append(self._tables.pop())

    def handle_data(self, data):
        if self._in_script:
            self.scripts[-1] += data


def scan(text):
    parser = Scan()
    parser.feed(text)
    parser.close()
    return parser


def render_pages(data_dir):
    return render.render_all(data_dir)


def read_tree(root):
    root = Path(root)
    return {
        p.relative_to(root).as_posix(): p.read_bytes()
        for p in sorted(root.rglob("*"))
        if p.is_file()
    }


def run_cli(args, env=None):
    environment = dict(os.environ)
    environment["ATLAS_TEST_ALLOW_ANY_TREE"] = "1"
    environment.update(env or {})
    return subprocess.run(
        [sys.executable, str(RENDER_PY), *args],
        capture_output=True,
        text=True,
        env=environment,
        check=False,
    )


def run_main(args):
    out, err = io.StringIO(), io.StringIO()
    with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
        code = render.main(args)
    return code, out.getvalue(), err.getvalue()


class RenderTestCase(unittest.TestCase):
    """Base: a temporary root, a fixture data dir under it, and the rendered pages."""

    data = None

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name)
        self.data_dir = write_data(self.root, copy.deepcopy(self.data or fixture()))
        self.out_dir = self.root / "out"

    def pages(self):
        return render_pages(self.data_dir)

    def cell_block(self, page_text, cell_id):
        start = page_text.index(f'id="{cell_id}"')
        return page_text[start : page_text.index("</div>", start)]


class PageSetTests(RenderTestCase):
    def test_every_page_named_in_the_table_is_written(self):
        code, _, err = run_main(["--data-dir", str(self.data_dir), "--out", str(self.out_dir)])
        self.assertEqual(code, 0, err)
        self.assertEqual(sorted(read_tree(self.out_dir)), sorted(EXPECTED_PAGES))

    def test_seven_harness_pages_and_eight_source_pages(self):
        pages = self.pages()
        self.assertEqual(
            sorted(p for p in pages if p.startswith("harness/")),
            sorted(f"harness/{p}.html" for p in PRODUCTS),
        )
        self.assertEqual(len(PRODUCTS), 7)
        self.assertEqual(
            sorted(p for p in pages if p.startswith("sources/")),
            sorted(f"sources/{s}.html" for s in SURFACE_IDS),
        )
        self.assertEqual(len(SURFACE_IDS), 8)

    def test_every_page_is_reachable_from_the_index(self):
        pages = self.pages()
        seen, queue = {"index.html"}, ["index.html"]
        while queue:
            page = queue.pop()
            for _, link in scan(pages[page]).links:
                if "://" in link:
                    continue
                target = posixpath.normpath(
                    posixpath.join(posixpath.dirname(page), link.split("#")[0])
                )
                if link.split("#")[0] and target in pages and target not in seen:
                    seen.add(target)
                    queue.append(target)
        self.assertEqual(sorted(seen), sorted(pages))

    def test_defaults_render_the_real_data_directory(self):
        code, _, err = run_main(["--out", str(self.out_dir)])
        self.assertEqual(code, 0, err)
        self.assertEqual(sorted(read_tree(self.out_dir)), sorted(EXPECTED_PAGES))

    def test_a_nearly_empty_data_directory_renders_with_no_data_cells(self):
        empty = write_data(self.root / "empty", {})
        pages = render_pages(empty)
        self.assertEqual(sorted(pages), sorted(EXPECTED_PAGES))
        self.assertIn("no data", pages["matrix.html"])
        self.assertIn("no data", pages["harness/cursor.html"])
        self.assertIn("no data", pages["sources/cursor.html"])
        self.assertIn("no data", pages["register.html"])
        self.assertIn("0 of 8 (flagged: matrix rows pending for claude-code,", pages["index.html"])

    def test_missing_required_file_and_malformed_json_exit_nonzero_naming_the_file(self):
        (self.data_dir / "surfaces.json").unlink()
        code, _, err = run_main(["--data-dir", str(self.data_dir), "--out", str(self.out_dir)])
        self.assertEqual(code, 2)
        self.assertIn("surfaces.json", err)
        shutil.copy(DATA_DIR / "surfaces.json", self.data_dir / "surfaces.json")
        (self.data_dir / "register.json").write_text("{not json", encoding="utf-8")
        code, _, err = run_main(["--data-dir", str(self.data_dir), "--out", str(self.out_dir)])
        self.assertEqual(code, 2)
        self.assertIn("register.json", err)

    def test_an_unknown_state_is_an_error_not_a_silent_default(self):
        data = fixture()
        data["cells"]["claude-code"][0]["state"] = "mostly"
        broken = write_data(self.root / "broken", data)
        code, _, err = run_main(["--data-dir", str(broken), "--out", str(self.out_dir)])
        self.assertEqual(code, 2)
        self.assertIn("mostly", err)


class DeterminismTests(RenderTestCase):
    def test_output_is_byte_identical_across_runs_timezones_locales_and_hash_seeds(self):
        variants = [
            {},
            {},
            {"TZ": "UTC"},
            {"TZ": "America/New_York"},
            {"LC_ALL": "C"},
            {"LC_ALL": "en_US.UTF-8"},
            {"PYTHONHASHSEED": "0"},
            {"PYTHONHASHSEED": "4242"},
        ]
        trees = []
        for number, env in enumerate(variants):
            out = self.root / f"run{number}"
            result = run_cli(["--data-dir", str(self.data_dir), "--out", str(out)], env)
            self.assertEqual(result.returncode, 0, f"{env}: {result.stderr}")
            trees.append(read_tree(out))
        self.assertEqual(sorted(trees[0]), sorted(EXPECTED_PAGES))
        for number, tree in enumerate(trees[1:], start=1):
            self.assertEqual(tree, trees[0], f"variant {variants[number]} differs")

    def test_encoding_and_line_endings(self):
        for path, text in self.pages().items():
            data = text.encode("utf-8")
            self.assertFalse(data.startswith(b"\xef\xbb\xbf"), path)
            self.assertNotIn(b"\r", data, path)
            self.assertTrue(data.endswith(b"\n"), path)
            self.assertFalse(data.endswith(b"\n\n"), path)
            data.decode("utf-8")

    def test_the_module_imports_nothing_that_reads_the_clock_or_the_environment(self):
        tree = ast.parse(RENDER_PY.read_text(encoding="utf-8"))
        imported = set()
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(a.name.split(".")[0] for a in node.names)
            elif isinstance(node, ast.ImportFrom):
                imported.add((node.module or "").split(".")[0])
        for banned in ("time", "datetime", "locale", "random", "uuid", "secrets", "os", "tempfile"):
            self.assertNotIn(banned, imported)
        self.assertEqual(
            imported,
            {
                "argparse",
                "base64",
                "html",
                "posixpath",
                "re",
                "sys",
                "pathlib",
                "urllib",
                "atlas_common",
            },
        )


class EscapingTests(RenderTestCase):
    def test_planted_script_is_escaped_in_every_data_field(self):
        pages = self.pages()
        harness = pages["harness/claude-code.html"]
        self.assertIn(f"Plain {XSS_ESCAPED} quote", harness)
        self.assertIn(f"per tool {XSS_ESCAPED}", harness)
        self.assertIn(f"Only {XSS_ESCAPED} in settings", harness)
        self.assertIn(f"Fix {XSS_ESCAPED} docs", pages["register.html"])
        self.assertIn(f"editorial-judgment {XSS_ESCAPED}", pages["register.html"])
        self.assertIn(f"pending {XSS_ESCAPED}", pages["levers.html"])
        self.assertIn(f"gap one {XSS_ESCAPED}", pages["index.html"])
        self.assertIn(f"gap one {XSS_ESCAPED}", pages["method.html"])
        self.assertIn(f'<th scope="row">{XSS_ESCAPED}</th>', pages["method.html"])
        self.assertIn(f"Plain {XSS_ESCAPED} quote", pages["sources/claude-code.html"])

    def test_no_page_carries_a_live_script_or_event_handler(self):
        for path, text in self.pages().items():
            self.assertNotIn("<script>alert(1)", text, path)
            parsed = scan(text)
            for body in parsed.scripts:
                self.assertEqual(body, render.AGE_SCRIPT, path)
            self.assertFalse([a for a in parsed.attr_names if a.startswith("on")], path)
            self.assertEqual(parsed.tags["script"], len(parsed.scripts), path)

    def test_a_value_cannot_break_out_of_the_title_attribute(self):
        data = fixture()
        data["cells"]["claude-code"][0]["value"] = 'x" onmouseover="alert(1)" data-x="'
        pages = render_pages(write_data(self.root / "attr", data))
        parsed = scan(pages["matrix.html"])
        self.assertNotIn("onmouseover", parsed.attr_names)
        self.assertIn(
            'title="x&quot; onmouseover=&quot;alert(1)&quot; data-x=&quot;"', pages["matrix.html"]
        )

    def test_lone_surrogates_controls_and_bidi_overrides_never_crash_or_survive(self):
        data = fixture()
        data["cells"]["claude-code"][0]["value"] = "lone \ud800 nul \x00 rlo ‮ bell \x07 tab\there"
        base = write_data(self.root / "odd", {k: v for k, v in data.items() if k != "cells"})
        cells = data["cells"]["claude-code"]
        (base / "cells").mkdir()
        text = json.dumps(
            {"surface": "claude-code", "cells": cells}
        )  # ASCII: \ud800 stays an escape
        (base / "cells" / "claude-code.json").write_text(text, encoding="ascii")
        pages = render_pages(base)
        raw = {path: page.encode("utf-8") for path, page in pages.items()}
        harness = pages["harness/claude-code.html"]
        self.assertIn("lone � nul � rlo � bell � tab\there", harness)
        for path, data_bytes in raw.items():
            self.assertNotIn("‮".encode(), data_bytes, path)
            self.assertNotIn(b"\x00", data_bytes, path)

    def test_embedded_newlines_and_carriage_returns_normalise_to_lf(self):
        data = fixture()
        data["cells"]["claude-code"][0]["value"] = "one\r\ntwo\rthree"
        pages = render_pages(write_data(self.root / "nl", data))
        self.assertIn('title="one\ntwo\nthree"', pages["matrix.html"])
        self.assertNotIn("\r", pages["matrix.html"])


class SelfContainedTests(RenderTestCase):
    def test_no_remote_fetch_of_any_kind(self):
        for path, text in self.pages().items():
            parsed = scan(text)
            self.assertNotIn("src", [name for name, _ in parsed.links], path)
            for banned in (
                "@import",
                "url(",
                "<link",
                "<img",
                "<iframe",
                "<object",
                "<embed",
                "<form",
            ):
                self.assertNotIn(banned, text, f"{path}: {banned}")
            self.assertNotIn("@font-face", text, path)
            self.assertNotIn("fonts.googleapis", text, path)

    def test_csp_meta_on_every_page_matches_the_inline_script_hash(self):
        with_script = 0
        for path, text in self.pages().items():
            parsed = scan(text)
            self.assertIsNotNone(parsed.csp, path)
            if parsed.scripts:
                with_script += 1
                digest = base64.b64encode(hashlib.sha256(parsed.scripts[0].encode()).digest())
                self.assertEqual(
                    parsed.csp,
                    "default-src 'none'; style-src 'unsafe-inline'; "
                    f"script-src 'sha256-{digest.decode()}'; img-src data:; "
                    "base-uri 'none'; form-action 'none'",
                    path,
                )
            else:
                self.assertEqual(parsed.csp, BASE_CSP, path)
                self.assertNotIn("script-src", parsed.csp)
        self.assertGreater(with_script, 0)

    def test_script_is_present_exactly_when_the_page_has_dates(self):
        for path, text in self.pages().items():
            self.assertEqual("<time " in text, "<script>" in text, path)
        pages = self.pages()
        self.assertIn("<script>", pages["harness/claude-code.html"])
        self.assertNotIn("<script>", pages["matrix.html"])

    def test_the_script_only_adds_an_age_label(self):
        script = render.AGE_SCRIPT
        for word in ("fresh", "ageing", "stale", "30", "90"):
            self.assertIn(word, script)
        for banned in ("fetch(", "XMLHttpRequest", "innerHTML", "eval(", "document.write", "src"):
            self.assertNotIn(banned, script)

    def test_every_page_reads_without_javascript(self):
        # the dates are in the static markup, and the matrix is a plain table
        pages = self.pages()
        self.assertIn('<time datetime="2026-10-04">2026-10-04</time>', pages["index.html"])
        self.assertEqual(
            pages["matrix.html"].count("<tr id="), len(set(render.Atlas(self.data_dir).row_ids))
        )

    def test_css_is_small(self):
        self.assertLess(len(render.CSS.encode("utf-8")), 6 * 1024)


class LinkTests(RenderTestCase):
    def test_every_link_is_relative_an_anchor_or_an_allowed_host(self):
        pages = self.pages()
        ids = {path: set(scan(text).ids) for path, text in pages.items()}
        checked = 0
        for path, text in pages.items():
            for name, link in scan(text).links:
                checked += 1
                self.assertEqual(name, "href", path)
                if link.startswith("#"):
                    self.assertIn(unquote(link[1:]), ids[path], f"{path}: {link}")
                elif "://" in link:
                    self.assertTrue(link.startswith("https://"), f"{path}: {link}")
                    host = link[len("https://") :].split("/")[0]
                    self.assertIn(host, ALLOWED_HOSTS, f"{path}: {link}")
                else:
                    target_path, _, fragment = link.partition("#")
                    target = posixpath.normpath(
                        posixpath.join(posixpath.dirname(path), target_path)
                    )
                    self.assertIn(target, pages, f"{path}: {link}")
                    if fragment:
                        self.assertIn(unquote(fragment), ids[target], f"{path}: {link}")
        self.assertGreater(checked, 500)

    def test_a_url_on_another_host_or_scheme_is_plain_text_not_a_link(self):
        pages = self.pages()
        for page in ("sources/claude-code.html", "harness/claude-code.html"):
            links = [link for _, link in scan(pages[page]).links]
            self.assertFalse([k for k in links if "evil.example.com" in k], page)
            self.assertFalse([k for k in links if k.startswith("http://")], page)
        self.assertIn(
            '<span class="mono">https://evil.example.com/page</span>',
            pages["sources/claude-code.html"],
        )
        self.assertIn(
            '<span class="mono">http://code.claude.com/insecure</span>',
            pages["sources/claude-code.html"],
        )
        self.assertIn(
            '<a href="https://code.claude.com/docs/en/permissions">',
            pages["sources/claude-code.html"],
        )

    def test_safe_external_accepts_only_exact_https_hosts(self):
        hosts = ("code.claude.com", "github.com")
        accepted = [
            "https://code.claude.com/docs/en/x",
            "https://github.com/a/b#frag",
            "https://CODE.claude.com/x",
        ]
        rejected = [
            "http://code.claude.com/x",
            "https://code.claude.com.evil.example.com/x",
            "https://evil.example.com/https://code.claude.com/",
            "https://code.claude.com@evil.example.com/x",
            "https://evil.example.com\\@code.claude.com/",
            "https://code.claude.com:8443/x",
            "https://www.github.com/x",
            "https://code.claude.com/a b",
            "https://code.claude.com/\n",
            "javascript:alert(1)",
            "//code.claude.com/x",
            "/docs/x",
            "",
            None,
        ]
        for url in accepted:
            self.assertTrue(render.safe_external(url, hosts), url)
        for url in rejected:
            self.assertFalse(render.safe_external(url, hosts), repr(url))

    def test_repo_files_link_to_github_only_when_they_exist(self):
        register = self.pages()["register.html"]
        self.assertIn(
            'href="https://github.com/mcorbett51090/RavenClaude/blob/main/docs/a.md"', register
        )
        self.assertNotIn('docs/missing.md"', register.replace("<code>docs/missing.md</code>", ""))
        self.assertIn("<code>docs/missing.md</code>", register)

    def test_href_and_rel_compute_paths_between_pages(self):
        self.assertEqual(render.rel("index.html", "harness/x.html"), "harness/x.html")
        self.assertEqual(render.rel("harness/x.html", "index.html"), "../index.html")
        self.assertEqual(render.rel("harness/x.html", "sources/y.html"), "../sources/y.html")
        self.assertEqual(render.href("a.html", "a.html", "F1.x"), "#F1.x")
        self.assertEqual(render.href("a/b.html", "c.html", "x/y"), "../c.html#x/y")


class SizeTests(RenderTestCase):
    def test_real_limits_hold_for_the_fixture(self):
        encoded = render.encode_pages(self.pages())
        self.assertLessEqual(max(len(d) for d in encoded.values()), 1_500_000)
        self.assertLessEqual(sum(len(d) for d in encoded.values()), 12_000_000)
        self.assertEqual((render.MAX_PAGE_BYTES, render.MAX_TOTAL_BYTES), (1_500_000, 12_000_000))

    def test_an_oversize_page_fails_naming_each_offender_and_writes_nothing(self):
        with mock.patch.object(render, "MAX_PAGE_BYTES", 100_000):
            code, _, err = run_main(["--data-dir", str(self.data_dir), "--out", str(self.out_dir)])
        self.assertEqual(code, 2)
        self.assertIn("page matrix.html is", err)
        self.assertNotIn("page index.html is", err)
        self.assertFalse(self.out_dir.exists())

    def test_the_total_limit_fails_too(self):
        with mock.patch.object(render, "MAX_TOTAL_BYTES", 10_000):
            code, _, err = run_main(["--data-dir", str(self.data_dir), "--out", str(self.out_dir)])
        self.assertEqual(code, 2)
        self.assertIn("all pages together", err)


class AccessibilityTests(RenderTestCase):
    def test_structure_of_every_page(self):
        for path, text in self.pages().items():
            parsed = scan(text)
            self.assertEqual(parsed.lang, "en", path)
            self.assertEqual(parsed.tags["h1"], 1, path)
            self.assertIn('<a class="skip" href="#main">', text, path)
            self.assertIn('<main id="main">', text, path)
            self.assertTrue(all(parsed.table_captions), path)
            self.assertEqual(len(parsed.table_captions), parsed.tags["table"], path)
            for tag in re.findall(r"<th\b[^>]*>", text):
                self.assertRegex(tag, r'scope="(col|row)"', path)
            self.assertEqual(
                len(re.findall(r"<table\b", text)),
                len(
                    re.findall(r'<div class="scroll" tabindex="0" role="region" aria-label="', text)
                ),
                path,
            )

    def test_every_glyph_carries_an_aria_label_with_the_word(self):
        pages = self.pages()
        for _, glyph, word, _ in render.STATES:
            self.assertIn(f'role="img" aria-label="{word}">{glyph}</span>', pages["matrix.html"])
        for text in pages.values():
            for tag in re.findall(r'<span class="g"[^>]*>', text):
                self.assertIn("aria-label=", tag)

    def test_css_has_scroll_regions_reduced_motion_and_both_themes(self):
        css = render.CSS
        self.assertIn("overflow-x:auto", css)
        self.assertIn("@media (prefers-reduced-motion: reduce)", css)
        self.assertRegex(css, r"@media \(prefers-reduced-motion: reduce\)\{[^}]*transition:none")
        self.assertIn("@media (prefers-color-scheme: dark)", css)
        self.assertIn("system-ui", css)
        self.assertIn("max-width:1100px", css)
        self.assertIn("padding:0 var(--s4)", css)
        self.assertIn("--s1:4px", css)

    def test_contrast_is_at_least_aa_in_both_themes(self):
        def variables(block):
            return dict(re.findall(r"(--[a-z0-9-]+):(#[0-9a-f]{6})", block))

        def luminance(colour):
            channels = [int(colour[i : i + 2], 16) / 255 for i in (1, 3, 5)]
            lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
            return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]

        def ratio(a, b):
            hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
            return (hi + 0.05) / (lo + 0.05)

        light_block = re.match(r"\s*:root\{([^}]*)\}", render.CSS).group(1)
        dark_block = re.search(
            r"@media \(prefers-color-scheme: dark\)\{:root\{([^}]*)\}", render.CSS
        ).group(1)
        light = variables(light_block)
        dark = dict(light, **variables(dark_block))
        self.assertNotEqual(light["--bg"], dark["--bg"])
        for theme in (light, dark):
            tints = [k for k in theme if k.startswith("--t-")]
            self.assertEqual(len(tints), 7)
            backgrounds = ["--bg", "--surface", *tints]
            for fg in ("--text", "--muted", "--accent"):
                for bg in backgrounds:
                    self.assertGreaterEqual(ratio(theme[fg], theme[bg]), 4.5, f"{fg} on {bg}")


class Balance(HTMLParser):
    VOID = {"meta", "br", "img", "input", "link", "hr"}

    def __init__(self):
        super().__init__()
        self.stack = []
        self.errors = []

    def handle_starttag(self, tag, attrs):
        if tag not in self.VOID:
            self.stack.append(tag)

    def handle_endtag(self, tag):
        if tag in self.VOID:
            return
        if self.stack and self.stack[-1] == tag:
            self.stack.pop()
        else:
            self.errors.append((tag, self.getpos()))


class MarkupTests(RenderTestCase):
    def test_every_page_has_balanced_tags(self):
        for path, text in self.pages().items():
            parser = Balance()
            parser.feed(text)
            parser.close()
            self.assertEqual((parser.errors, parser.stack), ([], []), path)

    def test_ids_are_unique_within_each_page(self):
        for path, text in self.pages().items():
            ids = scan(text).ids
            self.assertEqual([i for i, n in Counter(ids).items() if n > 1], [], path)


class CheckModeTests(RenderTestCase):
    def test_check_passes_on_fresh_pages_and_names_stale_and_missing_pages(self):
        args = ["--data-dir", str(self.data_dir), "--out", str(self.out_dir)]
        self.assertEqual(run_cli(args).returncode, 0)
        fresh = run_cli([*args, "--check"])
        self.assertEqual(fresh.returncode, 0, fresh.stderr)
        victim = self.out_dir / "harness" / "cursor.html"
        data = bytearray(victim.read_bytes())
        data[len(data) // 2] ^= 0x01  # one byte
        victim.write_bytes(bytes(data))
        stale = run_cli([*args, "--check"])
        self.assertNotEqual(stale.returncode, 0)
        self.assertIn("stale: harness/cursor.html", stale.stderr)
        self.assertNotIn("matrix.html", stale.stderr)
        (self.out_dir / "method.html").unlink()
        both = run_cli([*args, "--check"])
        self.assertNotEqual(both.returncode, 0)
        self.assertIn("stale: harness/cursor.html", both.stderr)
        self.assertIn("missing: method.html", both.stderr)

    def test_check_detects_a_data_change(self):
        args = ["--data-dir", str(self.data_dir), "--out", str(self.out_dir)]
        self.assertEqual(run_cli(args).returncode, 0)
        data = load_json(self.data_dir / "snapshot.json")
        data["known_gaps"] = ["a different gap"]
        dump_json(self.data_dir / "snapshot.json", data)
        result = run_cli([*args, "--check"])
        self.assertEqual(result.returncode, 1)
        self.assertIn("stale: index.html", result.stderr)
        self.assertIn("stale: method.html", result.stderr)

    def test_check_never_writes(self):
        result = run_cli(["--data-dir", str(self.data_dir), "--out", str(self.out_dir), "--check"])
        self.assertNotEqual(result.returncode, 0)
        self.assertFalse(self.out_dir.exists())


class GeneratedMarkerTests(RenderTestCase):
    def test_every_page_begins_after_the_doctype_with_the_marker(self):
        for path, text in self.pages().items():
            self.assertTrue(text.startswith(f"<!DOCTYPE html>\n{MARKER}\n"), path)


class NoNumericConfidenceTests(RenderTestCase):
    def test_a_forbidden_key_exits_nonzero_naming_it(self):
        for key in ("confidence", "probability", "certainty"):
            for kind in ("cell", "lever", "evidence", "task"):
                with self.subTest(key=key, kind=kind):
                    data = fixture()
                    if kind == "cell":
                        data["cells"]["claude-code"][0][key] = 0.9
                    elif kind == "lever":
                        data["levers"]["levers"][0]["scope"] = {"nested": [{key.upper(): 1}]}
                    elif kind == "evidence":
                        data["evidence"]["claude-code"][0][key] = 0.5
                    else:
                        data["levers"]["task_shape_rows"][0][key] = 1
                    broken = write_data(self.root / f"bad-{key}-{kind}", data)
                    code, _, err = run_main(["--data-dir", str(broken), "--out", str(self.out_dir)])
                    self.assertEqual(code, 2)
                    self.assertIn(key, err.lower())
        self.assertFalse(self.out_dir.exists())

    def test_the_lever_page_prints_no_confidence_or_percentages(self):
        text = self.pages()["levers.html"]
        self.assertNotIn("confidence", text.lower())
        self.assertNotRegex(re.sub(r"<style>.*?</style>", "", text, flags=re.S), r"[0-9]\s*%")


class ContentTests(RenderTestCase):
    def test_matrix_anchors_cells_and_clipping(self):
        matrix = self.pages()["matrix.html"]
        self.assertIn('<section id="F04">', matrix)
        self.assertIn('<tr id="F04.approval-modes">', matrix)
        block = matrix[matrix.index('<tr id="F04.approval-modes">') :]
        block = block[: block.index("</tr>")]
        shown = LONG_VALUE[:60] + "…"
        self.assertIn(f'title="{LONG_VALUE}">{shown}</span>', block)
        self.assertNotIn(f">{LONG_VALUE}<", block)
        self.assertIn(
            'role="img" aria-label="supported">●</span> <span class="w">supported</span>', block
        )
        self.assertIn("evidence: 2", block)
        self.assertIn('href="harness/claude-code.html#claude-code/F04.approval-modes"', block)
        self.assertIn('href="harness/copilot.html#copilot-vscode/F04.approval-modes"', block)
        self.assertIn('aria-label="no data">∅</span>', block)

    def test_matrix_orders_columns_and_facets_from_the_data_files(self):
        matrix = self.pages()["matrix.html"]
        head = matrix[matrix.index("<thead>") : matrix.index("</thead>")]
        names = re.findall(r"<a href=\"harness/[^\"]+\">([^<]+)</a>", head)
        self.assertEqual(names, [s["name"] for s in SURFACES])
        facet_ids = re.findall(r'<section id="(F\d\d)">', matrix)
        facets = load_json(DATA_DIR / "facets.json")["facets"]
        self.assertEqual(facet_ids, [f["id"] for f in facets])

    def test_the_six_states_print_glyph_and_word_in_the_state_tables(self):
        pages = self.pages()
        for page in ("index.html", "method.html"):
            for _, glyph, word, _ in render.STATES:
                self.assertIn(
                    f'aria-label="{word}">{glyph}</span></td><td>{word}</td>', pages[page], page
                )

    def test_unverified_cells_print_the_marker_text(self):
        harness = self.pages()["harness/claude-code.html"]
        auto = self.cell_block(harness, "claude-code/F04.auto-review")
        self.assertIn("[unverified: single secondary source; settles by fetch the changelog]", auto)
        self.assertIn('aria-label="unverified">!</span> <span class="w">unverified</span>', auto)
        picker = self.cell_block(harness, "claude-code/F17.model-picker")
        self.assertIn("[unverified: no verified evidence record; settles by re-extraction]", picker)
        verified = self.cell_block(harness, "claude-code/F21.host-platform")
        self.assertNotIn("unverified", verified)
        matrix = self.pages()["matrix.html"]
        row = matrix[matrix.index('<tr id="F17.model-picker">') :]
        self.assertIn('aria-label="unverified">!</span>', row[: row.index("</tr>")])

    def test_marker_text_variants(self):
        self.assertEqual(
            render.marker_text(
                {"marker": "[unverified: why; settles by probe]", "settles_by": "other"}
            ),
            "[unverified: why; settles by probe]",
        )
        self.assertEqual(
            render.marker_text({"marker": "why", "settles_by": "probe"}),
            "[unverified: why; settles by probe]",
        )
        self.assertEqual(
            render.marker_text({}),
            "[unverified: no verified evidence record; settles by re-extraction]",
        )
        self.assertEqual(
            render.marker_text({"settles_by": "x"}),
            "[unverified: no verified evidence record; settles by x]",
        )

    def test_harness_page_puts_f21_first_then_the_rest_in_data_order(self):
        harness = self.pages()["harness/claude-code.html"]
        order = re.findall(r'<section id="(F\d\d)">', harness)
        facets = [f["id"] for f in load_json(DATA_DIR / "facets.json")["facets"]]
        self.assertEqual(order, ["F21"] + [f for f in facets if f != "F21"])

    def test_harness_rows_show_value_evidence_citation_levers_and_register_entries(self):
        harness = self.pages()["harness/claude-code.html"]
        block = self.cell_block(harness, "claude-code/F04.approval-modes")
        self.assertIn(f"<strong>Value:</strong> {LONG_VALUE}", block)
        self.assertIn("E-claude-code-00001", block)
        self.assertIn('<a href="https://code.claude.com/docs/en/permissions">', block)
        self.assertIn('retrieved <time datetime="2026-09-01">2026-09-01</time>', block)
        self.assertIn("version 2.0.1", block)
        self.assertIn("tier E1", block)
        self.assertIn("version not recorded", block)
        self.assertIn("Described span: an install command line (raw lines 9-9)", block)
        self.assertIn('<a href="../register.html#ENH-001">ENH-001</a>', block)
        modes = self.cell_block(harness, "claude-code/F19.named-modes")
        self.assertIn("<code>--permission-mode</code>", modes)
        self.assertIn("<code>plan</code>", modes)

    def test_each_state_shows_its_own_evidence_role(self):
        harness = self.pages()["harness/claude-code.html"]
        self.assertIn(
            "<strong>Vendor statement:</strong>",
            self.cell_block(harness, "claude-code/F04.path-scoping"),
        )
        self.assertIn(
            "<strong>Positive quote:</strong>",
            self.cell_block(harness, "claude-code/F04.command-scoping"),
        )
        self.assertIn(
            "<strong>Limitation:</strong>",
            self.cell_block(harness, "claude-code/F04.per-tool-rules"),
        )
        sweep = self.cell_block(harness, "claude-code/F04.trust-prompt")
        self.assertIn(
            "Sweep: terms trust; hits 0, reviewed 0; positive control permission (4 hits)", sweep
        )

    def test_copilot_page_carries_both_columns_and_marks_missing_data(self):
        harness = self.pages()["harness/copilot.html"]
        self.assertIn("<h4>GitHub Copilot CLI</h4>", harness)
        self.assertIn("<h4>GitHub Copilot in VS Code (agent and chat)</h4>", harness)
        vscode = self.cell_block(harness, "copilot-vscode/F04.approval-modes")
        self.assertIn("<strong>Limitation:</strong> IDE only", vscode)
        cli = self.cell_block(harness, "copilot-cli/F04.approval-modes")
        self.assertIn("no data", cli)
        self.assertNotIn("<h4>", self.pages()["harness/cursor.html"])

    def test_index_counts_each_surface_by_state_and_verification(self):
        atlas = render.Atlas(self.data_dir)
        index = self.pages()["index.html"]
        table = index[index.index("Cell counts per column") :]
        row = table[table.index("Claude Code") : table.index("</tr>", table.index("Claude Code"))]
        numbers = [int(n) for n in re.findall(r"<td>(\d+)</td>", row)]
        # supported, partial, not exposed, n/a, undocumented, not researched, no data, verified, unverified, U00
        self.assertEqual(numbers, [4, 1, 1, 1, 1, 1, len(atlas.row_ids) - 9, 6, 3, 1])
        row = table[table.index("Cursor") : table.index("</tr>", table.index("Cursor"))]
        self.assertEqual(
            [int(n) for n in re.findall(r"<td>(\d+)</td>", row)][6], len(atlas.row_ids)
        )

    def test_index_banner_lists_every_column_with_version_source_and_date(self):
        index = self.pages()["index.html"]
        table = index[index.index("Columns and snapshot") : index.index("Success signal")]
        for sid in SURFACE_IDS:
            self.assertIn(f"<code>{sid}</code>", table)
        self.assertIn("<td>2.0.1</td><td>npm</td>", table)
        self.assertIn('<time datetime="2026-10-04">2026-10-04</time>', table)
        self.assertIn("<td>not recorded</td><td>not recorded</td>", table)
        self.assertIn("Freeze window:</strong> 2026-10-01 to 2026-10-04", index)

    def test_index_shows_top_ten_register_entries_by_rank_and_the_gaps(self):
        data = fixture()
        data["register"]["entries"] = [
            {
                "id": f"ENH-{n:03d}",
                "title": f"t{n}",
                "type": "extend",
                "rank": 20 - n,
                "status": "proposed",
            }
            for n in range(1, 16)
        ]
        index = render_pages(write_data(self.root / "ten", data))["index.html"]
        top = index[index.index("Top 10 register entries by rank") :]
        top = top[: top.index("</table>")]
        self.assertEqual(
            re.findall(r">(ENH-\d{3})</a>", top), [f"ENH-{n:03d}" for n in range(15, 5, -1)]
        )
        self.assertIn("gap one", index)

    def test_success_signal_all_eight_backed(self):
        data = fixture()
        data["levers"]["task_shape_rows"] = [task(s, POINTER) for s in SURFACE_IDS]
        index = render_pages(write_data(self.root / "all", data))["index.html"]
        self.assertIn("8 of 8 columns have matrix-backed lever guidance", index)
        self.assertNotIn("flagged", index)

    def test_success_signal_switches_to_the_flagged_text_when_matrix_pending(self):
        data = fixture()
        backed = ["claude-code", "codex-cli", "copilot-cli", "copilot-vscode", "grok-build"]
        pending = ["cursor", "gemini-cli", "grok-bot"]
        data["levers"]["task_shape_rows"] = [task(s, POINTER) for s in backed] + [
            task(s, None, "editorial-judgment", "matrix row pending") for s in pending
        ]
        data["snapshot"]["matrix_pending"] = True
        index = render_pages(write_data(self.root / "pending", data))["index.html"]
        self.assertIn(
            "5 of 8 (flagged: matrix rows pending for cursor, gemini-cli, grok-bot)", index
        )
        self.assertNotIn("columns have matrix-backed lever guidance", index)

    def test_success_signal_cannot_claim_more_than_the_data_backs(self):
        data = fixture()  # one pointer row, flag absent: the line must still be flagged
        index = render_pages(write_data(self.root / "thin", data))["index.html"]
        self.assertIn("1 of 8 (flagged: matrix rows pending for codex-cli,", index)
        self.assertNotIn("8 of 8", index)
        data["levers"]["task_shape_rows"] = [task(s, POINTER) for s in SURFACE_IDS]
        data["snapshot"]["matrix_pending"] = True
        index = render_pages(write_data(self.root / "flag", data))["index.html"]
        self.assertIn("8 of 8 (flagged: matrix rows pending for none)", index)

    def test_levers_page_heading_records_pointer_sha_and_the_judgment_badge(self):
        levers = self.pages()["levers.html"]
        self.assertIn("<h1>Lever guide: documented controls, editorial routing</h1>", levers)
        self.assertIn("<code>--permission-mode</code>", levers)
        self.assertIn("<td>session</td>", levers)
        self.assertIn("<code>default</code>", levers)
        self.assertIn("<code>model_reasoning_effort</code>", levers)
        self.assertIn("<code>gpt-y</code> [unverified]", levers)
        tasks = levers[levers.index("Task-shape rows</caption>") :]
        rows = re.findall(r"<tr>.*?</tr>", tasks, flags=re.S)
        capability = next(r for r in rows if "task for claude-code" in r)
        judgment = next(r for r in rows if "task for cursor" in r)
        self.assertIn("file <code>plugins/x/agent-routing-matrix.json</code>", capability)
        self.assertIn(f"matrix_sha <code>{'b' * 40}</code>", capability)
        self.assertNotIn("badge", capability)
        self.assertIn('<span class="badge">judgment, not measured</span>', judgment)
        self.assertIn("pending", judgment)
        self.assertEqual(levers.count('<span class="badge">judgment, not measured</span>'), 1)
        self.assertIn('href="#lever-0"', capability)

    def test_levers_page_groups_by_surface_then_lever_class_in_data_order(self):
        levers = self.pages()["levers.html"]
        h3 = re.findall(r"<h3>([^<]+)</h3>", levers)
        self.assertEqual(h3, ["Claude Code: mode", "OpenAI Codex CLI: effort"])
        self.assertIn('<tr id="lever-0">', levers)

    def test_lever_basis_other_than_capability_fact_is_badged(self):
        data = fixture()
        data["levers"]["task_shape_rows"] = [
            task("claude-code", POINTER, "capability-fact"),
            task("codex-cli", POINTER, "editorial-judgment"),
            task("cursor", POINTER, "inferred-from-docs"),
            task("gemini-cli", POINTER, None),
        ]
        levers = render_pages(write_data(self.root / "badge", data))["levers.html"]
        self.assertEqual(levers.count("judgment, not measured</span>"), 3)

    def test_register_is_sorted_by_rank_then_id_and_links_cells(self):
        register = self.pages()["register.html"]
        self.assertLess(register.index('id="ENH-001"'), register.index('id="ENH-002"'))
        self.assertIn('href="harness/claude-code.html#claude-code/F04.approval-modes"', register)
        self.assertIn('href="sources/claude-code.html#claude-code/U00/1"', register)
        self.assertNotIn("nowhere/F04.x</code></a>", register)
        self.assertIn("<code>nowhere/F04.x</code>", register)
        self.assertIn("basis: inference (falsified by: read the page)", register)
        self.assertIn("<td>7.5</td>", register)
        self.assertIn("<td>proposed</td>", register)

    def test_register_sort_puts_unranked_entries_last_and_ties_by_id(self):
        data = fixture()
        entries = [
            {"id": "ENH-005", "title": "u", "type": "extend", "status": "proposed"},
            {"id": "ENH-004", "title": "b", "type": "extend", "rank": 1, "status": "proposed"},
            {"id": "ENH-003", "title": "a", "type": "extend", "rank": 1, "status": "proposed"},
        ]
        data["register"]["entries"] = entries
        register = render_pages(write_data(self.root / "sort", data))["register.html"]
        found = re.findall(r'<tr id="(ENH-\d+)">', register)
        self.assertEqual(found, ["ENH-003", "ENH-004", "ENH-005"])

    def test_sources_pages_list_every_record_coverage_and_unmapped(self):
        pages = self.pages()
        text = pages["sources/claude-code.html"]
        for number in (1, 2, 3):
            self.assertIn(f'<tr id="E-claude-code-0000{number}">', text)
        self.assertIn(f"<code>{SHA}</code>", text)
        self.assertIn("Modes, raw lines 3-5", text)
        self.assertIn("Described span: an install command line (raw lines 9-9)", text)
        self.assertIn("<td>yes</td>", text)
        self.assertIn('<th scope="row">pages</th><td>120</td>', text)
        self.assertIn('<li id="claude-code/U00/1">', text)
        self.assertIn("Unmapped feature", text)
        none = pages["sources/cursor.html"]
        self.assertEqual(none.count('<p class="nodata">no data</p>'), 3)
        self.assertIn("E-codex-cli-00001", pages["sources/codex-cli.html"])

    def test_method_page_has_tables_verification_note_and_gaps(self):
        method = self.pages()["method.html"]
        for tier, meaning in render.TIERS:
            self.assertIn(f'<th scope="row">{tier}</th><td>{meaning}</td>', method)
        self.assertIn('<th scope="row">quotes_checked</th><td>12</td>', method)
        self.assertIn(
            "Grok Bot is covered as its own column; its relationship to the Cursor platform "
            "is recorded in row F21.shared-agent-runtime",
            method,
        )
        self.assertIn('href="harness/grok-bot.html#grok-bot/F21.shared-agent-runtime"', method)
        self.assertIn("gap one", method)

    def test_evidence_cited_by_a_cell_but_missing_from_the_data_says_so(self):
        data = fixture()
        data["cells"]["claude-code"][0]["evidence"] = ["E-claude-code-99999"]
        harness = render_pages(write_data(self.root / "dangling", data))["harness/claude-code.html"]
        block = self.cell_block(harness, "claude-code/F04.approval-modes")
        self.assertIn('E-claude-code-99999</span> <span class="nodata">(no record)</span>', block)


class StalePageTests(RenderTestCase):
    """Finding 4: a page the renderer no longer produces must never ship silently."""

    EXTRAS = ("harness/old-product.html", "sources/old-surface.html", "leftover.html")

    def write_extras(self):
        for name in self.EXTRAS:
            target = self.out_dir / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text("<p>old</p>\n", encoding="utf-8")

    def args(self, *more):
        return ["--data-dir", str(self.data_dir), "--out", str(self.out_dir), *more]

    def test_check_names_every_extra_page_and_fails(self):
        self.assertEqual(run_cli(self.args()).returncode, 0)
        self.write_extras()
        result = run_cli(self.args("--check"))
        self.assertEqual(result.returncode, 1, result.stderr)
        for name in self.EXTRAS:
            self.assertIn(name, result.stderr)
        self.assertNotIn("up to date", result.stdout)
        self.assertNotIn("stale: harness/cursor.html", result.stderr)

    def test_check_passes_again_once_the_extra_pages_are_gone(self):
        self.assertEqual(run_cli(self.args()).returncode, 0)
        self.write_extras()
        for name in self.EXTRAS:
            (self.out_dir / name).unlink()
        result = run_cli(self.args("--check"))
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_write_mode_keeps_extra_pages_warns_and_exits_nonzero(self):
        self.write_extras()
        result = run_cli(self.args())
        self.assertEqual(result.returncode, 1, result.stderr)
        for name in self.EXTRAS:
            self.assertIn(name, result.stderr)
            self.assertTrue((self.out_dir / name).is_file(), f"{name} was deleted")
            self.assertEqual((self.out_dir / name).read_text(encoding="utf-8"), "<p>old</p>\n")
        written = {p for p in read_tree(self.out_dir) if p.endswith(".html")}
        self.assertEqual(written, set(EXPECTED_PAGES) | set(self.EXTRAS))

    def test_only_html_files_in_the_three_folders_count(self):
        self.assertEqual(run_cli(self.args()).returncode, 0)
        for name in ("notes.txt", "harness/readme.md", "sources/data.json", "elsewhere/page.html"):
            target = self.out_dir / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text("x", encoding="utf-8")
        result = run_cli(self.args("--check"))
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_extra_pages_are_found_with_main_in_process_too(self):
        run_main(self.args())
        self.write_extras()
        code, _, err = run_main(self.args("--check"))
        self.assertEqual(code, 1)
        self.assertEqual(sum(1 for name in self.EXTRAS if name in err), len(self.EXTRAS))

    def test_the_default_out_folder_is_not_polluted_by_a_check(self):
        self.assertEqual(run_cli(self.args("--check")).returncode, 1)
        self.assertFalse(self.out_dir.exists())


class LongCitationTests(RenderTestCase):
    """Finding 12: a long URL must wrap instead of widening the page."""

    @staticmethod
    def rules():
        return [
            ([s.strip() for s in selectors.split(",")], body)
            for selectors, body in re.findall(r"([^{}@]+)\{([^{}]*)\}", render.CSS)
        ]

    def wraps(self, selector):
        return any(
            selector in selectors and "overflow-wrap:anywhere" in body
            for selectors, body in self.rules()
        )

    def test_citations_and_their_links_may_break_anywhere(self):
        # The rule is the lever that stops the sideways scroll: a headless-browser measurement
        # needs playwright, which is not importable in this environment.
        for selector in (".cite", ".cite a", "td a"):
            self.assertTrue(self.wraps(selector), selector)

    def test_a_long_citation_url_sits_in_a_cite_paragraph_with_the_rule_in_force(self):
        data = fixture()
        long_url = "https://code.claude.com/docs/" + "a" * 400
        data["evidence"]["claude-code"][0]["url"] = long_url
        pages = render_pages(write_data(self.root / "long", data))
        block = self.cell_block(pages["harness/claude-code.html"], "claude-code/F04.approval-modes")
        self.assertRegex(block, r'<p class="cite">Source: <a href="' + re.escape(long_url))
        self.assertIn(long_url, pages["sources/claude-code.html"])

    def test_the_stylesheet_is_still_small(self):
        self.assertLess(len(render.CSS.encode("utf-8")), 6 * 1024)


class UnnumberedUnmappedTests(RenderTestCase):
    """Finding 13: <surface>/U00 is as linkable as <surface>/U00/<n>."""

    def test_both_forms_link_to_the_sources_page_anchor(self):
        data = fixture()
        unnumbered = cell("claude-code", "U00", "supported", value="First unmapped")
        data["cells"]["claude-code"].append(unnumbered)
        data["register"]["entries"][1]["cells"] = [
            "claude-code/U00",
            "claude-code/U00/1",
            "claude-code/U00x",
        ]
        pages = render_pages(write_data(self.root / "u00", data))
        register = pages["register.html"]
        self.assertIn(
            '<a href="sources/claude-code.html#claude-code/U00"><code>claude-code/U00</code></a>',
            register,
        )
        self.assertIn('href="sources/claude-code.html#claude-code/U00/1"', register)
        self.assertNotIn("claude-code/U00x</code></a>", register)
        self.assertIn("<code>claude-code/U00x</code>", register)
        self.assertIn('<li id="claude-code/U00">', pages["sources/claude-code.html"])

    def test_the_link_resolves_to_an_id_on_the_target_page(self):
        data = fixture()
        data["cells"]["claude-code"].append(cell("claude-code", "U00", "supported"))
        data["register"]["entries"][1]["cells"] = ["claude-code/U00"]
        pages = render_pages(write_data(self.root / "u00b", data))
        self.assertIn("claude-code/U00", scan(pages["sources/claude-code.html"]).ids)


def more_evidence(data, count, surface="claude-code", row="F04.approval-modes"):
    """Give one cell ``count`` evidence ids, adding the records the cell now cites."""
    ids = [f"E-{surface}-{n:05d}" for n in range(1, count + 1)]
    kept = [e for e in data["evidence"][surface] if e["id"] not in ids]
    fresh = [
        evidence(surface, number, quote=f"Quote number {number} for the cell")
        for number in range(1, count + 1)
    ]
    data["evidence"][surface] = fresh + kept
    target = next(c for c in data["cells"][surface] if c["row"] == row)
    target["evidence"] = ids
    return ids


class QuoteBudgetTests(RenderTestCase):
    """Finding 14: harness pages show two quotes per cell; sources pages keep every record."""

    CELL = "claude-code/F04.approval-modes"

    def render(self, count, **changes):
        data = fixture()
        ids = more_evidence(data, count)
        if changes:
            changes["apply"](data, ids)
        return render_pages(write_data(self.root / f"q{count}", data)), ids

    def test_two_quotes_then_a_link_with_the_remaining_count(self):
        pages, ids = self.render(6)
        block = self.cell_block(pages["harness/claude-code.html"], self.CELL)
        self.assertEqual(block.count("<blockquote>"), 2)
        self.assertEqual(block.count("<li><strong>") + block.count('<li><a class="mono"'), 2)
        self.assertIn(
            '<li><a href="../sources/claude-code.html#claude-code/F04.approval-modes">'
            "4 more on the sources page</a></li>",
            block,
        )
        for eid in ids[:2]:
            self.assertIn(eid, block)
        for eid in ids[2:]:
            self.assertNotIn(f">{eid}<", block)

    def test_the_link_target_exists_and_the_sources_page_keeps_every_record(self):
        pages, ids = self.render(6)
        sources = pages["sources/claude-code.html"]
        self.assertIn(self.CELL, scan(sources).ids)
        for eid in ids:
            self.assertIn(f'<tr id="{eid}">', sources)
        anchor = sources[sources.index(f'<li id="{self.CELL}">') :]
        anchor = anchor[: anchor.index("</li>")]
        for eid in ids:
            self.assertIn(f'href="#{eid}"', anchor)

    def test_exactly_two_quotes_need_no_link_and_no_anchor(self):
        pages, _ = self.render(2)
        block = self.cell_block(pages["harness/claude-code.html"], self.CELL)
        self.assertEqual(block.count("<blockquote>"), 2)
        self.assertNotIn("more on the sources page", block)
        self.assertNotIn(f'<li id="{self.CELL}">', pages["sources/claude-code.html"])

    def test_one_more_than_the_budget_says_one_more(self):
        pages, _ = self.render(3)
        block = self.cell_block(pages["harness/claude-code.html"], self.CELL)
        self.assertIn("1 more on the sources page</a>", block)

    def test_a_vendor_statement_is_never_the_quote_that_gets_dropped(self):
        def apply(data, ids):
            cell_record = next(
                c for c in data["cells"]["claude-code"] if c["row"] == "F04.path-scoping"
            )
            cell_record["evidence"] = ids[:4]
            cell_record["vendor_statement"] = "E-claude-code-00005"
            data["evidence"]["claude-code"].append(
                evidence("claude-code", 5, quote="The vendor says there is no such control")
            )

        pages, _ = self.render(4, apply=apply)
        block = self.cell_block(pages["harness/claude-code.html"], "claude-code/F04.path-scoping")
        self.assertIn("<strong>Vendor statement:</strong>", block)
        self.assertIn("The vendor says there is no such control", block)
        self.assertEqual(block.count("<blockquote>"), 2)
        self.assertIn("3 more on the sources page", block)

    def test_unmapped_records_keep_every_quote_on_the_sources_page(self):
        def apply(data, ids):
            unmapped = next(c for c in data["cells"]["claude-code"] if c["row"] == "U00")
            unmapped["evidence"] = ids[:5]

        pages, _ = self.render(5, apply=apply)
        sources = pages["sources/claude-code.html"]
        item = sources[sources.index('<li id="claude-code/U00/1">') :]
        item = item[: item.index("</ul></li>")]
        self.assertEqual(item.count("<blockquote>"), 5)

    def test_every_link_still_resolves(self):
        pages, _ = self.render(6)
        ids = {path: set(scan(text).ids) for path, text in pages.items()}
        for path, text in pages.items():
            for _, link in scan(text).links:
                if "://" in link or link.startswith("#"):
                    continue
                target, _, fragment = link.partition("#")
                resolved = posixpath.normpath(posixpath.join(posixpath.dirname(path), target))
                self.assertIn(resolved, pages, f"{path}: {link}")
                if fragment:
                    self.assertIn(unquote(fragment), ids[resolved], f"{path}: {link}")

    def test_ids_stay_unique_on_every_page(self):
        pages, _ = self.render(6)
        for path, text in pages.items():
            repeated = [i for i, n in Counter(scan(text).ids).items() if n > 1]
            self.assertEqual(repeated, [], path)

    def test_a_dangling_overflow_reference_still_renders(self):
        def apply(data, ids):
            next(c for c in data["cells"]["claude-code"] if c["row"] == "F04.approval-modes")[
                "evidence"
            ] = [*ids, "E-claude-code-99999"]

        pages, _ = self.render(4, apply=apply)
        self.assertIn("E-claude-code-99999", pages["sources/claude-code.html"])
        self.assertIn("3 more on the sources page", pages["harness/claude-code.html"])


def synthetic_dataset():
    """127 frozen rows by 8 surfaces, six 300-character quotes per cell, 400-character values."""
    facets = load_json(DATA_DIR / "facets.json")["facets"]
    rows = [r["id"] for facet in facets for r in facet["rows"]]
    data = {"cells": {}, "evidence": {}}
    for surface in SURFACES:
        sid = surface["id"]
        host = surface["docs_hosts"][0]
        cells, records, number = [], [], 0
        for row in rows:
            ids = []
            for _ in range(6):
                number += 1
                ids.append(f"E-{sid}-{number:05d}")
                records.append(
                    evidence(
                        sid,
                        number,
                        url=f"https://{host}/docs/" + "segment/" * 12 + str(number),
                        quote=(f"quote {number} about {row} " * 30)[:300],
                    )
                )
            value = (f"value for {sid} {row} " * 40)[:400]
            cells.append(cell(sid, row, "supported", value=value, evidence=ids))
        data["cells"][sid] = cells
        data["evidence"][sid] = records
    return data


class WorstCaseSizeTests(RenderTestCase):
    def test_a_full_dataset_leaves_headroom_under_both_limits(self):
        data = synthetic_dataset()
        self.assertEqual(sum(len(v) for v in data["cells"].values()), 127 * 8)
        base = write_data(self.root / "big", data)
        encoded = render.encode_pages(render_pages(base))
        render.check_sizes(encoded)
        sizes = {path: len(blob) for path, blob in encoded.items()}
        largest = max(sizes, key=sizes.get)
        self.assertLessEqual(sizes[largest], 1_500_000, largest)
        self.assertLess(sum(sizes.values()), 12_000_000)
        harness = {p: n for p, n in sizes.items() if p.startswith("harness/")}
        self.assertLess(max(harness.values()), 1_000_000, harness)

    def test_every_record_is_still_on_the_sources_pages_of_the_full_dataset(self):
        data = synthetic_dataset()
        base = write_data(self.root / "big2", data)
        pages = render_pages(base)
        for sid, records in data["evidence"].items():
            text = pages[f"sources/{sid}.html"]
            self.assertEqual(text.count('<tr id="E-'), len(records), sid)


class UnitTests(unittest.TestCase):
    def test_clean_replaces_unsafe_characters_and_normalises_newlines(self):
        self.assertEqual(render.clean(None), "")
        self.assertEqual(render.clean(5), "5")
        self.assertEqual(render.clean("a\ud800b\udfffc"), "a�b�c")
        self.assertEqual(render.clean("a\x00b\x1bc\x7fd\x85e"), "a�b�c�d�e")
        self.assertEqual(render.clean("‮x⁦y⁩"), "�x�y�")
        self.assertEqual(render.clean("a\r\nb\rc\nd\te"), "a\nb\nc\nd\te")
        self.assertEqual(render.clean("\U0001f600 café א"), "\U0001f600 café א")

    def test_esc_quotes_everything_html_cares_about(self):
        self.assertEqual(
            render.esc("<a href=\"x\" b='y'>&"), "&lt;a href=&quot;x&quot; b=&#x27;y&#x27;&gt;&amp;"
        )

    def test_clip(self):
        self.assertEqual(render.clip("x" * 60), "x" * 60)
        self.assertEqual(render.clip("x" * 61), "x" * 60 + "…")

    def test_time_html_only_wraps_a_well_formed_date(self):
        self.assertEqual(
            render.time_html("2026-10-04"), '<time datetime="2026-10-04">2026-10-04</time>'
        )
        self.assertEqual(render.time_html('x"><b>'), "x&quot;&gt;&lt;b&gt;")
        self.assertEqual(render.time_html(None), "")

    def test_lever_refs_match_whatever_the_null_model_spelling(self):
        key = render.lever_key("claude-code", "mode", None)
        for spelled in (
            "claude-code|mode|",
            "claude-code|mode|null",
            "claude-code|mode|*",
            "claude-code|mode|ALL",
        ):
            self.assertEqual(render.ref_key(spelled), key)
        self.assertNotEqual(render.ref_key("claude-code|mode|opus"), key)
        self.assertEqual(render.ref_key("not a ref"), "not a ref")

    def test_ordered_keeps_known_order_then_the_rest_sorted(self):
        self.assertEqual(render.ordered(["b", "a"], ["z", "a", "y"]), ["a", "y", "z"])
        self.assertEqual(render.ordered(["b", "a"], ["a", "b"]), ["b", "a"])


if __name__ == "__main__":
    unittest.main()
