"""Render the harness-atlas data files into self-contained HTML pages.

The pages are generated views of the data: they carry fixed labels and nothing drafted. Missing
data renders as an explicit "no data" cell, so the renderer works on a nearly empty data directory.
Output is deterministic: no clock, no locale, no set iteration, UTF-8, LF, one trailing newline.

Usage: python3 render.py [--data-dir DIR] [--out DIR]
       python3 render.py --check          render in memory, compare with the files on disk
"""

import argparse
import base64
import html
import posixpath
import re
import sys
from pathlib import Path
from urllib.parse import quote, urlsplit

from atlas_common import ATLAS_DIR, DATA_DIR, assert_worktree, load_json, sha256_bytes

GENERATED = "<!-- Generated by _tools/render.py from data/. Do not edit by hand. -->"
ATLAS_TITLE = "Coding-agent harness atlas"
MAX_PAGE_BYTES = 1_500_000
MAX_TOTAL_BYTES = 12_000_000
CLIP = 60
MAX_HARNESS_QUOTES = 2
FORBIDDEN_KEYS = ("confidence", "probability", "certainty")
EXTRA_HOSTS = ("github.com",)
REPO_BLOB_BASE = "https://github.com/mcorbett51090/RavenClaude/blob/main/"
PRODUCT_NAMES = {"copilot": "GitHub Copilot"}
NULL_MODEL_TOKENS = ("", "null", "none", "*", "all")
LEVER_GUIDE_INTRO = (
    "Lever locations are documented facts: a flag, key, command or picker, with a citation. Task-shape "
    "rows are the routing matrix's own recommendations (agent, tier, rank, basis), copied from one "
    "matrix file pinned by SHA, beside the lever settings that realise them. Everything except a "
    "capability-fact is a judgment, not measured. A task class or column the matrix has no row for "
    "shows that, not a guess."
)
GROK_BOT_NOTE = (
    "Grok Bot is covered as its own column; its relationship to the Cursor platform "
    "is recorded in row F21.shared-agent-runtime."
)

# (id, glyph, word, meaning): the six states. Never colour alone: glyph and word always print.
STATES = (
    ("supported", "●", "supported", "documented and present"),
    ("partial", "◐", "partial", "present, with a quoted limitation"),
    ("not-exposed", "◌", "not exposed", "documented as having no such control"),
    ("not-applicable", "—", "n/a", "does not apply, shown by a positive quote"),
    ("undocumented", "?", "undocumented", "corpus swept, nothing found, positive control hit"),
    ("not-researched", "·", "not researched", "not yet read"),
)
STATE_INFO = {sid: (glyph, word) for sid, glyph, word, _ in STATES}
VERIFICATIONS = ("verified", "unverified")
TIERS = (
    ("E1", "docs"),
    ("E2", "changelog"),
    ("E3", "source at a commit"),
    ("E4", "executed"),
    ("R", "repo statement"),
    ("S", "secondary (discovery only)"),
    ("U", "training knowledge (never verified)"),
)
NAV = (
    ("index.html", "Overview"),
    ("matrix.html", "Matrix"),
    ("levers.html", "Lever guide"),
    ("register.html", "Register"),
    ("method.html", "Method"),
)
EVIDENCE_ROLES = (
    ("vendor_statement", "Vendor statement"),
    ("reference_page_evidence", "Reference page (positive control)"),
    ("na_quote", "Positive quote"),
)

AGE_SCRIPT = (
    '(function(){var n=Date.now();document.querySelectorAll("time[datetime]").forEach('
    'function(t){var d=Date.parse(t.getAttribute("datetime"));if(isNaN(d)){return;}'
    'var a=Math.floor((n-d)/864e5);var s=document.createElement("span");s.className="age";'
    's.textContent=" ("+(a<=30?"fresh":a<=90?"ageing":"stale")+")";t.appendChild(s);});})();'
)

CSS = """
:root{--bg:#ffffff;--surface:#f3f5f8;--text:#1b1f24;--muted:#4b5563;--border:#c5ccd6;
--accent:#0b4fb3;--t-supported:#d9f5e0;--t-partial:#fdf3c4;--t-not-exposed:#e4e9ef;
--t-not-applicable:#eceff3;--t-undocumented:#fde0dd;--t-not-researched:#ebe2fb;--t-nodata:#ffffff;
--s1:4px;--s2:8px;--s3:12px;--s4:16px;--s5:24px;--s6:32px}
@media (prefers-color-scheme: dark){:root{--bg:#0e1116;--surface:#171c23;--text:#e8edf3;
--muted:#a4afbd;--border:#3a4350;--accent:#8cc2ff;--t-supported:#143323;--t-partial:#3b3210;
--t-not-exposed:#232a33;--t-not-applicable:#1e242c;--t-undocumented:#43201f;
--t-not-researched:#2c2347;--t-nodata:#0e1116}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);
font:16px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif}
header,main{max-width:1400px;margin:0 auto;padding:0 var(--s4)}
main>p,main>ul,main>ol{max-width:75ch}
main{padding-bottom:var(--s6)}
h1{font-size:1.75rem;line-height:1.2;margin:var(--s5) 0 var(--s4)}
h2{font-size:1.35rem;margin:var(--s6) 0 var(--s3)}
h3{font-size:1.1rem;margin:var(--s5) 0 var(--s2)}
h4{font-size:1rem;margin:var(--s4) 0 var(--s2)}
p{margin:var(--s2) 0}
a{color:var(--accent);text-underline-offset:2px;transition:color .15s}
a:focus-visible,.scroll:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
.skip{position:absolute;left:-9999px;top:var(--s2);background:var(--surface);color:var(--text);
padding:var(--s2) var(--s3);border:1px solid var(--border)}
.skip:focus{left:var(--s2);z-index:1}
nav{padding:var(--s3) 0;border-bottom:1px solid var(--border)}
nav ul{display:flex;flex-wrap:wrap;gap:var(--s2) var(--s4);list-style:none;margin:0;padding:0}
nav a[aria-current]{font-weight:700;color:var(--text)}
code,.mono,.marker{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",
monospace;font-size:.875em;overflow-wrap:anywhere}
.scroll{overflow-x:auto;max-width:100%;margin:var(--s3) 0;border:1px solid var(--border)}
table{border-collapse:collapse;width:100%;min-width:640px}
table.matrix{min-width:960px}
caption{text-align:left;font-weight:600;padding:var(--s2)}
th,td{border:1px solid var(--border);padding:var(--s2);text-align:left;vertical-align:top;
overflow-wrap:anywhere}
th{background:var(--surface);overflow-wrap:normal}
th[scope=row]{font-weight:400}
table.matrix td{min-width:7.5rem;font-size:.85rem;overflow-wrap:break-word}
table.tasks{min-width:1100px}
table.tasks th:nth-child(2),table.tasks td:nth-child(2){min-width:9.5rem}
table.tasks th:nth-child(3),table.tasks td:nth-child(3){min-width:7.5rem}
table.tasks th:nth-child(4),table.tasks td:nth-child(4){min-width:7rem}
table.tasks th:nth-child(5),table.tasks td:nth-child(5){min-width:14rem}
table.tasks th:nth-child(7),table.tasks td:nth-child(7){min-width:14rem}
table.levers{min-width:1000px}
table.levers th:nth-child(1),table.levers td:nth-child(1){min-width:9rem}
table.levers th:nth-child(2),table.levers td:nth-child(2){min-width:8rem}
table.levers th:nth-child(3),table.levers td:nth-child(3){min-width:8rem}
table.levers th:nth-child(4),table.levers td:nth-child(4){min-width:16rem}
table.levers th:nth-child(5),table.levers td:nth-child(5){min-width:7rem}
table.levers th:nth-child(6),table.levers td:nth-child(6){min-width:5rem}
table.levers th:nth-child(7),table.levers td:nth-child(7){min-width:4.5rem}
table.levers th:nth-child(8),table.levers td:nth-child(8){min-width:6.5rem}
table.levers th:nth-child(9),table.levers td:nth-child(9){min-width:9rem}
table.register{min-width:1080px}
table.register th:nth-child(1),table.register td:nth-child(1){width:3.5rem}
table.register th:nth-child(2),table.register td:nth-child(2){min-width:22rem}
table.register th:nth-child(3),table.register td:nth-child(3),table.register th:nth-child(5),
table.register td:nth-child(5),table.register th:nth-child(6),table.register td:nth-child(6){white-space:nowrap}
table.register th:nth-child(4),table.register td:nth-child(4){min-width:7rem}
table.register th:nth-child(7),table.register td:nth-child(7){min-width:12rem}
table.register th:nth-child(8),table.register td:nth-child(8){min-width:10rem}
.s-supported{background:var(--t-supported)}
.s-partial{background:var(--t-partial)}
.s-not-exposed{background:var(--t-not-exposed)}
.s-not-applicable{background:var(--t-not-applicable)}
.s-undocumented{background:var(--t-undocumented)}
.s-not-researched{background:var(--t-not-researched)}
.s-nodata{background:var(--t-nodata)}
.g{display:inline-block;min-width:1.25em;text-align:center;font-weight:700}
.uv{font-weight:700}
.muted,.nodata,.ev{color:var(--muted)}
.ev{display:block;font-size:.875rem}
.badge{display:inline-block;border:1px solid var(--text);border-radius:4px;
padding:0 var(--s2);background:var(--t-partial);color:var(--text);font-size:.875rem}
.cell{border:1px solid var(--border);border-radius:4px;padding:var(--s3);margin:var(--s2) 0}
blockquote{margin:var(--s2) 0;padding:var(--s2) var(--s3);border-left:4px solid var(--border);
background:var(--surface)}
blockquote p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}
.cite{font-size:.875rem;color:var(--muted);margin:var(--s1) 0 var(--s2)}
.cite,.cite a,td a,th a,.cell{overflow-wrap:anywhere}
ul.cols{columns:2 14rem}
@media (prefers-reduced-motion: reduce){*,*::before,*::after{transition:none!important;
animation:none!important}}
"""

_UNSAFE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f\ud800-\udfff‪-‮⁦-⁩]")
_BAD_URL_CHARS = re.compile(r"[\s\x00-\x1f\x7f-\x9f\\]")
_DATE = re.compile(r"^[0-9]{4}-[0-9]{2}-[0-9]{2}$")


class RenderError(Exception):
    """Bad input or a breached limit: reported on stderr, exit 2."""


# --- text, links ---------------------------------------------------------------------------


def clean(value):
    """Text safe to emit: LF only; lone surrogates, controls and bidi overrides become U+FFFD."""
    text = "" if value is None else str(value)
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    return _UNSAFE.sub("�", text)


def esc(value):
    return html.escape(clean(value), quote=True)


def clip(text, limit=CLIP):
    return text if len(text) <= limit else text[:limit] + "…"


def safe_external(url, hosts):
    """True only for an https URL whose host is exactly one of ``hosts`` (no userinfo, no port)."""
    if not isinstance(url, str) or not url.startswith("https://") or _BAD_URL_CHARS.search(url):
        return False
    try:
        parts = urlsplit(url)
        host = parts.hostname
    except ValueError:
        return False
    return bool(host) and host in hosts and parts.netloc.lower() == host


def rel(src, dst):
    return posixpath.relpath(dst, posixpath.dirname(src) or ".")


def href(src, dst, fragment=None):
    base = "" if dst == src and fragment else rel(src, dst)
    if fragment is None:
        return esc(base)
    return esc(f"{base}#{quote(fragment, safe='/.-_:')}")


def local_link(src, dst, text, fragment=None):
    return f'<a href="{href(src, dst, fragment)}">{esc(text)}</a>'


def time_html(date):
    text = clean(date)
    if _DATE.match(text):
        return f'<time datetime="{text}">{text}</time>'
    return esc(text)


def as_list(value):
    return value if isinstance(value, list) else []


def as_dict(value):
    return value if isinstance(value, dict) else {}


def lever_key(surface, lever, model):
    model = "" if model is None else str(model)
    if model.lower() in NULL_MODEL_TOKENS:
        model = ""
    return f"{surface}|{lever}|{model}"


def ref_key(ref):
    parts = str(ref).split("|")
    if len(parts) != 3:
        return str(ref)
    return lever_key(*parts)


def ordered(known, present):
    """``known`` order first, then anything else in ``present`` sorted: nothing is dropped."""
    seen = []
    for item in list(known) + sorted(set(present) - set(known)):
        if item in present and item not in seen:
            seen.append(item)
    return seen


# --- data ------------------------------------------------------------------------------------


def scan_forbidden(obj, where):
    if isinstance(obj, dict):
        for key in obj:
            if str(key).lower() in FORBIDDEN_KEYS:
                raise RenderError(f"numeric-confidence key '{key}' in {where}; none is allowed")
            scan_forbidden(obj[key], where)
    elif isinstance(obj, list):
        for item in obj:
            scan_forbidden(item, where)


def _read(path, required):
    if not path.exists():
        if required:
            raise RenderError(f"{path} is required and missing")
        return None
    try:
        return load_json(path)
    except (OSError, ValueError) as exc:
        raise RenderError(f"{path}: {exc}") from exc


def _records(doc, key, path):
    if doc is None:
        return []
    items = doc.get(key, []) if isinstance(doc, dict) else None
    if not isinstance(items, list) or not all(isinstance(i, dict) for i in items):
        raise RenderError(f"{path}: expected an object whose '{key}' is a list of objects")
    return items


def _check_state(item, what):
    if item.get("state") not in STATE_INFO:
        raise RenderError(f"{what} has an unknown state {item.get('state')!r}")
    if item.get("verification") not in VERIFICATIONS:
        raise RenderError(f"{what} has an unknown verification {item.get('verification')!r}")


class Atlas:
    """The loaded data plus the indexes the pages need."""

    def __init__(self, data_dir):
        data_dir = Path(data_dir)
        facets_doc = _read(data_dir / "facets.json", True)
        surfaces_doc = _read(data_dir / "surfaces.json", True)
        self.surfaces = _records(surfaces_doc, "surfaces", data_dir / "surfaces.json")
        for surface in self.surfaces:
            if not surface.get("id"):
                raise RenderError("surfaces.json: a surface has no id")
        self.surface_ids = [s["id"] for s in self.surfaces]
        self.surface = {s["id"]: s for s in self.surfaces}
        self.lever_classes = as_list(facets_doc.get("lever_classes"))
        main_facets = _records(facets_doc, "facets", data_dir / "facets.json")
        optional = [
            f
            for f in _records(facets_doc, "optional_facets", data_dir / "facets.json")
            if f.get("rows")
        ]
        self.facets = main_facets + optional
        self.rows = {}
        for facet in self.facets:
            for row in as_list(facet.get("rows")):
                self.rows[row.get("id")] = facet
        self.row_ids = list(self.rows)

        self.products = []
        self.product_surfaces = {}
        for surface in self.surfaces:
            pid = surface.get("parent_product") or surface["id"]
            if pid not in self.product_surfaces:
                self.product_surfaces[pid] = []
                self.products.append(pid)
            self.product_surfaces[pid].append(surface)
        self.product_of = {s["id"]: (s.get("parent_product") or s["id"]) for s in self.surfaces}
        self.hosts = tuple(
            sorted(
                {str(h).lower() for s in self.surfaces for h in as_list(s.get("docs_hosts"))}
                | set(EXTRA_HOSTS)
            )
        )

        self.cells = {}
        self.unmapped = {sid: [] for sid in self.surface_ids}
        self.evidence = {}
        self.evidence_by_surface = {}
        for sid in self.surface_ids:
            path = data_dir / "cells" / f"{sid}.json"
            for cell in _records(_read(path, False), "cells", path):
                scan_forbidden(cell, f"cell {cell.get('id')}")
                _check_state(cell, f"cell {cell.get('id')}")
                if cell.get("row") == "U00":
                    self.unmapped[sid].append(cell)
                else:
                    self.cells.setdefault((sid, cell.get("row")), cell)
            path = data_dir / "evidence" / f"{sid}.json"
            records = _records(_read(path, False), "evidence", path)
            for record in records:
                scan_forbidden(record, f"evidence {record.get('id')}")
                self.evidence.setdefault(record.get("id"), record)
            self.evidence_by_surface[sid] = records

        levers_doc = _read(data_dir / "levers.json", False)
        lever_path = data_dir / "levers.json"
        self.levers = _records(levers_doc, "levers", lever_path)
        self.task_rows = []
        if isinstance(levers_doc, dict) and "task_shape_rows" in levers_doc:
            self.task_rows = _records(levers_doc, "task_shape_rows", lever_path)
        for lever in self.levers:
            scan_forbidden(lever, f"lever {lever.get('surface')}/{lever.get('lever')}")
            _check_state(lever, f"lever {lever.get('surface')}/{lever.get('lever')}")
        for task in self.task_rows:
            scan_forbidden(task, f"task-shape row {task.get('surface')}/{task.get('task_class')}")
        self.levers_by_cell = {}
        self.lever_anchor = {}
        self.lever_literals = {}
        for index, lever in enumerate(self.levers):
            cell_key = (lever.get("surface"), lever.get("row"))
            self.levers_by_cell.setdefault(cell_key, []).append(lever)
            key = lever_key(lever.get("surface"), lever.get("lever"), lever.get("model"))
            self.lever_anchor.setdefault(key, f"lever-{index}")
            literal = lever.get("literal")
            if isinstance(literal, str) and literal:
                found = self.lever_literals.setdefault(key, [])
                if literal not in found:
                    found.append(literal)

        register_path = data_dir / "register.json"
        entries = _records(_read(register_path, False), "entries", register_path)
        self.register = sorted(
            entries,
            key=lambda e: (
                not isinstance(e.get("rank"), int),
                e.get("rank") if isinstance(e.get("rank"), int) else 0,
                str(e.get("id")),
            ),
        )
        self.register_by_cell = {}
        for entry in self.register:
            for cell_id in as_list(entry.get("cells")):
                self.register_by_cell.setdefault(cell_id, []).append(entry)

        snapshot = _read(data_dir / "snapshot.json", False)
        self.snapshot = snapshot if isinstance(snapshot, dict) else {}
        self.columns = {}
        for column in as_list(self.snapshot.get("columns")):
            if isinstance(column, dict):
                self.columns.setdefault(column.get("surface"), column)

    def harness_path(self, sid):
        return f"harness/{self.product_of[sid]}.html"

    def product_name(self, pid):
        return PRODUCT_NAMES.get(pid) or clean(self.product_surfaces[pid][0].get("name") or pid)

    def surface_name(self, sid):
        return clean(self.surface[sid].get("name") or sid) if sid in self.surface else clean(sid)


# --- building blocks -------------------------------------------------------------------------


def heading(level, text, anchor=None):
    ident = f' id="{esc(anchor)}"' if anchor else ""
    return f"<h{level}{ident}>{esc(text)}</h{level}>"


def th(content, scope="col"):
    return f'<th scope="{scope}">{content}</th>'


def td(content, cls=""):
    return f'<td class="{cls}">{content}</td>' if cls else f"<td>{content}</td>"


def table(caption, head, rows, cls=""):
    """``head`` and each row's cells are ready HTML; a row is (anchor or None, [cells])."""
    klass = f' class="{cls}"' if cls else ""
    out = [
        f'<div class="scroll" tabindex="0" role="region" aria-label="{esc(caption)}">',
        f"<table{klass}>",
        f"<caption>{esc(caption)}</caption>",
        "<thead><tr>" + "".join(head) + "</tr></thead>",
        "<tbody>",
    ]
    for anchor, cells in rows:
        ident = f' id="{esc(anchor)}"' if anchor else ""
        out.append(f"<tr{ident}>" + "".join(cells) + "</tr>")
    out += ["</tbody>", "</table>", "</div>"]
    return "\n".join(out)


def nodata_block():
    return '<p class="nodata">no data</p>'


NODATA_INLINE = '<span class="nodata">no data</span>'
NODATA_MARK = (
    '<span class="g" role="img" aria-label="no data">∅</span> <span class="w">no data</span>'
)


def glyph(state):
    mark, word = STATE_INFO[state]
    return f'<span class="g" role="img" aria-label="{esc(word)}">{esc(mark)}</span>'


def marker_text(cell):
    """``[unverified: <reason>; settles by <settles_by>]`` from a cell's marker and settles_by."""
    settles = clean(cell.get("settles_by")).strip() or "re-extraction"
    marker = clean(cell.get("marker")).strip()
    if marker.startswith("[unverified") and marker.endswith("]"):
        return marker
    reason = marker or "no verified evidence record"
    return f"[unverified: {reason}; settles by {settles}]"


def state_mark(item, with_marker=False):
    word = STATE_INFO[item["state"]][1]
    out = f'{glyph(item["state"])} <span class="w">{esc(word)}</span>'
    if item["verification"] == "unverified":
        out += (
            ' <span class="uv" role="img" aria-label="unverified">!</span>'
            ' <span class="w">unverified</span>'
        )
        if with_marker:
            out += f' <span class="marker">{esc(marker_text(item))}</span>'
    return out


def legend_items():
    return "".join(
        f'<li>{glyph(sid)} <span class="w">{esc(word)}</span></li>' for sid, _, word, _ in STATES
    )


def ext_link(url, atlas):
    if safe_external(url, atlas.hosts):
        return f'<a href="{esc(url)}">{esc(url)}</a>'
    return f'<span class="mono">{esc(url)}</span>'


def evidence_link(eid, atlas, page):
    record = atlas.evidence.get(eid)
    if record is None or record.get("surface") not in atlas.surface:
        return f'<span class="mono">{esc(eid)}</span> <span class="nodata">(no record)</span>'
    target = f"sources/{record['surface']}.html"
    return f'<a class="mono" href="{href(page, target, clean(eid))}">{esc(eid)}</a>'


def citation_line(record, atlas):
    version = record.get("product_version")
    parts = [
        f"Source: {ext_link(record.get('url'), atlas)}",
        f"retrieved {time_html(record.get('retrieved'))}",
        "version " + (esc(version) if version else "not recorded"),
        f"tier {esc(record.get('tier'))}",
    ]
    return '<p class="cite">' + "; ".join(parts) + "</p>"


def locator_text(record):
    loc = record.get("locator") if isinstance(record.get("locator"), dict) else {}
    lines = f"raw lines {loc.get('raw_line_start')}-{loc.get('raw_line_end')}"
    return f"{loc['heading']}, {lines}" if loc.get("heading") else lines


def span_note(record):
    span = record.get("described_span")
    if not isinstance(span, dict):
        return None
    lines = f"raw lines {span.get('raw_line_start')}-{span.get('raw_line_end')}"
    return f"Described span: {clean(span.get('description'))} ({lines})"


def split_refs(refs, limit=MAX_HARNESS_QUOTES):
    """The refs a harness page quotes, and the rest it leaves to the sources page.

    Within the budget the order is kept. Past it, the role-labelled records (the vendor statement,
    the reference page, the positive quote) are the ones the cell rests on, so they are kept first.
    """
    if len(refs) <= limit:
        return refs, []
    ranked = sorted(refs, key=lambda ref: ref[0] is None)
    return ranked[:limit], ranked[limit:]


def evidence_block(eid, role, atlas, page):
    record = atlas.evidence.get(eid)
    label = f"<strong>{esc(role)}:</strong> " if role else ""
    if record is None:
        return f"<li>{label}{evidence_link(eid, atlas, page)}</li>"
    quote_text = clean(record.get("quote"))
    note = span_note(record)
    if quote_text:
        body = f"<blockquote><p>{esc(quote_text)}</p></blockquote>"
    elif note:
        body = f"<p>{esc(note)}</p>"
    else:
        body = nodata_block()
    cite = citation_line(record, atlas)
    return f"<li>{label}{evidence_link(eid, atlas, page)}{body}{cite}</li>"


def lever_parts(lever, atlas, page):
    values = [f"<code>{esc(v)}</code>" for v in as_list(lever.get("values"))]
    by_model = lever.get("values_by_model")
    if isinstance(by_model, dict):
        for model in sorted(by_model):
            joined = ", ".join(f"<code>{esc(v)}</code>" for v in as_list(by_model[model]))
            values.append(f"{esc(model)}: {joined}")
    unread = [f"<code>{esc(m)}</code> [unverified]" for m in as_list(lever.get("unread_models"))]
    citations = [evidence_link(e, atlas, page) for e in as_list(lever.get("evidence"))]
    literal = lever.get("literal")
    default = lever.get("default")
    model = lever.get("model")
    return {
        "row": f"<code>{esc(lever.get('row'))}</code>",
        "kind": f"<code>{esc(lever.get('location_kind'))}</code>",
        "literal": f"<code>{esc(literal)}</code>" if literal else NODATA_INLINE,
        "scope": esc(lever.get("scope")) if lever.get("scope") else NODATA_INLINE,
        "values": "<br>".join(values + unread) if values or unread else NODATA_INLINE,
        "default": f"<code>{esc(default)}</code>" if default else NODATA_INLINE,
        "model": esc(model) if model else "all",
        "state": state_mark(lever),
        "citation": "<br>".join(citations) if citations else NODATA_INLINE,
    }


# --- pages -----------------------------------------------------------------------------------


def document(page, title, h1, body):
    """Wrap a page body: doctype, generated marker, CSP, nav, skip link, optional age script."""
    script = ""
    csp_script = ""
    if "<time " in body:
        digest = base64.b64encode(bytes.fromhex(sha256_bytes(AGE_SCRIPT.encode("utf-8"))))
        csp_script = f"script-src 'sha256-{digest.decode('ascii')}'; "
        script = f"<script>{AGE_SCRIPT}</script>\n"
    csp = (
        "default-src 'none'; style-src 'unsafe-inline'; "
        f"{csp_script}img-src data:; base-uri 'none'; form-action 'none'"
    )
    nav = "".join(
        f'<li><a href="{href(page, dst)}"'
        + (' aria-current="page"' if dst == page else "")
        + f">{esc(label)}</a></li>"
        for dst, label in NAV
    )
    return (
        "\n".join(
            [
                "<!DOCTYPE html>",
                GENERATED,
                '<html lang="en">',
                "<head>",
                '<meta charset="utf-8">',
                f'<meta http-equiv="Content-Security-Policy" content="{csp}">',
                '<meta name="viewport" content="width=device-width, initial-scale=1">',
                '<meta name="color-scheme" content="light dark">',
                f"<title>{esc(title if title == ATLAS_TITLE else f'{title} | {ATLAS_TITLE}')}</title>",
                f"<style>{CSS}</style>",
                "</head>",
                "<body>",
                '<a class="skip" href="#main">Skip to content</a>',
                f'<header><nav aria-label="Atlas pages"><ul>{nav}</ul></nav></header>',
                '<main id="main">',
                f"<h1>{esc(h1)}</h1>",
                body,
                "</main>",
                script + "</body>",
                "</html>",
            ]
        )
        + "\n"
    )


def matrix_cell(atlas, sid, row_id, page):
    cell = atlas.cells.get((sid, row_id))
    target = href(page, atlas.harness_path(sid), f"{sid}/{row_id}")
    if cell is None:
        return "s-nodata", f'<a href="{target}">{NODATA_MARK}</a>'
    inner = state_mark(cell)
    value = clean(cell.get("value"))
    if value:
        inner += f' <span class="val" title="{esc(value)}">{esc(clip(value))}</span>'
    inner += f'<span class="ev">evidence: {len(as_list(cell.get("evidence")))}</span>'
    return f"s-{cell['state']}", f'<a href="{target}">{inner}</a>'


def render_matrix(atlas):
    page = "matrix.html"
    body = [f'<ul class="cols">{legend_items()}</ul>', '<ul class="cols">']
    for facet in atlas.facets:
        label = f"{facet.get('id')} {facet.get('name')}"
        body.append(f'<li><a href="#{esc(clean(facet.get("id")))}">{esc(label)}</a></li>')
    body.append("</ul>")
    for facet in atlas.facets:
        label = f"{facet.get('id')} {facet.get('name')}"
        body.append(f'<section id="{esc(facet.get("id"))}">')
        body.append(heading(2, label))
        head = [th("Row")] + [
            th(local_link(page, atlas.harness_path(s["id"]), atlas.surface_name(s["id"])))
            for s in atlas.surfaces
        ]
        rows = []
        for row in as_list(facet.get("rows")):
            row_id = row.get("id")
            cells = [th(f"{esc(row.get('label'))}<br><code>{esc(row_id)}</code>", "row")]
            for sid in atlas.surface_ids:
                cls, inner = matrix_cell(atlas, sid, row_id, page)
                cells.append(td(inner, cls))
            rows.append((row_id, cells))
        body.append(table(label, head, rows, "matrix") if rows else nodata_block())
        body.append("</section>")
    return document(page, "Matrix", "Matrix by facet and row", "\n".join(body))


def lever_line(lever, atlas, page):
    parts = lever_parts(lever, atlas, page)
    bits = [
        f"{parts['kind']} {parts['literal']}",
        f"scope: {parts['scope']}",
        f"values: {parts['values']}",
        f"default: {parts['default']}",
        f"model: {parts['model']}",
        parts["state"],
    ]
    if lever.get("evidence"):
        bits.append(f"citation: {parts['citation']}")
    return "<li>" + "; ".join(bits) + "</li>"


def sweep_text(report):
    terms = ", ".join(clean(t) for t in as_list(report.get("terms")))
    return (
        f"Sweep: terms {terms}; hits {clean(report.get('hits'))}, "
        f"reviewed {clean(report.get('hits_reviewed'))}; positive control "
        f"{clean(report.get('positive_control_term'))} "
        f"({clean(report.get('positive_control_hits'))} hits); "
        f"corpus sha256 {clean(report.get('corpus_sha256'))}"
    )


def cell_evidence_refs(cell):
    seen = []
    refs = [(None, e) for e in as_list(cell.get("evidence"))]
    refs += [(label, cell.get(key)) for key, label in EVIDENCE_ROLES if cell.get(key)]
    out = []
    for role, eid in refs:
        if eid not in seen:
            seen.append(eid)
            out.append((role, eid))
    return out


def harness_cell(atlas, sid, row_id, page, show_name):
    cell = atlas.cells.get((sid, row_id))
    cell_id = f"{sid}/{row_id}"
    cls = f"s-{cell['state']}" if cell else "s-nodata"
    out = [f'<div class="cell {cls}" id="{esc(clean(cell_id))}">']
    if show_name:
        out.append(heading(4, atlas.surface_name(sid)))
    if cell is None:
        out.append(f'<p class="st">{NODATA_MARK}</p>')
    else:
        out.append(f'<p class="st">{state_mark(cell, with_marker=True)}</p>')
        if cell.get("value"):
            out.append(f"<p><strong>Value:</strong> {esc(cell.get('value'))}</p>")
        if cell.get("limitation"):
            out.append(f"<p><strong>Limitation:</strong> {esc(cell.get('limitation'))}</p>")
        scope = [clean(s) for s in as_list(cell.get("surface_scope"))]
        if scope:
            out.append(f"<p><strong>Scope:</strong> {esc(', '.join(scope))}</p>")
        if cell.get("drifted"):
            out.append('<p><strong>Drifted:</strong> <span class="w">drifted</span></p>')
        if isinstance(cell.get("sweep_report"), dict):
            out.append(f'<p class="muted">{esc(sweep_text(cell["sweep_report"]))}</p>')
        shown, hidden = split_refs(cell_evidence_refs(cell))
        if shown:
            items = "".join(evidence_block(e, r, atlas, page) for r, e in shown)
            if hidden:
                more = local_link(
                    page, f"sources/{sid}.html", f"{len(hidden)} more on the sources page", cell_id
                )
                items += f"<li>{more}</li>"
            out.append(f"<p><strong>Evidence:</strong></p><ul>{items}</ul>")
    levers = atlas.levers_by_cell.get((sid, row_id), [])
    if levers:
        out.append("<p><strong>Lever locations:</strong></p>")
        out.append("<ul>" + "".join(lever_line(lv, atlas, page) for lv in levers) + "</ul>")
    entries = atlas.register_by_cell.get(cell_id, [])
    if entries:
        items = "".join(
            f"<li>{local_link(page, 'register.html', clean(e.get('id')), clean(e.get('id')))} "
            f"{esc(e.get('title'))} ({esc(e.get('type'))})</li>"
            for e in entries
        )
        out.append(f"<p><strong>Register entries:</strong></p><ul>{items}</ul>")
    else:
        out.append('<p class="muted"><strong>Register entries:</strong> none cite this cell.</p>')
    out.append("</div>")
    return "\n".join(out)


def render_harness(atlas, pid):
    page = f"harness/{pid}.html"
    surfaces = atlas.product_surfaces[pid]
    name = atlas.product_name(pid)
    facets = [f for f in atlas.facets if f.get("id") == "F21"]
    facets += [f for f in atlas.facets if f.get("id") != "F21"]
    body = []
    head = [th("Column"), th("Version"), th("Version source"), th("Retrieved"), th("Sources")]
    rows = []
    for s in surfaces:
        col = atlas.columns.get(s["id"])
        if col is None:
            cells = [td(NODATA_INLINE)] * 3
        else:
            cells = [
                td(esc(col.get("version")) if col.get("version") else "not recorded"),
                td(esc(col.get("version_source")) if col.get("version_source") else "not recorded"),
                td(time_html(col.get("retrieved"))),
            ]
        link = local_link(page, f"sources/{s['id']}.html", "Source records")
        rows.append((None, [th(esc(atlas.surface_name(s["id"])), "row"), *cells, td(link)]))
    body.append(table(f"{name}: columns", head, rows))
    body.append('<ul class="cols">')
    for facet in facets:
        label = f"{facet.get('id')} {facet.get('name')}"
        body.append(f'<li><a href="#{esc(clean(facet.get("id")))}">{esc(label)}</a></li>')
    body.append("</ul>")
    for facet in facets:
        body.append(f'<section id="{esc(facet.get("id"))}">')
        body.append(heading(2, f"{facet.get('id')} {facet.get('name')}"))
        for row in as_list(facet.get("rows")):
            row_id = row.get("id")
            body.append(f'<div id="{esc(row_id)}">')
            body.append(heading(3, row.get("label")))
            body.append(
                f'<p class="muted"><code>{esc(row_id)}</code> {esc(row.get("definition"))}</p>'
            )
            for s in surfaces:
                body.append(harness_cell(atlas, s["id"], row_id, page, len(surfaces) > 1))
            body.append("</div>")
        if not as_list(facet.get("rows")):
            body.append(nodata_block())
        body.append("</section>")
    return document(page, name, name, "\n".join(body))


def render_levers(atlas):
    page = "levers.html"
    title = "Lever guide: documented controls, editorial routing"
    intro = [f"<p>{esc(LEVER_GUIDE_INTRO)}</p>"]
    body = []
    by_surface = {}
    for index, lever in enumerate(atlas.levers):
        by_surface.setdefault(lever.get("surface"), []).append((index, lever))
    for sid in ordered(atlas.surface_ids, [s for s in by_surface if s is not None]):
        name = atlas.surface_name(sid)
        body.append(heading(2, name))
        groups = {}
        for index, lever in by_surface[sid]:
            groups.setdefault(lever.get("lever"), []).append((index, lever))
        for klass in ordered(atlas.lever_classes, [k for k in groups if k is not None]):
            body.append(heading(3, f"{name}: {klass}"))
            head = [th(c) for c in ("Row", "Location", "Literal", "Scope", "Values")]
            head += [th(c) for c in ("Default", "Model", "State", "Citation")]
            rows = []
            for index, lever in groups[klass]:
                parts = lever_parts(lever, atlas, page)
                cells = [td(parts[k]) for k in ("row", "kind", "literal", "scope", "values")]
                cells += [td(parts[k]) for k in ("default", "model", "state", "citation")]
                rows.append((f"lever-{index}", cells))
            body.append(table(f"{name}: {klass} lever locations", head, rows, "levers"))
    if not atlas.levers:
        body.append(nodata_block())
    split = len(body)
    body.append(heading(2, "Task-shape rows"))
    tasks = sorted(
        atlas.task_rows,
        key=lambda t: (
            atlas.surface_ids.index(t.get("surface"))
            if t.get("surface") in atlas.surface
            else len(atlas.surface_ids)
        ),
    )
    matrix_sha = atlas.snapshot.get("matrix_sha")
    rows = []
    for task in tasks:
        pointer = task.get("pointer")
        if isinstance(pointer, dict):
            sha = f"<code>{esc(matrix_sha)}</code>" if matrix_sha else NODATA_INLINE
            where = (
                f"file <code>{esc(pointer.get('file'))}</code>, path "
                f"<code>{esc(pointer.get('path'))}</code>, matrix_sha {sha}"
            )
        elif task.get("pending_label"):
            where = esc(task.get("pending_label"))
        else:
            where = NODATA_INLINE
        basis = esc(task.get("basis")) if task.get("basis") else NODATA_INLINE
        if task.get("basis") != "capability-fact" and (task.get("basis") or isinstance(pointer, dict)):
            basis += ' <span class="badge">judgment, not measured</span>'
        refs = []
        for ref in as_list(task.get("lever_settings")):
            key = ref_key(ref)
            anchor = atlas.lever_anchor.get(key)
            parts = str(ref).split("|")
            label = esc(parts[1]) if len(parts) == 3 else esc(ref)
            text = f'<a href="{href(page, page, anchor)}">{label}</a>' if anchor else label
            literals = atlas.lever_literals.get(key, [])[:3]
            if literals:
                text += ": " + ", ".join(f"<code>{esc(lit)}</code>" for lit in literals)
            refs.append(text)
        mode = " / ".join(esc(task[k]) for k in ("interaction_mode", "blast_radius") if task.get(k))
        tier = esc(task.get("tier")) if task.get("tier") else NODATA_INLINE
        if task.get("tier") and task.get("rank") is not None:
            tier += f" (rank {esc(task.get('rank'))})"
        if task.get("agent"):
            tier += f"<br>{esc(task.get('agent'))}"
        sid = task.get("surface")
        cells = [
            th(esc(atlas.surface_name(sid)) if sid else NODATA_INLINE, "row"),
            td(esc(task.get("task_class"))),
            td(mode if mode else NODATA_INLINE),
            td(tier),
            td(where),
            td(basis),
            td("<br>".join(refs) if refs else NODATA_INLINE),
        ]
        rows.append((None, cells))
    head = [th(c) for c in ("Surface", "Task class", "Mode / blast radius", "Matrix tier")]
    head += [th(c) for c in ("Matrix pointer or pending", "Basis")]
    head.append(th("Lever settings"))
    body.append(table("Task-shape rows", head, rows, "tasks") if rows else nodata_block())
    # the answer to "what do I set for this task" comes first; the per-column reference follows
    body = intro + body[split:] + [heading(2, "Lever locations by column")] + body[:split]
    return document(page, title, title, "\n".join(body))


def cell_link(atlas, cell_id, page):
    sid, _, tail = str(cell_id).partition("/")
    text = f"<code>{esc(cell_id)}</code>"
    if sid not in atlas.surface:
        return text
    if tail == "U00" or tail.startswith("U00/"):
        return f'<a href="{href(page, f"sources/{sid}.html", clean(cell_id))}">{text}</a>'
    if tail in atlas.rows:
        return f'<a href="{href(page, atlas.harness_path(sid), clean(cell_id))}">{text}</a>'
    return text


def repo_file(item):
    path = clean(item.get("path")) if isinstance(item, dict) else clean(item)
    if isinstance(item, dict) and item.get("exists") and ".." not in path.split("/"):
        url = REPO_BLOB_BASE + quote(path, safe="/")
        return f'<a href="{esc(url)}"><code>{esc(path)}</code></a>'
    return f'<code>{esc(path)}</code> <span class="nodata">(not in repo)</span>'


def render_register(atlas):
    page = "register.html"
    head = [th(c) for c in ("Rank", "Entry", "Type", "Surfaces", "Score", "Status", "Rationale")]
    head.append(th("Cells and repo files"))
    rows = []
    for entry in atlas.register:
        surfaces = []
        for sid in as_list(entry.get("surfaces")):
            if sid in atlas.surface:
                surfaces.append(local_link(page, atlas.harness_path(sid), sid))
            else:
                surfaces.append(esc(sid))
        basis = entry.get("basis") if isinstance(entry.get("basis"), dict) else {}
        title = f"<strong>{esc(entry.get('title'))}</strong>"
        if entry.get("proposal"):
            title += f"<br>{esc(entry.get('proposal'))}"
        if basis.get("kind"):
            falsified = (
                f" (falsified by: {esc(basis['falsified_by'])})"
                if basis.get("falsified_by")
                else ""
            )
            title += f"<br>basis: {esc(basis.get('kind'))}{falsified}"
        links = [cell_link(atlas, c, page) for c in as_list(entry.get("cells"))]
        links += [repo_file(f) for f in as_list(entry.get("repo_files"))]
        score = entry.get("score")
        cells = [
            td(esc(entry.get("rank")) if entry.get("rank") is not None else NODATA_INLINE),
            th(f'<span class="mono">{esc(entry.get("id"))}</span><br>{title}', "row"),
            td(esc(entry.get("type"))),
            td(", ".join(surfaces) if surfaces else NODATA_INLINE),
            td(esc(score) if score is not None else NODATA_INLINE),
            td(esc(entry.get("status"))),
            td(esc(entry.get("rationale")) if entry.get("rationale") else NODATA_INLINE),
            td("<br>".join(links) if links else NODATA_INLINE),
        ]
        rows.append((clean(entry.get("id")), cells))
    body = table("Enhancement register by rank", head, rows, "register") if rows else nodata_block()
    return document(page, "Register", "Enhancement register", body)


def evidence_row(record, atlas):
    quote_text = clean(record.get("quote"))
    note = span_note(record)
    verified = record.get("quote_verified")
    text = esc(quote_text) if quote_text else (esc(note) if note else NODATA_INLINE)
    return (
        clean(record.get("id")),
        [
            th(f'<span class="mono">{esc(record.get("id"))}</span>', "row"),
            td(esc(record.get("tier"))),
            td(ext_link(record.get("url"), atlas)),
            td(time_html(record.get("retrieved"))),
            td(
                esc(record.get("product_version"))
                if record.get("product_version")
                else "not recorded"
            ),
            td(f"<code>{esc(record.get('sha256'))}</code>"),
            td(esc(locator_text(record))),
            td("yes" if verified is True else "no" if verified is False else "not checked"),
            td(text),
        ],
    )


def cells_over_budget(atlas, sid, page):
    """Anchored list of the cells whose harness page quotes only some of their records."""
    items = []
    for (cell_sid, row_id), cell in atlas.cells.items():
        refs = cell_evidence_refs(cell)
        if cell_sid != sid or len(refs) <= MAX_HARNESS_QUOTES:
            continue
        cell_id = clean(f"{sid}/{row_id}")
        cited = ", ".join(
            (f"{esc(role)}: " if role else "") + evidence_link(eid, atlas, page)
            for role, eid in refs
        )
        items.append(
            f'<li id="{esc(cell_id)}"><span class="mono">{esc(cell_id)}</span>: {cited}</li>'
        )
    return "<ul>" + "".join(items) + "</ul>" if items else ""


def render_sources(atlas, sid):
    page = f"sources/{sid}.html"
    name = atlas.surface_name(sid)
    body = [heading(2, "Evidence records")]
    records = atlas.evidence_by_surface.get(sid, [])
    head = [th(c) for c in ("Id", "Tier", "Link", "Retrieved", "Version", "SHA-256")]
    head += [th(c) for c in ("Locator", "Quote verified", "Quote or described span")]
    if records:
        body.append(table(f"{name}: evidence", head, [evidence_row(r, atlas) for r in records]))
    else:
        body.append(nodata_block())
    over_budget = cells_over_budget(atlas, sid, page)
    if over_budget:
        body.append(heading(2, "Cells with more records than their harness page quotes"))
        body.append(over_budget)
    coverage = atlas.snapshot.get("coverage")
    coverage = coverage.get(sid) if isinstance(coverage, dict) else None
    body.append(heading(2, "Coverage"))
    if isinstance(coverage, dict) and coverage:
        rows = [(None, [th(esc(k), "row"), td(esc(coverage[k]))]) for k in sorted(coverage)]
        body.append(table(f"{name}: coverage", [th("Measure"), th("Value")], rows))
    else:
        body.append(nodata_block())
    body.append(heading(2, "Unmapped records (U00)"))
    unmapped = atlas.unmapped.get(sid, [])
    if unmapped:
        items = []
        for cell in unmapped:
            refs = cell_evidence_refs(cell)
            quotes = "".join(evidence_block(e, r, atlas, page) for r, e in refs)
            value = f"<p>{esc(cell.get('value'))}</p>" if cell.get("value") else ""
            items.append(
                f'<li id="{esc(cell.get("id"))}"><span class="mono">{esc(cell.get("id"))}</span> '
                f"{state_mark(cell, with_marker=True)}{value}<ul>{quotes}</ul></li>"
            )
        body.append("<ul>" + "".join(items) + "</ul>")
    else:
        body.append(nodata_block())
    return document(page, f"{name}: sources", f"{name}: sources", "\n".join(body))


def gap_list(atlas):
    gaps = as_list(atlas.snapshot.get("known_gaps"))
    if not gaps:
        return nodata_block()
    return "<ul>" + "".join(f"<li>{esc(g)}</li>" for g in gaps) + "</ul>"


def success_signal(atlas):
    total = len(atlas.surfaces)
    backed = {
        t.get("surface")
        for t in atlas.task_rows
        if isinstance(t.get("pointer"), dict) and t.get("surface") in atlas.surface
    }
    pending = [sid for sid in atlas.surface_ids if sid not in backed]
    if not atlas.snapshot.get("matrix_pending") and not pending:
        return f"{total} of {total} columns have matrix-backed lever guidance"
    names = ", ".join(clean(p) for p in pending) if pending else "none"
    return f"{total - len(pending)} of {total} (flagged: matrix rows pending for {names})"


def count_row(atlas, sid, page):
    counts = {state: 0 for state, _, _, _ in STATES}
    verification = {"verified": 0, "unverified": 0}
    missing = 0
    for row_id in atlas.row_ids:
        cell = atlas.cells.get((sid, row_id))
        if cell is None:
            missing += 1
            continue
        counts[cell["state"]] += 1
        verification[cell["verification"]] += 1
    numbers = [counts[state] for state, _, _, _ in STATES]
    numbers += [missing, verification["verified"], verification["unverified"]]
    numbers.append(len(atlas.unmapped.get(sid, [])))
    name = local_link(page, atlas.harness_path(sid), atlas.surface_name(sid))
    return (None, [th(name, "row")] + [td(str(n)) for n in numbers])


def render_index(atlas):
    page = "index.html"
    snap = atlas.snapshot
    body = []
    if snap.get("freeze_start") or snap.get("freeze_end"):
        window = f"{esc(snap.get('freeze_start'))} to {esc(snap.get('freeze_end'))}"
        body.append(f"<p><strong>Freeze window:</strong> {window}</p>")
    head = [th(c) for c in ("Column", "Id", "Version", "Version source", "Retrieved")]
    rows = []
    for s in atlas.surfaces:
        col = atlas.columns.get(s["id"])
        if col is None:
            cells = [td(NODATA_INLINE)] * 3
        else:
            cells = [
                td(esc(col.get("version")) if col.get("version") else "not recorded"),
                td(esc(col.get("version_source")) if col.get("version_source") else "not recorded"),
                td(time_html(col.get("retrieved"))),
            ]
        name = local_link(page, atlas.harness_path(s["id"]), atlas.surface_name(s["id"]))
        rows.append((None, [th(name, "row"), td(f"<code>{esc(s['id'])}</code>"), *cells]))
    body.append(table("Columns and snapshot", head, rows))
    body.append(
        f'<p class="signal"><strong>Success signal:</strong> {esc(success_signal(atlas))}</p>'
    )
    body.append(heading(2, "How to read"))
    legend = [(None, [td(glyph(s)), td(esc(w)), td(esc(m))]) for s, _, w, m in STATES]
    body.append(table("States", [th("Glyph"), th("State"), th("Meaning")], legend))
    tiers = "".join(f"<li><strong>{esc(t)}</strong> {esc(m)}</li>" for t, m in TIERS)
    body.append(f"<p><strong>Evidence tiers:</strong></p><ul>{tiers}</ul>")
    body.append(
        '<p><strong>Unverified marker:</strong> <span class="uv" role="img" '
        'aria-label="unverified">!</span> <span class="w">unverified</span> '
        '<span class="marker">[unverified: &lt;reason&gt;; settles by &lt;probe&gt;]</span></p>'
    )
    body.append(heading(2, "Cells by state and verification"))
    head = [th("Column")] + [th(w) for _, _, w, _ in STATES]
    head += [th(c) for c in ("no data", "verified", "unverified", "U00 records")]
    body.append(
        table(
            "Cell counts per column", head, [count_row(atlas, s, page) for s in atlas.surface_ids]
        )
    )
    body.append(heading(2, "Top of the register"))
    top = atlas.register[:10]
    if top:
        rows = []
        for e in top:
            eid = clean(e.get("id"))
            cells = [
                td(esc(e.get("rank")) if e.get("rank") is not None else NODATA_INLINE),
                td(local_link(page, "register.html", eid, eid)),
                td(esc(e.get("title"))),
                td(esc(e.get("type"))),
                td(esc(e.get("status"))),
            ]
            rows.append((None, cells))
        head = [th(c) for c in ("Rank", "Entry", "Title", "Type", "Status")]
        body.append(table("Top 10 register entries by rank", head, rows))
    else:
        body.append(nodata_block())
    body.append(heading(2, "Known gaps"))
    body.append(gap_list(atlas))
    body.append(heading(2, "Pages"))
    harness = "".join(
        f"<li>{local_link(page, f'harness/{p}.html', atlas.product_name(p))}</li>"
        for p in atlas.products
    )
    sources = "".join(
        f"<li>{local_link(page, f'sources/{s}.html', atlas.surface_name(s))}</li>"
        for s in atlas.surface_ids
    )
    body.append(f'<p><strong>Harness pages:</strong></p><ul class="cols">{harness}</ul>')
    body.append(f'<p><strong>Source pages:</strong></p><ul class="cols">{sources}</ul>')
    return document(page, ATLAS_TITLE, ATLAS_TITLE, "\n".join(body))


def render_method(atlas):
    page = "method.html"
    body = [heading(2, "States")]
    rows = [(None, [td(glyph(s)), td(esc(w)), td(esc(m))]) for s, _, w, m in STATES]
    body.append(table("States", [th("Glyph"), th("State"), th("Meaning")], rows))
    body.append(heading(2, "Evidence tiers"))
    rows = [(None, [th(esc(t), "row"), td(esc(m))]) for t, m in TIERS]
    body.append(table("Evidence tiers", [th("Tier"), th("Source")], rows))
    body.append(heading(2, "Verification"))
    verification = as_dict(atlas.snapshot.get("verification"))
    if verification:
        rows = [(None, [th(esc(k), "row"), td(esc(verification[k]))]) for k in sorted(verification)]
        body.append(table("Verification numbers", [th("Measure"), th("Value")], rows))
    else:
        body.append(nodata_block())
    body.append(heading(2, "Grok Bot"))
    body.append(f"<p>{esc(GROK_BOT_NOTE)}</p>")
    if "grok-bot" in atlas.surface:
        row_link = local_link(
            page,
            "harness/grok-bot.html",
            "Grok Bot, F21.shared-agent-runtime",
            "grok-bot/F21.shared-agent-runtime",
        )
        body.append(f"<p>{row_link}</p>")
    body.append(heading(2, "Known gaps"))
    body.append(gap_list(atlas))
    return document(page, "Method", "Method", "\n".join(body))


def render_all(data_dir):
    """Every page as {relative path: text}, in a fixed order."""
    atlas = Atlas(data_dir)
    pages = {"index.html": render_index(atlas), "matrix.html": render_matrix(atlas)}
    for pid in atlas.products:
        pages[f"harness/{pid}.html"] = render_harness(atlas, pid)
    pages["levers.html"] = render_levers(atlas)
    pages["register.html"] = render_register(atlas)
    for sid in atlas.surface_ids:
        pages[f"sources/{sid}.html"] = render_sources(atlas, sid)
    pages["method.html"] = render_method(atlas)
    return pages


def encode_pages(pages):
    encoded = {}
    for path, text in pages.items():
        try:
            encoded[path] = text.encode("utf-8")
        except UnicodeEncodeError as exc:
            raise RenderError(f"{path} is not encodable as UTF-8: {exc}") from exc
    return encoded


def check_sizes(encoded):
    problems = [
        f"page {path} is {len(data)} bytes, over the {MAX_PAGE_BYTES} limit"
        for path, data in encoded.items()
        if len(data) > MAX_PAGE_BYTES
    ]
    total = sum(len(d) for d in encoded.values())
    if total > MAX_TOTAL_BYTES:
        problems.append(f"all pages together are {total} bytes, over the {MAX_TOTAL_BYTES} limit")
    if problems:
        raise RenderError("; ".join(problems))


def extra_pages(out, rendered):
    """``*.html`` files in the output folder, harness/ and sources/ that no page of ours maps to."""
    found = []
    for folder in ("", "harness", "sources"):
        directory = out / folder if folder else out
        if directory.is_dir():
            for path in sorted(directory.glob("*.html")):
                name = f"{folder}/{path.name}" if folder else path.name
                if name not in rendered and path.is_file():
                    found.append(name)
    return found


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--data-dir", default=str(DATA_DIR))
    parser.add_argument("--out", default=str(ATLAS_DIR))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if not args.check:  # --check only reads, so it also runs on main after the branch lands
        assert_worktree()
    try:
        encoded = encode_pages(render_all(args.data_dir))
        check_sizes(encoded)
    except RenderError as exc:
        print(f"render: {exc}", file=sys.stderr)
        return 2
    out = Path(args.out)
    extras = extra_pages(out, encoded)
    if args.check:
        bad = []
        for path, data in encoded.items():
            target = out / path
            if not target.is_file():
                bad.append(f"missing: {path}")
            elif target.read_bytes() != data:
                bad.append(f"stale: {path}")
        for line in bad:
            print(f"render: {line}", file=sys.stderr)
        for path in extras:
            print(f"render: extra: {path} is not a page the renderer writes", file=sys.stderr)
        if bad:
            print(f"render: {len(bad)} of {len(encoded)} pages out of date", file=sys.stderr)
        if extras:
            print(f"render: {len(extras)} extra page(s) in the output folder", file=sys.stderr)
        if bad or extras:
            return 1
        print(f"render: {len(encoded)} pages up to date")
        return 0
    for path, data in encoded.items():
        target = out / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
    print(f"render: wrote {len(encoded)} pages ({sum(len(d) for d in encoded.values())} bytes)")
    for path in extras:
        print(
            f"render: warning: extra page {path} is not written by the renderer; "
            "it was left in place, delete it or restore its data",
            file=sys.stderr,
        )
    return 1 if extras else 0


if __name__ == "__main__":
    sys.exit(main())
