"""Render data/row-list.md, the owner-readable view of data/facets.json.

The markdown is generated, never hand-edited: edit facets.json and re-run.
Usage: python3 rowlist.py [--check]
"""

import sys

from atlas_common import ATLAS_DIR, DATA_DIR, assert_worktree, load_json

OUT = DATA_DIR / "row-list.md"
COLUMNS = 8


def render(facets):
    rows = sum(len(f["rows"]) for f in facets["facets"])
    levers = sum(1 for f in facets["facets"] for r in f["rows"] if r["lever"])
    p5 = sum(1 for f in facets["facets"] for r in f["rows"] if r["slice"])
    out = [
        "<!-- Generated by _tools/rowlist.py from data/facets.json. Do not edit by hand. -->",
        "",
        "# Frozen row list: coding-agent harness atlas",
        "",
        f"{len(facets['facets'])} core facets, {rows} named rows, {rows * COLUMNS} cells "
        f"({COLUMNS} columns: claude-code, codex-cli, copilot-cli, copilot-vscode, cursor, "
        "gemini-cli, grok-build, grok-bot).",
        f"{levers} rows are lever rows (model, effort, mode, parallelism, other); "
        f"{p5} rows ({p5 * COLUMNS} cells) are researched first for the lever guide.",
        "",
        "A comparison claim (X has it, Y does not) is made only on a named row. A feature "
        "that fits no row is kept as an unmapped (U00) record with its quote; three or more "
        "U00 records across two or more columns come back to you as an Update item.",
        "",
    ]
    for f in facets["facets"]:
        out.append(f"## {f['id']} {f['name']}")
        out.append("")
        out.append(f"{f['definition']}")
        out.append("")
        out.append("| row id | row | what it records | lever | first |")
        out.append("|---|---|---|---|---|")
        for r in f["rows"]:
            out.append(
                f"| `{r['id']}` | {r['label']} | {r['definition']} | "
                f"{r['lever'] or ''} | {'yes' if r['slice'] else ''} |"
            )
        out.append("")
    out.append("## Optional and unmapped")
    out.append("")
    for o in facets["optional_facets"]:
        out.append(f"- `{o['id']}` {o['name']}: {o['definition']}")
    u = facets["unmapped"]
    out.append(f"- `{u['id']}` {u['name']}: {u['definition']}")
    out.append("")
    return "\n".join(out)


def main():
    assert_worktree()
    text = render(load_json(DATA_DIR / "facets.json"))
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            sys.exit(f"{OUT.relative_to(ATLAS_DIR)} is stale; run rowlist.py")
        print("row-list.md is current")
        return
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ATLAS_DIR)}")


if __name__ == "__main__":
    main()
