#!/usr/bin/env python3
"""Resolve relative markdown links across docs and plugins; fail on broken targets.

Scans the root boundary docs (README.md, AGENTS.md, CLAUDE.md), docs/**/*.md, and
plugins/**/*.md for inline markdown links `[text](target)`. For every link whose
target is a *relative or repo-absolute path* (not an external URL, a bare #anchor,
or an angle-bracket <placeholder>), it resolves the path and fails if the target
file or directory does not exist.

Skips:
  - external schemes: http://, https://, mailto:, tel:, ftp(s)://, data:
  - protocol-relative URLs (//host/...)
  - in-page anchors: targets starting with '#'
  - angle-bracket placeholders: targets containing '<' or '>' (e.g. <git-sha>)
  - the generated copilot/ projection tree under plugins/*/ (regenerated from core,
    not hand-authored — its links are validated at the source)
  - fenced code blocks and inline code spans (illustrative, not real links)

For a target with an anchor suffix (path/to/file.md#section), only the path part
is resolved; the anchor fragment itself is not validated. Repo-absolute targets
(leading '/') resolve against the repository root.

This is the root-cause gate for the 2026-05 class of broken cross-plugin
CLAUDE.md skill links that shipped green. Exit 0 if all links resolve; exit 1
with a per-link report otherwise. Runs in CI (validate-marketplace.yml) and is
exercised bidirectionally by audit-gates.sh.
"""

import re
import sys
from pathlib import Path
from urllib.parse import unquote

ROOT = Path(__file__).resolve().parent.parent

LINK_RE = re.compile(r"\[(?:[^\]]*)\]\(([^)]+)\)")
FENCE_RE = re.compile(r"```.*?```", re.DOTALL)
INLINE_CODE_RE = re.compile(r"`[^`]*`")
EXTERNAL_SCHEME_RE = re.compile(r"^(?:[a-z][a-z0-9+.-]*:)?//", re.IGNORECASE)
KNOWN_SCHEME_RE = re.compile(
    r"^(?:https?|mailto|tel|ftps?|data|file):", re.IGNORECASE
)

failures = []


GENERATED_MARKERS = ("GENERATED by", "DO NOT EDIT")


def is_excluded(p: Path) -> bool:
    rel = p.relative_to(ROOT)
    # Generated projection tree.
    if any(part == "copilot" for part in rel.parts):
        return True
    # Template/example files carry illustrative placeholder links.
    if p.name.startswith("_"):
        return True
    # Generated markdown (links are written for a rewritten render base).
    # Read defensively: a non-UTF-8 or transiently-unreadable .md must not crash
    # the whole link gate with an uncaught UnicodeDecodeError/OSError — treat an
    # unreadable head as "not a generated file" and let normal link-checking run.
    try:
        head = p.read_text(encoding="utf-8", errors="ignore")[:400]
    except OSError:
        return False
    if any(marker in head for marker in GENERATED_MARKERS):
        return True
    return False


def iter_markdown_files():
    for name in ("README.md", "AGENTS.md", "CLAUDE.md", "GETTING_STARTED.md", "STRATEGY.md"):
        p = ROOT / name
        if p.is_file() and not is_excluded(p):
            yield p
    for base in ("docs", "plugins"):
        for p in sorted((ROOT / base).rglob("*.md")):
            if not is_excluded(p):
                yield p


def is_external(target: str) -> bool:
    return bool(KNOWN_SCHEME_RE.match(target) or EXTERNAL_SCHEME_RE.match(target))


def resolve_target(md_file: Path, raw: str) -> Path | None:
    """Return the filesystem path a link points at, or None if it should be skipped."""
    target = raw.strip()
    if not target or target.startswith("#"):
        return None
    if "<" in target or ">" in target:  # placeholder token, not a real path
        return None
    if is_external(target):
        return None

    # Drop a markdown title suffix:  (path "Title")  ->  path
    target = target.split()[0]
    # Drop the anchor fragment:  file.md#section  ->  file.md
    path_part = target.split("#", 1)[0]
    if not path_part:
        return None
    path_part = unquote(path_part)

    if path_part.startswith("/"):
        return (ROOT / path_part.lstrip("/")).resolve()
    return (md_file.parent / path_part).resolve()


def strip_code(text: str) -> str:
    text = FENCE_RE.sub("", text)
    return INLINE_CODE_RE.sub("", text)


def main() -> int:
    for md_file in iter_markdown_files():
        text = strip_code(md_file.read_text())
        for m in LINK_RE.finditer(text):
            resolved = resolve_target(md_file, m.group(1))
            if resolved is None:
                continue
            if not resolved.exists():
                rel = md_file.relative_to(ROOT)
                failures.append(f"{rel}: broken link -> '{m.group(1).strip()}'")

    if failures:
        print("Markdown link check FAILED:")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("Markdown link check passed: all relative links resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
