#!/usr/bin/env python3
"""Project canonical agents into Cursor custom subagents (.cursor/agents/*.md).

Sibling of generate-codex-agents.py. Source: plugins/ravenclaude-core/agents/*.md.
Each output file carries name, description, and the agent body; review-only agents
(those that get read-only sandbox on Codex) also get readonly: true — Cursor's
default is false and an omitted key grants write.

Usage:
    python3 scripts/generate-cursor-agents.py --out /path/to/project/.cursor/agents
    python3 scripts/generate-cursor-agents.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = REPO_ROOT / "plugins" / "ravenclaude-core"
AGENTS_DIR = CORE_DIR / "agents"
DEFAULT_OUT = REPO_ROOT / ".cursor" / "agents"

_FM_RE = re.compile(r"\A---\n(.*?)\n---\n?(.*)\Z", re.S)
_KV_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$")
_WRITE_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
_NAME_OK = re.compile(r"\A[A-Za-z0-9_-]{1,64}\Z")
_BUILTIN_CURSOR = frozenset({"explore", "bash", "browser"})


def split_frontmatter(text: str) -> tuple[str, str]:
    m = _FM_RE.match(text)
    return (m.group(1), m.group(2)) if m else ("", text)


def scalar(raw: str) -> str:
    s = raw.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def parse_agent(path: Path) -> dict:
    fm, body = split_frontmatter(path.read_text(encoding="utf-8"))
    name = description = model = ""
    tools: list[str] = []
    for line in fm.splitlines():
        kv = _KV_RE.match(line)
        if not kv:
            continue
        key, raw = kv.group(1), kv.group(2)
        if key == "name" and not name:
            name = scalar(raw)
        elif key == "description" and not description:
            description = scalar(raw)
        elif key == "model" and not model:
            model = scalar(raw).strip().lower()
        elif key == "tools" and not tools:
            tools = [t.strip() for t in scalar(raw).split(",") if t.strip()]
    return {
        "name": name or path.stem,
        "description": description,
        "tools": tools,
        "model": model,
        "body": body.strip(),
    }


def readonly_for(tools: list[str]) -> bool:
    if not tools or "*" in tools:
        return False
    return not any(t in _WRITE_TOOLS for t in tools)


def yaml_quote(value: str) -> str:
    if not value:
        return '""'
    if re.search(r'[:#\n"\']', value):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def build_agent_md(agent: dict) -> str:
    tier = agent.get("model") or ""
    header = (
        "<!-- GENERATED by scripts/generate-cursor-agents.py — do not edit by hand. -->\n"
        f"<!-- Source: plugins/ravenclaude-core/agents/{agent['name']}.md -->\n"
    )
    if tier and tier != "inherit":
        header += (
            f"<!-- Canonical model tier: {tier}. Cursor `model` defaults to inherit; "
            "pin in the UI if needed. -->\n"
        )
    lines = [
        "---",
        f"name: {agent['name']}",
        f"description: {yaml_quote(agent['description'])}",
    ]
    if readonly_for(agent["tools"]):
        lines.append("readonly: true")
    lines.extend(["---", ""])
    return header + "\n".join(lines) + agent["body"] + "\n"


def build_tree() -> dict[str, str]:
    tree: dict[str, str] = {}
    for path in sorted(AGENTS_DIR.glob("*.md")):
        agent = parse_agent(path)
        if not _NAME_OK.match(agent["name"]):
            raise ValueError(f"{path.name}: unsafe agent name {agent['name']!r}")
        if agent["name"].lower() in _BUILTIN_CURSOR:
            print(
                f"cursor-agents: warning: {agent['name']!r} collides with a built-in Cursor subagent name",
                file=sys.stderr,
            )
        tree[f"{agent['name']}.md"] = build_agent_md(agent)
    return tree


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    try:
        tree = build_tree()
    except ValueError as exc:
        print(f"cursor-agents: {exc}", file=sys.stderr)
        return 1
    if not tree:
        print("FATAL: no canonical agents found", file=sys.stderr)
        return 1

    out_dir: Path = args.out
    if args.check:
        stale = []
        existing = {p.name for p in out_dir.glob("*.md")} if out_dir.is_dir() else set()
        for rel, content in sorted(tree.items()):
            dest = out_dir / rel
            if not dest.is_file() or dest.read_text(encoding="utf-8") != content:
                stale.append(rel)
        for orphan in sorted(existing - set(tree)):
            stale.append(f"{orphan} (orphan)")
        if stale:
            for rel in stale:
                print(f"STALE: {out_dir}/{rel}", file=sys.stderr)
            return 1
        print(f"cursor agents fresh ({len(tree)} file(s))")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for rel, content in sorted(tree.items()):
        dest = out_dir / rel
        dest.write_text(content, encoding="utf-8")
        print(f"wrote {dest} ({len(content):,} bytes)")
    for orphan in sorted(p for p in out_dir.glob("*.md") if p.name not in tree):
        orphan.unlink()
        print(f"removed orphan {orphan}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
