#!/usr/bin/env python3
"""generate-concepts-doc.py — emit docs/concepts.md from the concept source.

The Learn-tab concepts (plugins/ravenclaude-core/knowledge/concepts/*.md, loaded
+ validated by concepts.py) are the single source of truth. This generator
projects them into a canonical Markdown reference at docs/concepts.md so the
"how it works" explanation has a readable, linkable, GitHub-rendered home that
never drifts from the dashboard's Learn tab — both read the same source.

The diagrams are emitted as ```mermaid source blocks (GitHub renders them
natively), not the pre-rendered SVGs — the SVGs exist for the offline dashboard.

Usage:
    generate-concepts-doc.py [--root DIR]          # (re)write docs/concepts.md
    generate-concepts-doc.py --check [--root DIR]  # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import concepts as concepts_mod  # noqa: E402

DOC_PATH = "docs/concepts.md"

_KIND_LABEL = {"platform-fact": "platform fact", "ravenclaude-built": "RavenClaude-built"}

_HEADER = """<!-- GENERATED by scripts/generate-concepts-doc.py from
     plugins/ravenclaude-core/knowledge/concepts/ — DO NOT EDIT BY HAND.
     Edit the concept source and re-run the generator. The dashboard's
     interactive "Learn" tab is built from the same source. -->

# How RavenClaude works — concept reference

A plain-language reference for the moving parts: the platform facts RavenClaude
builds on, and what it adds on top. Each concept below is mirrored — with
interactive diagrams, search, and live widgets — in the comfort-posture
dashboard's **Learn** tab (`/dashboard`).
"""


def build_doc(root: Path) -> str:
    concepts = concepts_mod.load_concepts(root)
    parts = [_HEADER]
    if not concepts:
        parts.append("\n_No concepts authored yet._\n")
        return "\n".join(parts)

    # group by category, preserving the registry (load_concepts) order
    groups: dict[str, list[dict]] = {}
    order: list[str] = []
    for c in concepts:
        if c["category"] not in groups:
            groups[c["category"]] = []
            order.append(c["category"])
        groups[c["category"]].append(c)

    titles = {c["id"]: c["title"] for c in concepts}

    for cat in order:
        parts.append(f"\n## {cat}\n")
        for c in groups[cat]:
            kind = _KIND_LABEL.get(c["kind"], c["kind"])
            parts.append(f"### {c['title']} · _{kind}_\n")
            parts.append(f"> {c['summary']}\n")
            parts.append(c["body_md"] + "\n")
            parts.append("```mermaid\n" + c["diagram"] + "\n```\n")
            refs = [titles[r] for r in c.get("see_also", []) if r in titles]
            if refs:
                parts.append("**See also:** " + " · ".join(refs) + "\n")
            sources = " · ".join(
                f"[{s['label']}]({s['url']})" for s in c.get("sources", [])
            )
            parts.append(f"**Sources:** {sources}\n")
            if c.get("last_verified"):
                parts.append(f"_Last verified: {c['last_verified']}_\n")
            parts.append("\n---\n")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repo root")
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/concepts.md is stale")
    args = ap.parse_args()
    root = Path(args.root).resolve()
    out_path = root / DOC_PATH

    try:
        doc = build_doc(root)
    except concepts_mod.ConceptError as exc:
        print(f"Cannot generate {DOC_PATH} — concept schema invalid:\n  ✗ {exc}")
        return 1

    if args.check:
        if not out_path.exists():
            print(f"{DOC_PATH} missing — run: scripts/generate-concepts-doc.py")
            return 1
        if out_path.read_text(encoding="utf-8") != doc:
            print(f"{DOC_PATH} is STALE — regenerate with: scripts/generate-concepts-doc.py")
            return 1
        print(f"{DOC_PATH} is fresh.")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(doc, encoding="utf-8")
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
