#!/usr/bin/env python3
"""generate-skill-index.py — one always-on skill that indexes every skill in the marketplace.

FORGE plan: .ravenclaude/runs/forge/dynamic-skill-context/plan.md, phase P0.

Every skill in every plugin is invisible to the agent the moment its plugin is
disabled — no error, no denial, just silence (this repo's own "silent-green
defect" pattern). This generator builds ONE small, always-on skill
(`skill-index`) whose description is a single line (so it survives the native
usage-frequency description budget per A2/A3 in the FORGE run's claims table)
and whose BODY (loaded only on invocation, never resident) is the complete
index: every skill's plugin, its description, and the exact command to
re-enable it.

X7 mitigation (critic-brief.md X7 / red-team.md RT-5.4): a never-invoked
skill's DESCRIPTION is the first thing Claude Code's native per-turn budget
drops, so `skill-index` may render name-only on a given turn. The fix is that
the NAME alone must carry the entire affordance — "skill-index" is
self-explanatory without its description — and this generator's own --check
gate proves the skill's PRESENCE (a census), never a description-text
inspection.

Usage:
    python3 scripts/generate-skill-index.py            # write the index
    python3 scripts/generate-skill-index.py --check     # 0 fresh, 2 stale, 1 could-not-run

Discovery is the canonical 5-segment shape `plugins/<plugin>/skills/<skill>/SKILL.md`
ONLY — deeper paths (e.g. a skill's own bundled template/example SKILL.md, such
as `authoring-org-skills/templates/examples/.../SKILL.md`) are teaching
material inside another skill's resource directory, not separately-invocable
skills, and are deliberately excluded.
"""

from __future__ import annotations

import argparse
import glob
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(
    REPO_ROOT, "plugins", "ravenclaude-core", "skills", "skill-index", "SKILL.md"
)
MARKETPLACE_NAME = "ravenclaude"
GENERATED_HEADER = (
    "<!-- GENERATED by scripts/generate-skill-index.py — do not edit by hand.\n"
    "     Run: python3 scripts/generate-skill-index.py\n"
    "     The --check freshness gate fails CI on drift. -->"
)

_FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.S)
_BLOCK_SCALARS = (">", "|", ">-", "|-", ">+", "|+")


def _parse_description(text: str, relpath: str) -> str:
    """Pull `description:` out of a SKILL.md's YAML frontmatter.

    Tolerant of a quoted scalar and of a `>`/`|` block scalar (both used in
    this marketplace) — folds a block scalar's continuation lines into one
    space-joined line. Not a strict YAML parser: this repo's frontmatter is
    hand-authored, not attacker-controlled, and only `description:` is read.
    """
    m = _FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError(f"{relpath}: no frontmatter block found")
    lines = m.group(1).splitlines()
    for i, line in enumerate(lines):
        if not line.startswith("description:"):
            continue
        rest = line[len("description:"):].strip()
        if rest in _BLOCK_SCALARS:
            block = []
            for cont in lines[i + 1:]:
                if cont.strip() == "":
                    continue
                if cont.startswith((" ", "\t")):
                    block.append(cont.strip())
                    continue
                break
            if not block:
                raise ValueError(f"{relpath}: empty block-scalar description")
            return " ".join(block).strip()
        if not rest:
            raise ValueError(f"{relpath}: empty description: field")
        return rest.strip('"').strip("'").strip()
    raise ValueError(f"{relpath}: no `description:` field in frontmatter")


def discover_skills() -> list:
    """Every plugin-shipped skill, canonical 5-segment path only."""
    pattern = os.path.join(REPO_ROOT, "plugins", "*", "skills", "*", "SKILL.md")
    entries = []
    for path in sorted(glob.glob(pattern)):
        rel = os.path.relpath(path, REPO_ROOT)
        parts = rel.split(os.sep)
        if len(parts) != 5:
            continue
        plugin, skill = parts[1], parts[3]
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        description = _parse_description(text, rel)
        entries.append({"plugin": plugin, "skill": skill, "description": description})
    return entries


def render(entries: list) -> str:
    plugin_count = len({e["plugin"] for e in entries})
    lines = [
        "---",
        "name: skill-index",
        "description: Look up any skill in the marketplace by name or topic, "
        "including a disabled one, and get its exact re-enable command. Reach "
        "for this when you suspect a skill exists for the current task but it "
        "is not in your listing.",
        "allowed-tools: Read",
        "---",
        "",
        GENERATED_HEADER,
        "",
        "# Skill: skill-index",
        "",
        "A complete, always-current index of every skill shipped by every RavenClaude "
        "plugin — including one whose plugin is currently disabled and therefore does "
        "not appear in your own skill listing this turn.",
        "",
        "## Why this exists",
        "",
        "A skill whose plugin is disabled is invisible to you: no error, no denial, "
        "just silence. If you suspect a skill exists for the task at hand but don't "
        "see it listed, invoke this skill and search the table below by name, plugin, "
        "or keyword before concluding no such skill exists.",
        "",
        "## Re-enabling a disabled skill",
        "",
        "Every entry below names its owning plugin. To bring a disabled plugin's "
        "skills back:",
        "",
        "```",
        f"/plugin enable <plugin>@{MARKETPLACE_NAME}",
        "/reload-plugins",
        "```",
        "",
        f"## Index ({len(entries)} skills across {plugin_count} plugins)",
        "",
        "| Skill | Plugin | Description |",
        "|---|---|---|",
    ]
    for e in sorted(entries, key=lambda e: (e["plugin"], e["skill"])):
        desc = e["description"].replace("|", "\\|")
        lines.append(f"| `{e['skill']}` | `{e['plugin']}` | {desc} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check", action="store_true", help="report drift and exit 2; write nothing"
    )
    args = parser.parse_args()

    try:
        entries = discover_skills()
    except ValueError as exc:
        print(f"generate-skill-index: COULD NOT RUN — {exc}", file=sys.stderr)
        return 1
    if not entries:
        print(
            "generate-skill-index: COULD NOT RUN — discovered zero skills (glob broken?)",
            file=sys.stderr,
        )
        return 1

    generated = render(entries)

    if args.check:
        if not os.path.isfile(OUTPUT_PATH):
            print(f"generate-skill-index: STALE — {OUTPUT_PATH} does not exist", file=sys.stderr)
            return 2
        with open(OUTPUT_PATH, encoding="utf-8") as fh:
            committed = fh.read()
        if committed != generated:
            print(
                f"generate-skill-index: STALE — {OUTPUT_PATH} does not match a fresh regen",
                file=sys.stderr,
            )
            return 2
        print(f"generate-skill-index: fresh — {len(entries)} skills indexed")
        return 0

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        fh.write(generated)
    print(
        f"generate-skill-index: wrote {OUTPUT_PATH} ({len(entries)} skills, "
        f"{len(generated):,} bytes)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
