-- ---------------------------------------------------------------------------
-- Multi-tenant Postgres schema starter
-- ---------------------------------------------------------------------------
-- Generated by data-platform/templates/database-schema-starter.sql
-- Last reviewed: 2026-05-21
--
-- Ships with:
--   * tenants, users, tenant_memberships tables
--   * tenant_id column on every fact table
--   * FORCE ROW LEVEL SECURITY policies
--   * Audit-log columns (created_at, updated_at, created_by, updated_by)
--   * Companion: templates/rls-cross-tenant-test.sql (MUST pass before deploy)
--
-- USAGE:
--   1. Replace <YOUR_FACT_TABLE> with your actual fact tables
--   2. Set the per-request tenant_id via SET LOCAL (in app code or pgbouncer hook)
--   3. Run templates/rls-cross-tenant-test.sql in CI before any merge
--
-- DO NOT:
--   * Set app.tenant_id without LOCAL (connection-pool leak)
--   * Grant BYPASSRLS to viewer-facing roles
--   * Remove FORCE clause (table owners would bypass RLS in ELT pipelines)
-- ---------------------------------------------------------------------------

-- Required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- 1. tenants table (root of tenancy)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenants (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    name          text NOT NULL,
    slug          text UNIQUE NOT NULL,
    status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','archived')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 2. users table (global; not tenant-scoped)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    email         text UNIQUE NOT NULL,
    display_name  text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- 3. tenant_memberships (which user belongs to which tenant + role)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tenant_memberships (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role          text NOT NULL DEFAULT 'viewer' CHECK (role IN ('viewer','editor','admin')),
    created_at    timestamptz NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_tenant_memberships_tenant ON tenant_memberships(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tenant_memberships_user ON tenant_memberships(user_id);

-- ---------------------------------------------------------------------------
-- 4. Example fact table — REPLACE with your actual fact tables
--    Every fact table MUST have tenant_id, FORCE RLS, and an index on tenant_id
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS fact_orders (
    id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id     uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    order_date    date NOT NULL,
    amount        numeric(18,2) NOT NULL,
    customer_id   uuid,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    created_by    uuid REFERENCES users(id),
    updated_by    uuid REFERENCES users(id)
);

-- Tenant index — REQUIRED for RLS performance
CREATE INDEX IF NOT EXISTS idx_fact_orders_tenant ON fact_orders(tenant_id);
CREATE INDEX IF NOT EXISTS idx_fact_orders_tenant_date ON fact_orders(tenant_id, order_date);

-- ---------------------------------------------------------------------------
-- 5. ENABLE + FORCE Row Level Security on the fact table
-- ---------------------------------------------------------------------------
ALTER TABLE fact_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE fact_orders FORCE ROW LEVEL SECURITY;

-- Policy: viewers see only their tenant's data
-- USING + WITH CHECK both required for FOR ALL (read + write)
CREATE POLICY tenant_isolation ON fact_orders
    FOR ALL
    USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

-- ---------------------------------------------------------------------------
-- 6. Application roles
-- ---------------------------------------------------------------------------
-- viewer_role: enforced by RLS (default — no BYPASSRLS)
CREATE ROLE viewer_role NOINHERIT;
GRANT SELECT ON tenants, users, tenant_memberships TO viewer_role;
GRANT SELECT ON fact_orders TO viewer_role;

-- elt_role: bypasses RLS for ELT pipelines (intentional — raw landing before viewer exposure)
CREATE ROLE elt_role NOINHERIT BYPASSRLS;
GRANT SELECT, INSERT, UPDATE, DELETE ON fact_orders TO elt_role;
GRANT SELECT ON tenants, users, tenant_memberships TO elt_role;

-- ---------------------------------------------------------------------------
-- 7. Per-request tenant_id setting (called by app code or pgbouncer hook)
-- ---------------------------------------------------------------------------
-- In app code:
--     BEGIN;
--     SET LOCAL app.tenant_id = '<tenant_id_from_jwt_claim>';
--     -- ... queries here run scoped to that tenant ...
--     COMMIT;
--
-- The LOCAL keyword is REQUIRED. Without it, the setting persists across
-- connection-pooled requests and causes cross-tenant leaks.

-- ---------------------------------------------------------------------------
-- 8. Audit-log trigger (optional but recommended)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_fact_orders_updated_at
    BEFORE UPDATE ON fact_orders
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- 9. Acceptance criteria
-- ---------------------------------------------------------------------------
-- Before merge:
--   * `psql -d <db> -f database-schema-starter.sql` runs clean
--   * `psql -d <db> -f rls-cross-tenant-test.sql` returns ZERO rows from the
--     denial test
--   * Every fact table has: tenant_id column, FORCE RLS, idx on tenant_id, policy
--
-- Refresh triggers for this template:
--   * Postgres major-version with RLS-related changes
--   * New fact table added to engagement schema (re-apply pattern)
--   * Multi-tenant audit incident (this template's contract evolves)
