// ---------------------------------------------------------------------------
// JWT issuer for embedded dashboards
// ---------------------------------------------------------------------------
// Generated by data-platform/templates/jwt-issuer.ts
// Last reviewed: 2026-05-21
//
// Canonical 2026 embed-auth flow: host app's backend issues short-lived JWTs
// (5-15 min) with tenant_id claim → frontend passes JWT to embed → embed
// (Superset / Metabase / Cube / etc.) verifies signature and enforces RLS at
// query time scoped to the JWT's tenant_id.
//
// USAGE:
//   import { issueEmbedToken } from "./jwt-issuer";
//   const token = await issueEmbedToken({
//     userId: "user-123",
//     tenantId: "tenant-abc",
//     audience: "metabase",
//   });
//
// ENVIRONMENT:
//   JWT_SIGNING_KEY — required. HS256 shared secret or RS256 private key.
//     32+ bytes of random for HS256. Never inline in source.
//   JWT_KEY_VERSION — optional. Used in the token header for rotation.
//
// DO NOT:
//   * Hard-code the signing key (the data-platform-smells hook catches this)
//   * Set expiresIn > 30 minutes (the hook catches this too)
//   * Derive tenant_id from the URL or request body (must come from a
//     server-side authenticated session)
// ---------------------------------------------------------------------------

import jwt from "jsonwebtoken";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type EmbedAudience = "metabase" | "superset" | "cube" | "powerbi";

export interface IssueEmbedTokenInput {
  /** End-user identifier from the host app's authenticated session */
  userId: string;
  /** The tenant the viewer can see. NEVER from URL/body — only from session. */
  tenantId: string;
  /** Which embed tool the token is for (audience claim) */
  audience: EmbedAudience;
  /** Optional explicit list of allowed dashboard IDs (defense in depth) */
  allowedDashboards?: string[];
  /** Optional roles for Power BI EffectiveIdentity */
  roles?: string[];
  /** Override default expiration (in seconds). Default: 900 (15 min). MAX: 1800 (30 min). */
  expiresInSeconds?: number;
}

export interface EmbedTokenPayload {
  sub: string;
  tenant_id: string;
  iat: number;
  exp: number;
  iss: string;
  aud: EmbedAudience;
  allowed_dashboards?: string[];
  roles?: string[];
  nonce: string;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_EXPIRES_IN_SECONDS = 900; // 15 min
const MAX_EXPIRES_IN_SECONDS = 1800; // 30 min (hard ceiling)
const ISSUER = process.env.JWT_ISSUER || "data-platform-host";

// ---------------------------------------------------------------------------
// Issuer
// ---------------------------------------------------------------------------

export async function issueEmbedToken(input: IssueEmbedTokenInput): Promise<string> {
  validateEnv();
  validateInput(input);

  const now = Math.floor(Date.now() / 1000);
  const expiresIn = Math.min(
    input.expiresInSeconds ?? DEFAULT_EXPIRES_IN_SECONDS,
    MAX_EXPIRES_IN_SECONDS,
  );

  const payload: EmbedTokenPayload = {
    sub: input.userId,
    tenant_id: input.tenantId,
    iat: now,
    exp: now + expiresIn,
    iss: ISSUER,
    aud: input.audience,
    nonce: crypto.randomUUID(),
    ...(input.allowedDashboards && { allowed_dashboards: input.allowedDashboards }),
    ...(input.roles && { roles: input.roles }),
  };

  const signingKey = process.env.JWT_SIGNING_KEY!;
  const keyVersion = process.env.JWT_KEY_VERSION || "1";

  return jwt.sign(payload, signingKey, {
    algorithm: "HS256",
    header: { alg: "HS256", typ: "JWT", kid: keyVersion },
  });
}

// ---------------------------------------------------------------------------
// Verifier (for smoke testing — production verification happens in the embed)
// ---------------------------------------------------------------------------

export async function verifyEmbedToken(token: string): Promise<EmbedTokenPayload> {
  validateEnv();
  const signingKey = process.env.JWT_SIGNING_KEY!;

  return new Promise((resolve, reject) => {
    jwt.verify(token, signingKey, { algorithms: ["HS256"], issuer: ISSUER }, (err, decoded) => {
      if (err) return reject(err);
      resolve(decoded as EmbedTokenPayload);
    });
  });
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function validateEnv(): void {
  if (!process.env.JWT_SIGNING_KEY) {
    throw new Error("JWT_SIGNING_KEY is not set. Refusing to issue tokens.");
  }
  if (process.env.JWT_SIGNING_KEY.length < 32) {
    throw new Error("JWT_SIGNING_KEY must be at least 32 bytes for HS256.");
  }
}

function validateInput(input: IssueEmbedTokenInput): void {
  if (!input.userId) {
    throw new Error("userId is required.");
  }
  if (!input.tenantId) {
    throw new Error("tenantId is required.");
  }
  if (!input.audience) {
    throw new Error("audience is required.");
  }
  if (input.expiresInSeconds && input.expiresInSeconds > MAX_EXPIRES_IN_SECONDS) {
    throw new Error(`expiresInSeconds capped at ${MAX_EXPIRES_IN_SECONDS} (30 min).`);
  }
}

// ---------------------------------------------------------------------------
// Round-trip smoke test (call manually or in CI)
// ---------------------------------------------------------------------------

export async function smokeTest(): Promise<void> {
  const token = await issueEmbedToken({
    userId: "test-user",
    tenantId: "test-tenant-uuid",
    audience: "metabase",
    expiresInSeconds: 60,
  });
  const decoded = await verifyEmbedToken(token);
  if (decoded.tenant_id !== "test-tenant-uuid") {
    throw new Error("Smoke test failed: tenant_id round-trip broken.");
  }
  if (decoded.aud !== "metabase") {
    throw new Error("Smoke test failed: audience round-trip broken.");
  }
  if (decoded.exp - decoded.iat !== 60) {
    throw new Error("Smoke test failed: expiration round-trip broken.");
  }
  console.log("JWT issuer smoke test PASSED.");
}

// ---------------------------------------------------------------------------
// Notes for security review (per ravenclaude-core/security-reviewer):
//
//   * Algorithm: HS256 for SMB consulting (shared-secret rotation requires
//     coordination; acceptable). For productized SaaS scaling to many clients,
//     switch to RS256 + JWKS so signing keys can rotate without coordination.
//   * Expiration: 5-15 min default; 30-min hard ceiling enforced.
//   * Nonce: included as `nonce` claim for replay protection.
//   * Issuer + Audience: both set; verifier checks both.
//   * Key in env var only — the data-platform-smells hook flags any
//     inline secret.
//
// Refresh triggers:
//   * jsonwebtoken library major-version bump
//   * Switch from HS256 to RS256 (for productized SaaS)
//   * New embed audience added (extend EmbedAudience type)
//   * Cube / Metabase / Superset / Power BI change their JWT contract
// ---------------------------------------------------------------------------
