#!/usr/bin/env python3
"""build-outcome-corpus.py — Phase 1 of verify-before-assert.

Extracts every agent-issued Bash tool call plus its result from the local
transcript corpus into fixed-shape JSONL envelopes, so that every candidate rule
in Phases 3-6 can be MEASURED against real traffic before it is wired.

⛔ THE CORPUS IS NON-STATIONARY. It was generated by the UN-instrumented agent.
Fire rates computed on it are PRE-REGISTRATION THRESHOLDS, not predictions: the
agent adapts to the hook, and adaptation is the point. Phase 11 re-measures on
live data; that re-measurement is mandatory, not optional.

⛔ AN EMPTY RESULT NEEDS A POSITIVE CONTROL. Four synthetic envelopes are planted
into every extraction run and must be recovered, so "0 failures in the corpus"
can never silently mean "the extractor is blind".

Storage contract
----------------
The full corpus carries real command strings and is written to a LOCAL, ignored
run dir by default -- never committed. Only a small hand-checked sample is
committed for the self-test. Every field is scrubbed with the canonical secret
patterns first, in both cases.

Usage
-----
    python3 build-outcome-corpus.py --out <dir> [--transcripts <dir>]
    python3 build-outcome-corpus.py --self-test
    python3 build-outcome-corpus.py --must-fail
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import random
import re
import sys

# ── Bucket floors (Phase 1 pre-build gate) ───────────────────────────────────
MIN_ENVELOPES = 5000
MIN_FAILURES = 200
MIN_EMPTY_STDOUT = 200

# The harness substitutes this placeholder for a command that produced nothing.
# ⛔ Measured 2026-08-25: testing `not stdout.strip()` on the tool_result CONTENT
# reports ZERO empty results across 43,751 envelopes, because the placeholder is
# non-empty text. The emptiness lives in toolUseResult.stdout, not in content.
# control: the placeholder string occurs 540 times while content-emptiness occurs
# 0 times, so the two readings discriminate.
NO_OUTPUT_PLACEHOLDER = "(Bash completed with no output)"

_EXIT_RE = re.compile(r"Exit code (\d+)")

_HERE = os.path.dirname(os.path.abspath(__file__))
_SCRUB_SH = os.path.join(_HERE, "..", "hooks", "_scrub.sh")


class CorpusBlind(RuntimeError):
    """Raised when the extractor cannot prove it can see.

    Never `assert`: python -O strips asserts, which would delete the canary and
    produce exactly the silent-green failure it exists to prevent.
    """


# ── Secret scrubbing — patterns parsed from _scrub.sh, the single source ─────
def _ere_to_python(pat: str) -> str:
    """Translate the POSIX bracket classes _scrub.sh uses into Python re."""
    return (
        pat.replace("[:space:]", r"\s")
        .replace("[:digit:]", r"\d")
        .replace("[:alpha:]", "a-zA-Z")
        .replace("[:alnum:]", "a-zA-Z0-9")
    )


def load_secret_patterns(path: str = _SCRUB_SH) -> list:
    """Parse _secret_patterns=( ... ) out of the canonical scrubber.

    Parsed rather than re-declared so the corpus builder cannot drift from the
    scrubber the emit path uses. A parse that finds nothing raises: a scrubber
    that silently matches nothing is worse than no scrubber, because it looks
    like it ran.
    """
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            text = fh.read()
    except OSError as exc:
        raise CorpusBlind(f"cannot read the canonical scrubber at {path}: {exc}")
    block = re.search(r"^_secret_patterns=\((.*?)^\)", text, re.S | re.M)
    if not block:
        raise CorpusBlind("_secret_patterns=( ... ) not found in _scrub.sh")
    pats = re.findall(r"^\s*'([^']+)'\s*$", block.group(1), re.M)
    if len(pats) < 5:
        raise CorpusBlind(
            f"parsed only {len(pats)} secret patterns from _scrub.sh; "
            "the parse is broken, not the scrubber"
        )
    return [re.compile(_ere_to_python(p)) for p in pats]


def scrub(text: str, pats: list) -> str:
    if not text:
        return text
    for p in pats:
        text = p.sub("[REDACTED]", text)
    return text


# ── Command-shape derivation ─────────────────────────────────────────────────
# ⛔ DELIBERATE DUPLICATION, declared. hooks/triage-outcome.sh derives the same
# booleans in bash at runtime. This is the offline twin used for measurement.
# An untested refactor of a live hook is the worse trade; the honest cost is that
# the two derivations can drift, so any rule promoted out of the replay harness
# ships with its own hook-level fixture rather than inheriting this one's verdict.
_LIMIT_RE = re.compile(r"\|\s*(head|tail)\b|(?<!\w)-m\s+\d|--max-count")
_DEVNULL_OUT_RE = re.compile(r"(?<!2)>\s*/dev/null")
_2DEVNULL_RE = re.compile(r"2>\s*/dev/null|2>&1\s*>\s*/dev/null")
_MERGE_RE = re.compile(r"2>&1")
_GLOB_RE = re.compile(r"[*?]|\[[^\]]+\]")
_PAGINATED_RE = re.compile(r"\bgh\s+api\b|per_page=|\?page=")

_FAMILY_PATTERNS = [
    ("grep", re.compile(r"^\s*(grep|rg|ag|ack)\b|\|\s*(grep|rg)\b")),
    ("find", re.compile(r"^\s*(find|fd)\b|\|\s*(find|fd)\b")),
    ("git", re.compile(r"^\s*git\b|\bgit\s+(log|show|diff|rev-parse|branch|status)\b")),
    ("http", re.compile(r"^\s*(curl|wget|http|gh)\b")),
    ("jq", re.compile(r"\bjq\b")),
    ("build", re.compile(r"\b(npm|pnpm|yarn|make|cargo|go|tsc|astro|vite|pytest|ruff)\b")),
    ("pkg", re.compile(r"\b(brew|apt|pip|pip3|pipx)\b")),
    ("fs", re.compile(r"^\s*(ls|cat|head|tail|wc|stat|du|df|file|readlink)\b")),
    ("shell", re.compile(r"^\s*(echo|printf|export|source|eval|test|\[)\b")),
]

_MUTATING_RE = re.compile(
    r"^\s*(rm|mv|cp|mkdir|touch|chmod|chown|ln|install|tee)\b"
    r"|>\s*[^|&\s]|>>|\bgit\s+(add|commit|push|checkout|switch|merge|rebase|reset|restore|clean)\b"
    r"|\b(npm|pnpm|yarn|pip|pip3|brew)\s+(install|add|publish|uninstall)\b"
)

# ⛔ Noise redirections must be stripped BEFORE the mutation test, or the test
# eats its own subject. MEASURED 2026-08-25: with `2>/dev/null` left in place,
# `has_2devnull` was true on 7,283 envelopes while the R-1 candidate rule
# (2>/dev/null AND evidence-bearing) fired on ZERO of 26,980 — because the
# redirect's own `>` matched the mutating-redirect branch and disqualified every
# command the rule exists to catch. A rule that measures 0.00% reads as "no risk
# here" and would have been dropped for the wrong reason.
# control: after stripping, R-1 fires on a non-zero population while the planted
# mutating fixtures (`> out.txt`, `git add`) still classify as non-evidence-bearing.
_NOISE_REDIR_RE = re.compile(r"2>\s*&\s*1|&>\s*/dev/null|\d?>\s*/dev/null")


def derive_family(cmd: str) -> str:
    for name, pat in _FAMILY_PATTERNS:
        if pat.search(cmd):
            return name
    return "other"


def derive_shape(cmd: str) -> dict:
    """Derived LEXICAL booleans only.

    The raw command never reaches the taxonomy module: the injection boundary is
    enforced by this shape, not by reviewer discipline.
    """
    return {
        "has_devnull_stdout": bool(_DEVNULL_OUT_RE.search(cmd)),
        "has_2devnull": bool(_2DEVNULL_RE.search(cmd)),
        "has_output_limit": bool(_LIMIT_RE.search(cmd)),
        "is_pipeline": "|" in cmd,
        "has_stderr_merge": bool(_MERGE_RE.search(cmd)),
        "has_glob": bool(_GLOB_RE.search(cmd)),
        "has_relative_path": not bool(re.search(r"(^|\s)/", cmd)),
        "has_paginated_client": bool(_PAGINATED_RE.search(cmd)),
        "is_evidence_bearing": not bool(_MUTATING_RE.search(_NOISE_REDIR_RE.sub(" ", cmd))),
        "tool_family": derive_family(cmd),
    }


# ── stderr label derivation ──────────────────────────────────────────────────
# ⛔ Labels are derived from STDERR ONLY. Deriving them from stdout is a measured
# defect: on 2026-08-25 the shipped triage hook produced `permission-denied`,
# `conn-refused`, `in-progress` and `timeout` labels three times in one session
# from words appearing in a SUCCESSFUL command's stdout, with stderr empty.
# control: derive_labels("") returns [] while derive_labels(real_stderr) does
# not, and both directions are asserted in --self-test, so a future edit that
# widens the input back to stdout turns the suite red.
_LABEL_RULES = [
    ("command-not-found", re.compile(r"command not found|: not found", re.I)),
    ("no-such-file", re.compile(r"No such file or directory|no matches found", re.I)),
    ("permission-denied", re.compile(r"Permission denied|EACCES", re.I)),
    ("is-a-directory", re.compile(r"Is a directory", re.I)),
    ("not-a-git-repo", re.compile(r"not a git repository", re.I)),
    ("ambiguous-argument", re.compile(r"ambiguous argument|unknown revision", re.I)),
    ("broken-pipe", re.compile(r"Broken pipe|SIGPIPE", re.I)),
    ("json-parse-error", re.compile(r"parse error|invalid JSON|JSONDecodeError", re.I)),
    ("rate-limited", re.compile(r"rate limit|\b429\b|API rate", re.I)),
    ("server-error", re.compile(r"\b5[0-9][0-9]\b|Internal Server Error", re.I)),
    ("timeout", re.compile(r"timed out|timeout", re.I)),
    ("conn-refused", re.compile(r"Connection refused|Connection reset", re.I)),
    ("dns-failure", re.compile(r"Could not resolve host|Name or service not known", re.I)),
    ("auth-denied", re.compile(r"\b40[13]\b|Unauthorized|Forbidden|Bad credentials", re.I)),
    ("in-progress", re.compile(r"in progress|still running|queued", re.I)),
]

_INDETERMINATE = frozenset(
    {"rate-limited", "server-error", "timeout", "conn-refused", "dns-failure",
     "auth-denied", "in-progress"}
)


def derive_labels(stderr: str) -> list:
    if not stderr or not stderr.strip():
        return []
    out = [name for name, pat in _LABEL_RULES if pat.search(stderr)]
    if not out:
        out = ["stderr-nonempty"]
    return sorted(out)


# ── Planted positive controls ────────────────────────────────────────────────
PLANTED = [
    {
        "_planted": "rc127",
        "cmd": "rc-canary-binary --version",
        "stdout": "",
        "stderr": "zsh: command not found: rc-canary-binary",
        "content": "Exit code 127",
        "is_error": True,
    },
    {
        "_planted": "empty-stdout",
        "cmd": "grep -n 'rc-canary-token' /etc/hosts",
        "stdout": "",
        "stderr": "",
        "content": NO_OUTPUT_PLACEHOLDER,
        "is_error": False,
    },
    {
        "_planted": "clean",
        "cmd": "echo rc-canary-ok",
        "stdout": "rc-canary-ok\n",
        "stderr": "",
        "content": "rc-canary-ok",
        "is_error": False,
    },
    {
        "_planted": "secret",
        "cmd": (
            "curl -H 'Authorization: Bearer "
            "ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' https://api.example"
        ),
        "stdout": "",
        "stderr": "",
        "content": NO_OUTPUT_PLACEHOLDER,
        "is_error": False,
    },
]

_PLANTED_TOKEN = "ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"


def _verdict(exit_code, stdout_empty, labels):
    if any(lbl in _INDETERMINATE for lbl in labels):
        return "indeterminate"
    if exit_code not in (0, None):
        return "negative"
    if stdout_empty:
        return "empty-null"
    return "clean"


def make_envelope(cmd, stdout, stderr, content, is_error, src, pats, blind=False, cwd=""):
    """Build one fixed-shape envelope.

    `blind` is the --must-fail lever: it deletes the exit-code derivation, which
    must drive the self-test red.
    """
    stdout_empty = (not stdout.strip()) or content.strip() == NO_OUTPUT_PLACEHOLDER
    exit_code = None
    if not blind:
        m = _EXIT_RE.search(content or "")
        if m:
            exit_code = int(m.group(1))
        elif is_error:
            exit_code = 1
        else:
            exit_code = 0
    labels = derive_labels(stderr)
    return {
        "src": src,
        # cwd is required by any rule that reasons about WHERE a path resolves
        # (Phase 4 R-4). Without it that rule is unmeasurable, and an
        # unmeasurable rule must not ship.
        "cwd": cwd,
        "cmd": scrub(cmd, pats),
        "shape": derive_shape(cmd),
        "exit_code": exit_code,
        "stdout_empty": bool(stdout_empty),
        "stderr_labels": labels,
        "is_error": bool(is_error),
        "verdict": _verdict(exit_code, stdout_empty, labels),
        "stderr_sample": scrub(stderr, pats)[:400],
    }


def iter_transcripts(root):
    yield from sorted(glob.glob(os.path.join(root, "**", "*.jsonl"), recursive=True))


def extract(root, pats, blind=False, limit=None):
    envelopes = []
    pending = {}
    for fp in iter_transcripts(root):
        try:
            fh = open(fp, encoding="utf-8", errors="replace")
        except OSError:
            continue
        with fh:
            for line in fh:
                if '"tool_use"' not in line and '"tool_result"' not in line:
                    continue
                try:
                    rec = json.loads(line)
                except Exception:
                    continue
                msg = rec.get("message")
                if not isinstance(msg, dict):
                    continue
                blocks = msg.get("content")
                if not isinstance(blocks, list):
                    continue
                for b in blocks:
                    if not isinstance(b, dict):
                        continue
                    if b.get("type") == "tool_use" and b.get("name") == "Bash":
                        cmd = (b.get("input") or {}).get("command") or ""
                        if cmd:
                            pending[b.get("id")] = cmd
                    elif b.get("type") == "tool_result":
                        cmd = pending.pop(b.get("tool_use_id"), None)
                        if cmd is None:
                            continue
                        tur = rec.get("toolUseResult")
                        stdout = stderr = ""
                        if isinstance(tur, dict):
                            stdout = tur.get("stdout") or ""
                            stderr = tur.get("stderr") or ""
                        content = b.get("content") or ""
                        if not isinstance(content, str):
                            content = ""
                        envelopes.append(
                            make_envelope(
                                cmd, stdout, stderr, content,
                                bool(b.get("is_error")),
                                os.path.basename(fp), pats, blind,
                                cwd=rec.get("cwd") or "",
                            )
                        )
                        if limit and len(envelopes) >= limit:
                            return envelopes
    return envelopes


def plant(envelopes, pats, blind=False):
    out = list(envelopes)
    for p in PLANTED:
        env = make_envelope(p["cmd"], p["stdout"], p["stderr"], p["content"],
                            p["is_error"], "PLANTED", pats, blind)
        env["planted"] = p["_planted"]
        out.append(env)
    return out


def buckets(envelopes):
    return {
        "total": len(envelopes),
        "failures": sum(1 for e in envelopes if e["verdict"] == "negative" or e["is_error"]),
        "empty_stdout": sum(1 for e in envelopes if e["stdout_empty"]),
        "indeterminate": sum(1 for e in envelopes if e["verdict"] == "indeterminate"),
        "clean": sum(1 for e in envelopes if e["verdict"] == "clean"),
    }


def gate_report(b):
    rows = [
        ("envelopes", b["total"], MIN_ENVELOPES),
        ("failures", b["failures"], MIN_FAILURES),
        ("empty-stdout", b["empty_stdout"], MIN_EMPTY_STDOUT),
    ]
    ok = True
    lines = []
    for name, got, floor in rows:
        good = got >= floor
        ok = ok and good
        lines.append(f"  {'PASS' if good else 'SHORT'}  {name:<14} {got:>7} (floor {floor})")
    return ok, "\n".join(lines)


# ── Self-test / must-fail ────────────────────────────────────────────────────
def run_self_test(blind=False) -> int:
    pats = load_secret_patterns()
    failures = []

    planted = plant([], pats, blind=blind)
    by = {e.get("planted"): e for e in planted}

    # 1. all planted envelopes recovered
    for key in ("rc127", "empty-stdout", "clean", "secret"):
        if key not in by:
            failures.append(f"planted envelope {key!r} was not recovered")

    # 2. the rc=127 control must carry its exit code and a negative verdict
    e = by.get("rc127")
    if e is not None:
        if e["exit_code"] != 127:
            failures.append(f"rc127 control: exit_code={e['exit_code']!r}, expected 127")
        if e["verdict"] != "negative":
            failures.append(f"rc127 control: verdict={e['verdict']!r}, expected 'negative'")
        if "command-not-found" not in e["stderr_labels"]:
            failures.append(
                f"rc127 control: labels={e['stderr_labels']}, expected command-not-found"
            )

    # 3. the empty-stdout control must be seen as empty, NOT as clean
    e = by.get("empty-stdout")
    if e is not None:
        if not e["stdout_empty"]:
            failures.append("empty-stdout control: placeholder was not read as empty")
        if e["verdict"] != "empty-null":
            failures.append(
                f"empty-stdout control: verdict={e['verdict']!r}, expected 'empty-null'"
            )

    # 4. the clean control must produce no finding (the negative control)
    e = by.get("clean")
    if e is not None and e["verdict"] != "clean":
        failures.append(f"clean control: verdict={e['verdict']!r}, expected 'clean'")

    # 5. secret scrub — a planted token must not survive into the envelope
    e = by.get("secret")
    if e is not None:
        blob = json.dumps(e)
        if _PLANTED_TOKEN in blob:
            failures.append("SECRET LEAK: the planted token survived into the envelope")
        if "[REDACTED]" not in blob:
            failures.append("scrubber did not fire on the planted secret control")

    # 6. ⛔ labels come from stderr ONLY, and the derivation is not blind
    if derive_labels("") != []:
        failures.append("label derivation fired on empty stderr")
    if derive_labels("zsh: command not found: x") == []:
        failures.append("label derivation is blind: it found nothing in real stderr text")

    # 7. the scrubber parse is a positive control in its own right
    if len(pats) < 5:
        failures.append(f"only {len(pats)} secret patterns parsed from _scrub.sh")

    # 8. ⛔ evidence-bearing must survive a noise redirection, and must still
    # reject real mutation. Both directions, or the fix regresses silently.
    for cmd in ("grep -rn foo src/ 2>/dev/null", "ls -la 2>&1", "rg bar >/dev/null"):
        if not derive_shape(cmd)["is_evidence_bearing"]:
            failures.append(f"noise redirection disqualified an evidence-bearing command: {cmd!r}")
    for cmd in ("grep -rn foo src/ > out.txt", "git add -A", "rm -rf build/"):
        if derive_shape(cmd)["is_evidence_bearing"]:
            failures.append(f"a mutating command classified as evidence-bearing: {cmd!r}")

    for f in failures:
        print(f"FAIL: {f}")
    if failures:
        print(f"\nself-test FAILED — {len(failures)} finding(s)")
        return 1
    print("PASS: 8 checks — planted controls recovered, scrub fired, labels stderr-only,")
    print("      evidence-bearing survives noise redirection and still rejects mutation")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="build the outcome corpus")
    ap.add_argument("--out")
    ap.add_argument("--transcripts", default=os.path.expanduser("~/.claude/projects"))
    ap.add_argument("--limit", type=int)
    ap.add_argument("--sample", type=int, default=0,
                    help="also write a hand-checkable random sample of N envelopes")
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--must-fail", action="store_true")
    args = ap.parse_args()

    if args.self_test:
        return run_self_test()
    if args.must_fail:
        # Blind the exit-code derivation; the self-test MUST go red.
        rc = run_self_test(blind=True)
        if rc == 0:
            print("MUST-FAIL VIOLATED: the self-test passed with the extractor blinded")
            return 1
        print("PASS (--must-fail): blinding the exit-code derivation turns the self-test red")
        return 0

    if not args.out:
        ap.error("--out is required unless --self-test/--must-fail")

    pats = load_secret_patterns()
    if not os.path.isdir(args.transcripts):
        print(f"SHORT: no transcript tree at {args.transcripts}")
        return 2
    envelopes = plant(extract(args.transcripts, pats, limit=args.limit), pats)
    os.makedirs(args.out, exist_ok=True)
    path = os.path.join(args.out, "corpus.jsonl")
    with open(path, "w", encoding="utf-8") as fh:
        for e in envelopes:
            fh.write(json.dumps(e, ensure_ascii=False) + "\n")

    b = buckets(envelopes)
    ok, report = gate_report(b)
    print(f"wrote {path}")
    print(report)
    print(f"  (indeterminate {b['indeterminate']}, clean {b['clean']})")
    if args.sample:
        rnd = random.Random(20260825)
        sm = rnd.sample(envelopes, min(args.sample, len(envelopes)))
        spath = os.path.join(args.out, "sample.jsonl")
        with open(spath, "w", encoding="utf-8") as fh:
            for e in sm:
                fh.write(json.dumps(e, ensure_ascii=False) + "\n")
        print(f"wrote {spath} ({len(sm)} rows for hand classification)")
    if not ok:
        print("\n⛔ CORPUS INSUFFICIENT — trigger-rate claims in later phases must be")
        print("   marked `unverified` rather than estimated.")
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main())
